// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentToken = `-- name: CreateAgentToken :one

INSERT INTO agent_api_tokens (name, token_hash, token_prefix, scopes, all_projects, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, token_hash, token_prefix, scopes, all_projects, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type CreateAgentTokenParams struct {
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []byte             `json:"scopes"`
	AllProjects bool               `json:"all_projects"`
	CreatedBy   int32              `json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Запросы контекста agenttokens (v1 CRUD + v2 bearer-auth).
func (q *Queries) CreateAgentToken(ctx context.Context, arg CreateAgentTokenParams) (AgentApiToken, error) {
	row := q.db.QueryRow(ctx, createAgentToken,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.AllProjects,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i AgentApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.AllProjects,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentToken = `-- name: DeleteAgentToken :exec
DELETE FROM agent_api_tokens WHERE id = $1
`

func (q *Queries) DeleteAgentToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAgentToken, id)
	return err
}

const getAgentTokenByHash = `-- name: GetAgentTokenByHash :one
SELECT id, name, token_hash, token_prefix, scopes, all_projects, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at FROM agent_api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAgentTokenByHash(ctx context.Context, tokenHash string) (AgentApiToken, error) {
	row := q.db.QueryRow(ctx, getAgentTokenByHash, tokenHash)
	var i AgentApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.AllProjects,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTokenByID = `-- name: GetAgentTokenByID :one
SELECT id, name, token_hash, token_prefix, scopes, all_projects, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at FROM agent_api_tokens WHERE id = $1
`

func (q *Queries) GetAgentTokenByID(ctx context.Context, id int32) (AgentApiToken, error) {
	row := q.db.QueryRow(ctx, getAgentTokenByID, id)
	var i AgentApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.AllProjects,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoleByID = `-- name: GetUserRoleByID :one
SELECT id, role FROM users WHERE id = $1
`

type GetUserRoleByIDRow struct {
	ID   int32    `json:"id"`
	Role UserRole `json:"role"`
}

func (q *Queries) GetUserRoleByID(ctx context.Context, id int32) (GetUserRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserRoleByID, id)
	var i GetUserRoleByIDRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const insertAgentTokenGrant = `-- name: InsertAgentTokenGrant :exec
INSERT INTO agent_api_token_project_grants (token_id, project_id) VALUES ($1, $2)
ON CONFLICT ON CONSTRAINT uq_agent_api_token_project DO NOTHING
`

type InsertAgentTokenGrantParams struct {
	TokenID   int32 `json:"token_id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) InsertAgentTokenGrant(ctx context.Context, arg InsertAgentTokenGrantParams) error {
	_, err := q.db.Exec(ctx, insertAgentTokenGrant, arg.TokenID, arg.ProjectID)
	return err
}

const listAgentTokenGrants = `-- name: ListAgentTokenGrants :many
SELECT project_id FROM agent_api_token_project_grants WHERE token_id = $1 ORDER BY project_id
`

func (q *Queries) ListAgentTokenGrants(ctx context.Context, tokenID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listAgentTokenGrants, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var project_id int32
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTokensByCreator = `-- name: ListAgentTokensByCreator :many
SELECT id, name, token_hash, token_prefix, scopes, all_projects, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at FROM agent_api_tokens WHERE created_by = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAgentTokensByCreator(ctx context.Context, createdBy int32) ([]AgentApiToken, error) {
	rows, err := q.db.Query(ctx, listAgentTokensByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentApiToken{}
	for rows.Next() {
		var i AgentApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Scopes,
			&i.AllProjects,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberProjectIDs = `-- name: ListMemberProjectIDs :many
SELECT project_id FROM project_members WHERE user_id = $1
`

func (q *Queries) ListMemberProjectIDs(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listMemberProjectIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var project_id int32
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgentTokenLastUsed = `-- name: TouchAgentTokenLastUsed :exec
UPDATE agent_api_tokens SET last_used_at = $2 WHERE id = $1
`

type TouchAgentTokenLastUsedParams struct {
	ID         int32              `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchAgentTokenLastUsed(ctx context.Context, arg TouchAgentTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAgentTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
