// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_logs (user_id, action, entity_type, entity_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	UserID     pgtype.Int4 `json:"user_id"`
	Action     string      `json:"action"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   pgtype.Int4 `json:"entity_id"`
	Details    []byte      `json:"details"`
	IpAddress  pgtype.Text `json:"ip_address"`
}

// Запросы контекста audit. Пишем журнал действий; чтение — в контексте audit позже.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
	)
	return err
}
