// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO invitations (email, full_name, role, project_role, token_hash, status, expires_at, invited_by)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, $7)
RETURNING id, email, full_name, role, project_role, token_hash, status, expires_at, invited_by, accepted_at, accepted_user_id, created_at, updated_at
`

type CreateInvitationParams struct {
	Email       string             `json:"email"`
	FullName    pgtype.Text        `json:"full_name"`
	Role        UserRole           `json:"role"`
	ProjectRole ProjectRole        `json:"project_role"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	InvitedBy   pgtype.Int4        `json:"invited_by"`
}

// ─────────────────────────── invitations ───────────────────────────
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.ProjectRole,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.InvitedBy,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.ProjectRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ─────────────────────────── password_reset_tokens ───────────────────────────
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createReactivationToken = `-- name: CreateReactivationToken :one

INSERT INTO account_reactivation_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateReactivationTokenParams struct {
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ─────────────────────────── account_reactivation_tokens ───────────────────────────
func (q *Queries) CreateReactivationToken(ctx context.Context, arg CreateReactivationTokenParams) (AccountReactivationToken, error) {
	row := q.db.QueryRow(ctx, createReactivationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i AccountReactivationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, full_name, password_hash, role, project_role, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, email, full_name, avatar_minio_bucket, avatar_minio_key, avatar_content_type, avatar_uploaded_at, password_hash, password_changed_at, totp_secret, totp_enabled, totp_confirmed_at, role, project_role, is_active, is_locked, tags, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	FullName     pgtype.Text `json:"full_name"`
	PasswordHash string      `json:"password_hash"`
	Role         UserRole    `json:"role"`
	ProjectRole  ProjectRole `json:"project_role"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.Role,
		arg.ProjectRole,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.AvatarMinioBucket,
		&i.AvatarMinioKey,
		&i.AvatarContentType,
		&i.AvatarUploadedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpConfirmedAt,
		&i.Role,
		&i.ProjectRole,
		&i.IsActive,
		&i.IsLocked,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const disableUserTotp = `-- name: DisableUserTotp :exec
UPDATE users SET totp_enabled = false, totp_secret = NULL, totp_confirmed_at = NULL WHERE id = $1
`

func (q *Queries) DisableUserTotp(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, disableUserTotp, id)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const enableUserTotp = `-- name: EnableUserTotp :exec
UPDATE users SET totp_enabled = true, totp_confirmed_at = now() WHERE id = $1
`

func (q *Queries) EnableUserTotp(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, enableUserTotp, id)
	return err
}

const expireUserUnusedPasswordResetTokens = `-- name: ExpireUserUnusedPasswordResetTokens :exec
UPDATE password_reset_tokens SET used_at = now() WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ExpireUserUnusedPasswordResetTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, expireUserUnusedPasswordResetTokens, userID)
	return err
}

const expireUserUnusedReactivationTokens = `-- name: ExpireUserUnusedReactivationTokens :exec
UPDATE account_reactivation_tokens SET used_at = now() WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ExpireUserUnusedReactivationTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, expireUserUnusedReactivationTokens, userID)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, email, full_name, role, project_role, token_hash, status, expires_at, invited_by, accepted_at, accepted_user_id, created_at, updated_at FROM invitations WHERE token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.ProjectRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordResetByHash = `-- name: GetPasswordResetByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvitationByEmail = `-- name: GetPendingInvitationByEmail :one
SELECT id, email, full_name, role, project_role, token_hash, status, expires_at, invited_by, accepted_at, accepted_user_id, created_at, updated_at FROM invitations WHERE email = $1 AND status = 'pending' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPendingInvitationByEmail(ctx context.Context, email string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByEmail, email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.ProjectRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReactivationByHash = `-- name: GetReactivationByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM account_reactivation_tokens WHERE token_hash = $1
`

func (q *Queries) GetReactivationByHash(ctx context.Context, tokenHash string) (AccountReactivationToken, error) {
	row := q.db.QueryRow(ctx, getReactivationByHash, tokenHash)
	var i AccountReactivationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenForUser = `-- name: GetRefreshTokenForUser :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at FROM refresh_tokens WHERE token_hash = $1 AND user_id = $2
`

type GetRefreshTokenForUserParams struct {
	TokenHash string `json:"token_hash"`
	UserID    int32  `json:"user_id"`
}

func (q *Queries) GetRefreshTokenForUser(ctx context.Context, arg GetRefreshTokenForUserParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUser, arg.TokenHash, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, full_name, avatar_minio_bucket, avatar_minio_key, avatar_content_type, avatar_uploaded_at, password_hash, password_changed_at, totp_secret, totp_enabled, totp_confirmed_at, role, project_role, is_active, is_locked, tags, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.AvatarMinioBucket,
		&i.AvatarMinioKey,
		&i.AvatarContentType,
		&i.AvatarUploadedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpConfirmedAt,
		&i.Role,
		&i.ProjectRole,
		&i.IsActive,
		&i.IsLocked,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one


SELECT id, username, email, full_name, avatar_minio_bucket, avatar_minio_key, avatar_content_type, avatar_uploaded_at, password_hash, password_changed_at, totp_secret, totp_enabled, totp_confirmed_at, role, project_role, is_active, is_locked, tags, created_at, updated_at FROM users WHERE id = $1
`

// Запросы контекста auth. Растут по мере порта роутеров auth/users.
// Колонки — из baseline (00001_baseline.sql). sqlc-синтаксис имён: `-- name: X :kind`.
// ─────────────────────────── users ───────────────────────────
func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.AvatarMinioBucket,
		&i.AvatarMinioKey,
		&i.AvatarContentType,
		&i.AvatarUploadedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpConfirmedAt,
		&i.Role,
		&i.ProjectRole,
		&i.IsActive,
		&i.IsLocked,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, full_name, avatar_minio_bucket, avatar_minio_key, avatar_content_type, avatar_uploaded_at, password_hash, password_changed_at, totp_secret, totp_enabled, totp_confirmed_at, role, project_role, is_active, is_locked, tags, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.AvatarMinioBucket,
		&i.AvatarMinioKey,
		&i.AvatarContentType,
		&i.AvatarUploadedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpConfirmedAt,
		&i.Role,
		&i.ProjectRole,
		&i.IsActive,
		&i.IsLocked,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked_at
`

type InsertRefreshTokenParams struct {
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ─────────────────────────── refresh_tokens ───────────────────────────
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE invitations
SET status = 'accepted', accepted_at = now(), accepted_user_id = $2
WHERE id = $1
`

type MarkInvitationAcceptedParams struct {
	ID             int32       `json:"id"`
	AcceptedUserID pgtype.Int4 `json:"accepted_user_id"`
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, arg.ID, arg.AcceptedUserID)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}

const markReactivationUsed = `-- name: MarkReactivationUsed :exec
UPDATE account_reactivation_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkReactivationUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markReactivationUsed, id)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE invitations SET status = 'revoked' WHERE id = $1
`

func (q *Queries) RevokeInvitation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeInvitation, id)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $2 WHERE id = $1
`

type SetUserActiveParams struct {
	ID       int32 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}

const setUserLocked = `-- name: SetUserLocked :exec
UPDATE users SET is_locked = $2 WHERE id = $1
`

type SetUserLockedParams struct {
	ID       int32 `json:"id"`
	IsLocked bool  `json:"is_locked"`
}

func (q *Queries) SetUserLocked(ctx context.Context, arg SetUserLockedParams) error {
	_, err := q.db.Exec(ctx, setUserLocked, arg.ID, arg.IsLocked)
	return err
}

const setUserTotpSecret = `-- name: SetUserTotpSecret :exec

UPDATE users SET totp_secret = $2 WHERE id = $1
`

type SetUserTotpSecretParams struct {
	ID         int32       `json:"id"`
	TotpSecret pgtype.Text `json:"totp_secret"`
}

// ─────────────────────────── 2FA (TOTP) ───────────────────────────
func (q *Queries) SetUserTotpSecret(ctx context.Context, arg SetUserTotpSecretParams) error {
	_, err := q.db.Exec(ctx, setUserTotpSecret, arg.ID, arg.TotpSecret)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, password_changed_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
