// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM workspace_integrations WHERE key_name = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, keyName string) error {
	_, err := q.db.Exec(ctx, deleteIntegration, keyName)
	return err
}

const getIntegration = `-- name: GetIntegration :one

SELECT key_name, value_encrypted, updated_by, updated_at
FROM workspace_integrations
WHERE key_name = $1
`

// Контекст integrations: workspace-level API-ключи (зашифрованы Fernet, BYTEA).
// Секреты наружу не отдаём — только факт «configured» + updated_at.
func (q *Queries) GetIntegration(ctx context.Context, keyName string) (WorkspaceIntegration, error) {
	row := q.db.QueryRow(ctx, getIntegration, keyName)
	var i WorkspaceIntegration
	err := row.Scan(
		&i.KeyName,
		&i.ValueEncrypted,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT key_name, updated_by, updated_at
FROM workspace_integrations
ORDER BY key_name
`

type ListIntegrationsRow struct {
	KeyName   string             `json:"key_name"`
	UpdatedBy pgtype.Int4        `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListIntegrations(ctx context.Context) ([]ListIntegrationsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationsRow{}
	for rows.Next() {
		var i ListIntegrationsRow
		if err := rows.Scan(&i.KeyName, &i.UpdatedBy, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntegration = `-- name: UpsertIntegration :exec
INSERT INTO workspace_integrations (key_name, value_encrypted, updated_by, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key_name) DO UPDATE
SET value_encrypted = EXCLUDED.value_encrypted,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
`

type UpsertIntegrationParams struct {
	KeyName        string      `json:"key_name"`
	ValueEncrypted []byte      `json:"value_encrypted"`
	UpdatedBy      pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) error {
	_, err := q.db.Exec(ctx, upsertIntegration, arg.KeyName, arg.ValueEncrypted, arg.UpdatedBy)
	return err
}
