// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHosts = `-- name: CountHosts :one
SELECT count(*) FROM hosts
WHERE project_id = $1
  AND ($2::text IS NULL OR origin = $2)
  AND ($3::host_status IS NULL OR status = $3)
`

type CountHostsParams struct {
	ProjectID int32          `json:"project_id"`
	Origin    pgtype.Text    `json:"origin"`
	Status    NullHostStatus `json:"status"`
}

func (q *Queries) CountHosts(ctx context.Context, arg CountHostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHosts, arg.ProjectID, arg.Origin, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const deleteHost = `-- name: DeleteHost :exec
DELETE FROM hosts WHERE id = $1 AND project_id = $2
`

type DeleteHostParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) DeleteHost(ctx context.Context, arg DeleteHostParams) error {
	_, err := q.db.Exec(ctx, deleteHost, arg.ID, arg.ProjectID)
	return err
}

const deleteHostIP = `-- name: DeleteHostIP :exec
DELETE FROM host_ip_addresses WHERE id = $1
`

func (q *Queries) DeleteHostIP(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHostIP, id)
	return err
}

const deletePort = `-- name: DeletePort :exec
DELETE FROM ports WHERE id = $1
`

func (q *Queries) DeletePort(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePort, id)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const findEndpointByPathMethod = `-- name: FindEndpointByPathMethod :one
SELECT id, host_id, path, method, description, query_params, request_body, request_content_type, request_headers, created_at, updated_at FROM endpoints
WHERE host_id = $1 AND path = $2
  AND method IS NOT DISTINCT FROM $3
  AND id <> $4
LIMIT 1
`

type FindEndpointByPathMethodParams struct {
	HostID    int32          `json:"host_id"`
	Path      string         `json:"path"`
	Method    NullHttpMethod `json:"method"`
	ExcludeID int32          `json:"exclude_id"`
}

func (q *Queries) FindEndpointByPathMethod(ctx context.Context, arg FindEndpointByPathMethodParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, findEndpointByPathMethod,
		arg.HostID,
		arg.Path,
		arg.Method,
		arg.ExcludeID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Path,
		&i.Method,
		&i.Description,
		&i.QueryParams,
		&i.RequestBody,
		&i.RequestContentType,
		&i.RequestHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPortDup = `-- name: FindPortDup :one
SELECT id, host_id, ip_address_id, port_number, protocol, state, http_status, created_at, updated_at FROM ports
WHERE ip_address_id = $1 AND port_number = $2 AND protocol = $3
  AND id <> $4
LIMIT 1
`

type FindPortDupParams struct {
	IpAddressID int32        `json:"ip_address_id"`
	PortNumber  int32        `json:"port_number"`
	Protocol    PortProtocol `json:"protocol"`
	ExcludeID   int32        `json:"exclude_id"`
}

func (q *Queries) FindPortDup(ctx context.Context, arg FindPortDupParams) (Port, error) {
	row := q.db.QueryRow(ctx, findPortDup,
		arg.IpAddressID,
		arg.PortNumber,
		arg.Protocol,
		arg.ExcludeID,
	)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.IpAddressID,
		&i.PortNumber,
		&i.Protocol,
		&i.State,
		&i.HttpStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findServiceByName = `-- name: FindServiceByName :one
SELECT id, port_id, name, version, banner, created_at, updated_at FROM services WHERE port_id = $1 AND name = $2 LIMIT 1
`

type FindServiceByNameParams struct {
	PortID int32  `json:"port_id"`
	Name   string `json:"name"`
}

func (q *Queries) FindServiceByName(ctx context.Context, arg FindServiceByNameParams) (Service, error) {
	row := q.db.QueryRow(ctx, findServiceByName, arg.PortID, arg.Name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.PortID,
		&i.Name,
		&i.Version,
		&i.Banner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointForHost = `-- name: GetEndpointForHost :one
SELECT id, host_id, path, method, description, query_params, request_body, request_content_type, request_headers, created_at, updated_at FROM endpoints WHERE id = $1 AND host_id = $2
`

type GetEndpointForHostParams struct {
	ID     int32 `json:"id"`
	HostID int32 `json:"host_id"`
}

func (q *Queries) GetEndpointForHost(ctx context.Context, arg GetEndpointForHostParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointForHost, arg.ID, arg.HostID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Path,
		&i.Method,
		&i.Description,
		&i.QueryParams,
		&i.RequestBody,
		&i.RequestContentType,
		&i.RequestHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHost = `-- name: GetHost :one
SELECT id, project_id, ip_address, hostname, status, os_type, notes, origin, created_at, updated_at FROM hosts WHERE id = $1 AND project_id = $2
`

type GetHostParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) GetHost(ctx context.Context, arg GetHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, getHost, arg.ID, arg.ProjectID)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IpAddress,
		&i.Hostname,
		&i.Status,
		&i.OsType,
		&i.Notes,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostIPForHost = `-- name: GetHostIPForHost :one
SELECT id, host_id, ip_address, label, is_primary, hostnames, is_cloudflare, created_at, updated_at FROM host_ip_addresses WHERE id = $1 AND host_id = $2
`

type GetHostIPForHostParams struct {
	ID     int32 `json:"id"`
	HostID int32 `json:"host_id"`
}

func (q *Queries) GetHostIPForHost(ctx context.Context, arg GetHostIPForHostParams) (HostIpAddress, error) {
	row := q.db.QueryRow(ctx, getHostIPForHost, arg.ID, arg.HostID)
	var i HostIpAddress
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.IpAddress,
		&i.Label,
		&i.IsPrimary,
		&i.Hostnames,
		&i.IsCloudflare,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPort = `-- name: GetPort :one
SELECT id, host_id, ip_address_id, port_number, protocol, state, http_status, created_at, updated_at FROM ports WHERE id = $1 AND host_id = $2
`

type GetPortParams struct {
	ID     int32 `json:"id"`
	HostID int32 `json:"host_id"`
}

func (q *Queries) GetPort(ctx context.Context, arg GetPortParams) (Port, error) {
	row := q.db.QueryRow(ctx, getPort, arg.ID, arg.HostID)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.IpAddressID,
		&i.PortNumber,
		&i.Protocol,
		&i.State,
		&i.HttpStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceForPort = `-- name: GetServiceForPort :one
SELECT id, port_id, name, version, banner, created_at, updated_at FROM services WHERE id = $1 AND port_id = $2
`

type GetServiceForPortParams struct {
	ID     int32 `json:"id"`
	PortID int32 `json:"port_id"`
}

func (q *Queries) GetServiceForPort(ctx context.Context, arg GetServiceForPortParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceForPort, arg.ID, arg.PortID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.PortID,
		&i.Name,
		&i.Version,
		&i.Banner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEndpoint = `-- name: InsertEndpoint :one
INSERT INTO endpoints (host_id, path, method, description, query_params, request_body, request_content_type, request_headers)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, host_id, path, method, description, query_params, request_body, request_content_type, request_headers, created_at, updated_at
`

type InsertEndpointParams struct {
	HostID             int32          `json:"host_id"`
	Path               string         `json:"path"`
	Method             NullHttpMethod `json:"method"`
	Description        pgtype.Text    `json:"description"`
	QueryParams        []byte         `json:"query_params"`
	RequestBody        pgtype.Text    `json:"request_body"`
	RequestContentType pgtype.Text    `json:"request_content_type"`
	RequestHeaders     []byte         `json:"request_headers"`
}

func (q *Queries) InsertEndpoint(ctx context.Context, arg InsertEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, insertEndpoint,
		arg.HostID,
		arg.Path,
		arg.Method,
		arg.Description,
		arg.QueryParams,
		arg.RequestBody,
		arg.RequestContentType,
		arg.RequestHeaders,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Path,
		&i.Method,
		&i.Description,
		&i.QueryParams,
		&i.RequestBody,
		&i.RequestContentType,
		&i.RequestHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHost = `-- name: InsertHost :one

INSERT INTO hosts (project_id, ip_address, hostname, status, os_type, notes, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, project_id, ip_address, hostname, status, os_type, notes, origin, created_at, updated_at
`

type InsertHostParams struct {
	ProjectID int32       `json:"project_id"`
	IpAddress pgtype.Text `json:"ip_address"`
	Hostname  pgtype.Text `json:"hostname"`
	Status    HostStatus  `json:"status"`
	OsType    HostOsType  `json:"os_type"`
	Notes     pgtype.Text `json:"notes"`
	Origin    string      `json:"origin"`
}

// Контекст inventory: hosts/ip-addresses/ports/services/endpoints (+ OpenAPI import/export).
// hidden-ips живут в контексте projects (те же роуты) — здесь их нет.
// ─────────── hosts ───────────
func (q *Queries) InsertHost(ctx context.Context, arg InsertHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, insertHost,
		arg.ProjectID,
		arg.IpAddress,
		arg.Hostname,
		arg.Status,
		arg.OsType,
		arg.Notes,
		arg.Origin,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IpAddress,
		&i.Hostname,
		&i.Status,
		&i.OsType,
		&i.Notes,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHostIP = `-- name: InsertHostIP :one
INSERT INTO host_ip_addresses (host_id, ip_address, label, is_primary, is_cloudflare, hostnames)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, host_id, ip_address, label, is_primary, hostnames, is_cloudflare, created_at, updated_at
`

type InsertHostIPParams struct {
	HostID       int32       `json:"host_id"`
	IpAddress    string      `json:"ip_address"`
	Label        pgtype.Text `json:"label"`
	IsPrimary    bool        `json:"is_primary"`
	IsCloudflare pgtype.Bool `json:"is_cloudflare"`
	Hostnames    []byte      `json:"hostnames"`
}

func (q *Queries) InsertHostIP(ctx context.Context, arg InsertHostIPParams) (HostIpAddress, error) {
	row := q.db.QueryRow(ctx, insertHostIP,
		arg.HostID,
		arg.IpAddress,
		arg.Label,
		arg.IsPrimary,
		arg.IsCloudflare,
		arg.Hostnames,
	)
	var i HostIpAddress
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.IpAddress,
		&i.Label,
		&i.IsPrimary,
		&i.Hostnames,
		&i.IsCloudflare,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPort = `-- name: InsertPort :one
INSERT INTO ports (host_id, ip_address_id, port_number, protocol, state, http_status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, host_id, ip_address_id, port_number, protocol, state, http_status, created_at, updated_at
`

type InsertPortParams struct {
	HostID      int32        `json:"host_id"`
	IpAddressID int32        `json:"ip_address_id"`
	PortNumber  int32        `json:"port_number"`
	Protocol    PortProtocol `json:"protocol"`
	State       PortState    `json:"state"`
	HttpStatus  pgtype.Int4  `json:"http_status"`
}

func (q *Queries) InsertPort(ctx context.Context, arg InsertPortParams) (Port, error) {
	row := q.db.QueryRow(ctx, insertPort,
		arg.HostID,
		arg.IpAddressID,
		arg.PortNumber,
		arg.Protocol,
		arg.State,
		arg.HttpStatus,
	)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.IpAddressID,
		&i.PortNumber,
		&i.Protocol,
		&i.State,
		&i.HttpStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertService = `-- name: InsertService :one
INSERT INTO services (port_id, name, version, banner) VALUES ($1, $2, $3, $4) RETURNING id, port_id, name, version, banner, created_at, updated_at
`

type InsertServiceParams struct {
	PortID  int32       `json:"port_id"`
	Name    string      `json:"name"`
	Version pgtype.Text `json:"version"`
	Banner  pgtype.Text `json:"banner"`
}

func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, insertService,
		arg.PortID,
		arg.Name,
		arg.Version,
		arg.Banner,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.PortID,
		&i.Name,
		&i.Version,
		&i.Banner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndpointsForHost = `-- name: ListEndpointsForHost :many
SELECT id, host_id, path, method, description, query_params, request_body, request_content_type, request_headers, created_at, updated_at FROM endpoints WHERE host_id = $1 ORDER BY created_at DESC
`

// ─────────── endpoints ───────────
func (q *Queries) ListEndpointsForHost(ctx context.Context, hostID int32) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Path,
			&i.Method,
			&i.Description,
			&i.QueryParams,
			&i.RequestBody,
			&i.RequestContentType,
			&i.RequestHeaders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointsForHostOrdered = `-- name: ListEndpointsForHostOrdered :many
SELECT id, host_id, path, method, description, query_params, request_body, request_content_type, request_headers, created_at, updated_at FROM endpoints WHERE host_id = $1 ORDER BY path, method
`

func (q *Queries) ListEndpointsForHostOrdered(ctx context.Context, hostID int32) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsForHostOrdered, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Path,
			&i.Method,
			&i.Description,
			&i.QueryParams,
			&i.RequestBody,
			&i.RequestContentType,
			&i.RequestHeaders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpointsForHosts = `-- name: ListEndpointsForHosts :many
SELECT id, host_id, path, method, description, query_params, request_body, request_content_type, request_headers, created_at, updated_at FROM endpoints WHERE host_id = ANY($1::int[]) ORDER BY host_id, id
`

func (q *Queries) ListEndpointsForHosts(ctx context.Context, hostIds []int32) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsForHosts, hostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Path,
			&i.Method,
			&i.Description,
			&i.QueryParams,
			&i.RequestBody,
			&i.RequestContentType,
			&i.RequestHeaders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostIPs = `-- name: ListHostIPs :many
SELECT id, host_id, ip_address, label, is_primary, hostnames, is_cloudflare, created_at, updated_at FROM host_ip_addresses WHERE host_id = $1 ORDER BY created_at
`

// ─────────── host_ip_addresses ───────────
func (q *Queries) ListHostIPs(ctx context.Context, hostID int32) ([]HostIpAddress, error) {
	rows, err := q.db.Query(ctx, listHostIPs, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostIpAddress{}
	for rows.Next() {
		var i HostIpAddress
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.IpAddress,
			&i.Label,
			&i.IsPrimary,
			&i.Hostnames,
			&i.IsCloudflare,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostIPsForHosts = `-- name: ListHostIPsForHosts :many
SELECT id, host_id, ip_address, label, is_primary, hostnames, is_cloudflare, created_at, updated_at FROM host_ip_addresses WHERE host_id = ANY($1::int[]) ORDER BY host_id, created_at
`

func (q *Queries) ListHostIPsForHosts(ctx context.Context, hostIds []int32) ([]HostIpAddress, error) {
	rows, err := q.db.Query(ctx, listHostIPsForHosts, hostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostIpAddress{}
	for rows.Next() {
		var i HostIpAddress
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.IpAddress,
			&i.Label,
			&i.IsPrimary,
			&i.Hostnames,
			&i.IsCloudflare,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosts = `-- name: ListHosts :many
SELECT id, project_id, ip_address, hostname, status, os_type, notes, origin, created_at, updated_at FROM hosts
WHERE project_id = $1
  AND ($2::text IS NULL OR origin = $2)
  AND ($3::host_status IS NULL OR status = $3)
ORDER BY created_at DESC OFFSET $4 LIMIT $5
`

type ListHostsParams struct {
	ProjectID int32          `json:"project_id"`
	Origin    pgtype.Text    `json:"origin"`
	Status    NullHostStatus `json:"status"`
	Offset    int32          `json:"offset"`
	Lim       int32          `json:"lim"`
}

func (q *Queries) ListHosts(ctx context.Context, arg ListHostsParams) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts,
		arg.ProjectID,
		arg.Origin,
		arg.Status,
		arg.Offset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IpAddress,
			&i.Hostname,
			&i.Status,
			&i.OsType,
			&i.Notes,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortsForHost = `-- name: ListPortsForHost :many
SELECT id, host_id, ip_address_id, port_number, protocol, state, http_status, created_at, updated_at FROM ports WHERE host_id = $1 ORDER BY port_number
`

// ─────────── ports ───────────
func (q *Queries) ListPortsForHost(ctx context.Context, hostID int32) ([]Port, error) {
	rows, err := q.db.Query(ctx, listPortsForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Port{}
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.IpAddressID,
			&i.PortNumber,
			&i.Protocol,
			&i.State,
			&i.HttpStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortsForIPs = `-- name: ListPortsForIPs :many
SELECT id, host_id, ip_address_id, port_number, protocol, state, http_status, created_at, updated_at FROM ports WHERE ip_address_id = ANY($1::int[]) ORDER BY ip_address_id, port_number
`

func (q *Queries) ListPortsForIPs(ctx context.Context, ipIds []int32) ([]Port, error) {
	rows, err := q.db.Query(ctx, listPortsForIPs, ipIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Port{}
	for rows.Next() {
		var i Port
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.IpAddressID,
			&i.PortNumber,
			&i.Protocol,
			&i.State,
			&i.HttpStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForPort = `-- name: ListServicesForPort :many
SELECT id, port_id, name, version, banner, created_at, updated_at FROM services WHERE port_id = $1 ORDER BY created_at DESC
`

// ─────────── services ───────────
func (q *Queries) ListServicesForPort(ctx context.Context, portID int32) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesForPort, portID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.PortID,
			&i.Name,
			&i.Version,
			&i.Banner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForPorts = `-- name: ListServicesForPorts :many
SELECT id, port_id, name, version, banner, created_at, updated_at FROM services WHERE port_id = ANY($1::int[]) ORDER BY port_id, name
`

func (q *Queries) ListServicesForPorts(ctx context.Context, portIds []int32) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesForPorts, portIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.PortID,
			&i.Name,
			&i.Version,
			&i.Banner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHostPrimaryIP = `-- name: SetHostPrimaryIP :exec
UPDATE hosts SET ip_address = $2, updated_at = now() WHERE id = $1
`

type SetHostPrimaryIPParams struct {
	ID        int32       `json:"id"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) SetHostPrimaryIP(ctx context.Context, arg SetHostPrimaryIPParams) error {
	_, err := q.db.Exec(ctx, setHostPrimaryIP, arg.ID, arg.IpAddress)
	return err
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints SET path = $2, method = $3, description = $4, query_params = $5,
    request_body = $6, request_content_type = $7, request_headers = $8, updated_at = now()
WHERE id = $1 RETURNING id, host_id, path, method, description, query_params, request_body, request_content_type, request_headers, created_at, updated_at
`

type UpdateEndpointParams struct {
	ID                 int32          `json:"id"`
	Path               string         `json:"path"`
	Method             NullHttpMethod `json:"method"`
	Description        pgtype.Text    `json:"description"`
	QueryParams        []byte         `json:"query_params"`
	RequestBody        pgtype.Text    `json:"request_body"`
	RequestContentType pgtype.Text    `json:"request_content_type"`
	RequestHeaders     []byte         `json:"request_headers"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.ID,
		arg.Path,
		arg.Method,
		arg.Description,
		arg.QueryParams,
		arg.RequestBody,
		arg.RequestContentType,
		arg.RequestHeaders,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Path,
		&i.Method,
		&i.Description,
		&i.QueryParams,
		&i.RequestBody,
		&i.RequestContentType,
		&i.RequestHeaders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHost = `-- name: UpdateHost :one
UPDATE hosts SET ip_address = $2, hostname = $3, status = $4, os_type = $5, notes = $6, updated_at = now()
WHERE id = $1 RETURNING id, project_id, ip_address, hostname, status, os_type, notes, origin, created_at, updated_at
`

type UpdateHostParams struct {
	ID        int32       `json:"id"`
	IpAddress pgtype.Text `json:"ip_address"`
	Hostname  pgtype.Text `json:"hostname"`
	Status    HostStatus  `json:"status"`
	OsType    HostOsType  `json:"os_type"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateHost(ctx context.Context, arg UpdateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, updateHost,
		arg.ID,
		arg.IpAddress,
		arg.Hostname,
		arg.Status,
		arg.OsType,
		arg.Notes,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IpAddress,
		&i.Hostname,
		&i.Status,
		&i.OsType,
		&i.Notes,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHostIP = `-- name: UpdateHostIP :exec
UPDATE host_ip_addresses SET label = $2, is_primary = $3, is_cloudflare = $4, hostnames = $5, updated_at = now()
WHERE id = $1
`

type UpdateHostIPParams struct {
	ID           int32       `json:"id"`
	Label        pgtype.Text `json:"label"`
	IsPrimary    bool        `json:"is_primary"`
	IsCloudflare pgtype.Bool `json:"is_cloudflare"`
	Hostnames    []byte      `json:"hostnames"`
}

func (q *Queries) UpdateHostIP(ctx context.Context, arg UpdateHostIPParams) error {
	_, err := q.db.Exec(ctx, updateHostIP,
		arg.ID,
		arg.Label,
		arg.IsPrimary,
		arg.IsCloudflare,
		arg.Hostnames,
	)
	return err
}

const updatePort = `-- name: UpdatePort :one
UPDATE ports SET ip_address_id = $2, port_number = $3, protocol = $4, state = $5, http_status = $6, updated_at = now()
WHERE id = $1 RETURNING id, host_id, ip_address_id, port_number, protocol, state, http_status, created_at, updated_at
`

type UpdatePortParams struct {
	ID          int32        `json:"id"`
	IpAddressID int32        `json:"ip_address_id"`
	PortNumber  int32        `json:"port_number"`
	Protocol    PortProtocol `json:"protocol"`
	State       PortState    `json:"state"`
	HttpStatus  pgtype.Int4  `json:"http_status"`
}

func (q *Queries) UpdatePort(ctx context.Context, arg UpdatePortParams) (Port, error) {
	row := q.db.QueryRow(ctx, updatePort,
		arg.ID,
		arg.IpAddressID,
		arg.PortNumber,
		arg.Protocol,
		arg.State,
		arg.HttpStatus,
	)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.IpAddressID,
		&i.PortNumber,
		&i.Protocol,
		&i.State,
		&i.HttpStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services SET name = $2, version = $3, banner = $4, updated_at = now() WHERE id = $1 RETURNING id, port_id, name, version, banner, created_at, updated_at
`

type UpdateServiceParams struct {
	ID      int32       `json:"id"`
	Name    string      `json:"name"`
	Version pgtype.Text `json:"version"`
	Banner  pgtype.Text `json:"banner"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Banner,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.PortID,
		&i.Name,
		&i.Version,
		&i.Banner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
