// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: js.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteJsFilesForHost = `-- name: DeleteJsFilesForHost :exec
DELETE FROM js_files WHERE project_id = $1 AND host_id = $2
`

type DeleteJsFilesForHostParams struct {
	ProjectID int32 `json:"project_id"`
	HostID    int32 `json:"host_id"`
}

func (q *Queries) DeleteJsFilesForHost(ctx context.Context, arg DeleteJsFilesForHostParams) error {
	_, err := q.db.Exec(ctx, deleteJsFilesForHost, arg.ProjectID, arg.HostID)
	return err
}

const deleteJsSecretsForFile = `-- name: DeleteJsSecretsForFile :exec
DELETE FROM js_secrets WHERE js_file_id = $1
`

func (q *Queries) DeleteJsSecretsForFile(ctx context.Context, jsFileID int32) error {
	_, err := q.db.Exec(ctx, deleteJsSecretsForFile, jsFileID)
	return err
}

const getJsFileByProjectURL = `-- name: GetJsFileByProjectURL :one

SELECT id, project_id, host_id, url, sha256, size_bytes, content_type, status, error, secret_count, endpoint_count, endpoints, fetched_at, created_at, updated_at FROM js_files WHERE project_id = $1 AND url = $2
`

type GetJsFileByProjectURLParams struct {
	ProjectID int32  `json:"project_id"`
	Url       string `json:"url"`
}

// Контекст recon, ферма JS: js_files/js_secrets. Скан «в памяти» (файлы в БД не
// хранятся) — тут только находки, метаданные и апсерт по (project_id, url).
func (q *Queries) GetJsFileByProjectURL(ctx context.Context, arg GetJsFileByProjectURLParams) (JsFile, error) {
	row := q.db.QueryRow(ctx, getJsFileByProjectURL, arg.ProjectID, arg.Url)
	var i JsFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.HostID,
		&i.Url,
		&i.Sha256,
		&i.SizeBytes,
		&i.ContentType,
		&i.Status,
		&i.Error,
		&i.SecretCount,
		&i.EndpointCount,
		&i.Endpoints,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJsSecret = `-- name: InsertJsSecret :exec
INSERT INTO js_secrets (js_file_id, kind, match_preview, snippet, severity)
VALUES ($1, $2, $3, $4, $5)
`

type InsertJsSecretParams struct {
	JsFileID     int32       `json:"js_file_id"`
	Kind         string      `json:"kind"`
	MatchPreview string      `json:"match_preview"`
	Snippet      pgtype.Text `json:"snippet"`
	Severity     string      `json:"severity"`
}

func (q *Queries) InsertJsSecret(ctx context.Context, arg InsertJsSecretParams) error {
	_, err := q.db.Exec(ctx, insertJsSecret,
		arg.JsFileID,
		arg.Kind,
		arg.MatchPreview,
		arg.Snippet,
		arg.Severity,
	)
	return err
}

const listJsFileURLsForHost = `-- name: ListJsFileURLsForHost :many
SELECT url FROM js_files WHERE project_id = $1 AND host_id = $2 ORDER BY url
`

type ListJsFileURLsForHostParams struct {
	ProjectID int32 `json:"project_id"`
	HostID    int32 `json:"host_id"`
}

func (q *Queries) ListJsFileURLsForHost(ctx context.Context, arg ListJsFileURLsForHostParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listJsFileURLsForHost, arg.ProjectID, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJsFileURLsForProject = `-- name: ListJsFileURLsForProject :many
SELECT url FROM js_files WHERE project_id = $1 ORDER BY url
`

func (q *Queries) ListJsFileURLsForProject(ctx context.Context, projectID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listJsFileURLsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJsFilesForProject = `-- name: ListJsFilesForProject :many
SELECT id, project_id, host_id, url, sha256, size_bytes, content_type, status, error, secret_count, endpoint_count, endpoints, fetched_at, created_at, updated_at FROM js_files WHERE project_id = $1 ORDER BY secret_count DESC, url
`

func (q *Queries) ListJsFilesForProject(ctx context.Context, projectID int32) ([]JsFile, error) {
	rows, err := q.db.Query(ctx, listJsFilesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JsFile{}
	for rows.Next() {
		var i JsFile
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.HostID,
			&i.Url,
			&i.Sha256,
			&i.SizeBytes,
			&i.ContentType,
			&i.Status,
			&i.Error,
			&i.SecretCount,
			&i.EndpointCount,
			&i.Endpoints,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJsSecretsForFile = `-- name: ListJsSecretsForFile :many
SELECT id, js_file_id, kind, match_preview, snippet, severity, created_at, updated_at FROM js_secrets WHERE js_file_id = $1 ORDER BY id
`

func (q *Queries) ListJsSecretsForFile(ctx context.Context, jsFileID int32) ([]JsSecret, error) {
	rows, err := q.db.Query(ctx, listJsSecretsForFile, jsFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JsSecret{}
	for rows.Next() {
		var i JsSecret
		if err := rows.Scan(
			&i.ID,
			&i.JsFileID,
			&i.Kind,
			&i.MatchPreview,
			&i.Snippet,
			&i.Severity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJsFile = `-- name: UpsertJsFile :one
INSERT INTO js_files (project_id, host_id, url, sha256, size_bytes, content_type, status, error, secret_count, endpoint_count, endpoints, fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT ON CONSTRAINT uq_js_file_project_url DO UPDATE SET
    host_id = EXCLUDED.host_id,
    sha256 = EXCLUDED.sha256,
    size_bytes = EXCLUDED.size_bytes,
    content_type = EXCLUDED.content_type,
    status = EXCLUDED.status,
    error = EXCLUDED.error,
    secret_count = EXCLUDED.secret_count,
    endpoint_count = EXCLUDED.endpoint_count,
    endpoints = EXCLUDED.endpoints,
    fetched_at = EXCLUDED.fetched_at,
    updated_at = now()
RETURNING id
`

type UpsertJsFileParams struct {
	ProjectID     int32              `json:"project_id"`
	HostID        int32              `json:"host_id"`
	Url           string             `json:"url"`
	Sha256        pgtype.Text        `json:"sha256"`
	SizeBytes     pgtype.Int4        `json:"size_bytes"`
	ContentType   pgtype.Text        `json:"content_type"`
	Status        string             `json:"status"`
	Error         pgtype.Text        `json:"error"`
	SecretCount   int32              `json:"secret_count"`
	EndpointCount int32              `json:"endpoint_count"`
	Endpoints     []byte             `json:"endpoints"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) UpsertJsFile(ctx context.Context, arg UpsertJsFileParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertJsFile,
		arg.ProjectID,
		arg.HostID,
		arg.Url,
		arg.Sha256,
		arg.SizeBytes,
		arg.ContentType,
		arg.Status,
		arg.Error,
		arg.SecretCount,
		arg.EndpointCount,
		arg.Endpoints,
		arg.FetchedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
