// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLeaks = `-- name: ClearLeaks :execrows
DELETE FROM recon_leaks
WHERE project_id = $1
  AND ($2::text IS NULL OR source = $2)
  AND ($3::int IS NULL OR job_id = $3)
`

type ClearLeaksParams struct {
	ProjectID int32       `json:"project_id"`
	Source    pgtype.Text `json:"source"`
	JobID     pgtype.Int4 `json:"job_id"`
}

// Удаляет утечки проекта с необязательными фильтрами source/job_id; число удалённых.
func (q *Queries) ClearLeaks(ctx context.Context, arg ClearLeaksParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearLeaks, arg.ProjectID, arg.Source, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLeak = `-- name: InsertLeak :exec

INSERT INTO recon_leaks (project_id, job_id, source, kind, subject, value, detail, verified)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
`

type InsertLeakParams struct {
	ProjectID int32       `json:"project_id"`
	JobID     pgtype.Int4 `json:"job_id"`
	Source    string      `json:"source"`
	Kind      string      `json:"kind"`
	Subject   pgtype.Text `json:"subject"`
	Value     pgtype.Text `json:"value"`
	Detail    []byte      `json:"detail"`
	Verified  bool        `json:"verified"`
}

// Контекст leaks: единое хранилище утечек (recon_leaks). Пишут разные источники
// (source=github|linkedin|hibp|…); чтение/импорт/очистка — по проекту с
// необязательными фильтрами source/job_id. Импорт создаёт project_notes.
func (q *Queries) InsertLeak(ctx context.Context, arg InsertLeakParams) error {
	_, err := q.db.Exec(ctx, insertLeak,
		arg.ProjectID,
		arg.JobID,
		arg.Source,
		arg.Kind,
		arg.Subject,
		arg.Value,
		arg.Detail,
		arg.Verified,
	)
	return err
}

const insertLeakNote = `-- name: InsertLeakNote :exec
INSERT INTO project_notes (project_id, parent_id, title, content, sort_order, created_by, updated_by)
VALUES (
    $1, NULL, $2, $3,
    COALESCE((SELECT MAX(sort_order) + 1 FROM project_notes WHERE project_id = $1 AND parent_id IS NULL), 0),
    $4, $4
)
`

type InsertLeakNoteParams struct {
	ProjectID int32       `json:"project_id"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	CreatedBy int32       `json:"created_by"`
}

// Лёгкий персист импорта: одна страница-заметка на утечку. title уникален (id
// утечки в заголовке), parent_id=NULL, sort_order — следующий на верхнем уровне.
func (q *Queries) InsertLeakNote(ctx context.Context, arg InsertLeakNoteParams) error {
	_, err := q.db.Exec(ctx, insertLeakNote,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.CreatedBy,
	)
	return err
}

const listLeaks = `-- name: ListLeaks :many
SELECT id, project_id, job_id, source, kind, subject, value, detail, verified, imported, created_at
FROM recon_leaks
WHERE project_id = $1
  AND ($2::text IS NULL OR source = $2)
  AND ($3::int IS NULL OR job_id = $3)
ORDER BY id
`

type ListLeaksParams struct {
	ProjectID int32       `json:"project_id"`
	Source    pgtype.Text `json:"source"`
	JobID     pgtype.Int4 `json:"job_id"`
}

// Все утечки проекта с необязательными фильтрами source/job_id (NULL = не фильтруем).
func (q *Queries) ListLeaks(ctx context.Context, arg ListLeaksParams) ([]ReconLeak, error) {
	rows, err := q.db.Query(ctx, listLeaks, arg.ProjectID, arg.Source, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconLeak{}
	for rows.Next() {
		var i ReconLeak
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Source,
			&i.Kind,
			&i.Subject,
			&i.Value,
			&i.Detail,
			&i.Verified,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaksByIDs = `-- name: ListLeaksByIDs :many
SELECT id, project_id, job_id, source, kind, subject, value, detail, verified, imported, created_at
FROM recon_leaks
WHERE project_id = $1 AND id = ANY($2::int[])
ORDER BY id
`

type ListLeaksByIDsParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Выбранные утечки проекта по id (для импорта). Скоуп проекта обязателен.
func (q *Queries) ListLeaksByIDs(ctx context.Context, arg ListLeaksByIDsParams) ([]ReconLeak, error) {
	rows, err := q.db.Query(ctx, listLeaksByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconLeak{}
	for rows.Next() {
		var i ReconLeak
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Source,
			&i.Kind,
			&i.Subject,
			&i.Value,
			&i.Detail,
			&i.Verified,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLeaksImported = `-- name: MarkLeaksImported :exec
UPDATE recon_leaks SET imported = true
WHERE project_id = $1 AND id = ANY($2::int[])
`

type MarkLeaksImportedParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Помечает выбранные утечки импортированными (идемпотентно).
func (q *Queries) MarkLeaksImported(ctx context.Context, arg MarkLeaksImportedParams) error {
	_, err := q.db.Exec(ctx, markLeaksImported, arg.ProjectID, arg.Ids)
	return err
}
