// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingMailJobs = `-- name: ClaimPendingMailJobs :many
SELECT id, user_id, created_by, recipient_email, subject, template, payload, status, attempts, published_at, sent_at, last_error, created_at, updated_at FROM mail_jobs WHERE status = 'pending' ORDER BY created_at LIMIT $1
`

func (q *Queries) ClaimPendingMailJobs(ctx context.Context, limit int32) ([]MailJob, error) {
	rows, err := q.db.Query(ctx, claimPendingMailJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailJob{}
	for rows.Next() {
		var i MailJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedBy,
			&i.RecipientEmail,
			&i.Subject,
			&i.Template,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.PublishedAt,
			&i.SentAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMailJob = `-- name: InsertMailJob :one

INSERT INTO mail_jobs (user_id, created_by, recipient_email, subject, template, payload, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, user_id, created_by, recipient_email, subject, template, payload, status, attempts, published_at, sent_at, last_error, created_at, updated_at
`

type InsertMailJobParams struct {
	UserID         pgtype.Int4 `json:"user_id"`
	CreatedBy      pgtype.Int4 `json:"created_by"`
	RecipientEmail string      `json:"recipient_email"`
	Subject        string      `json:"subject"`
	Template       string      `json:"template"`
	Payload        []byte      `json:"payload"`
}

// Запросы контекста mail (outbox). Отправка писем — Phase 2 (mail-worker).
func (q *Queries) InsertMailJob(ctx context.Context, arg InsertMailJobParams) (MailJob, error) {
	row := q.db.QueryRow(ctx, insertMailJob,
		arg.UserID,
		arg.CreatedBy,
		arg.RecipientEmail,
		arg.Subject,
		arg.Template,
		arg.Payload,
	)
	var i MailJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedBy,
		&i.RecipientEmail,
		&i.Subject,
		&i.Template,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.PublishedAt,
		&i.SentAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMailJobFailed = `-- name: MarkMailJobFailed :exec
UPDATE mail_jobs SET status = 'failed', attempts = attempts + 1, last_error = $2 WHERE id = $1
`

type MarkMailJobFailedParams struct {
	ID        int32       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkMailJobFailed(ctx context.Context, arg MarkMailJobFailedParams) error {
	_, err := q.db.Exec(ctx, markMailJobFailed, arg.ID, arg.LastError)
	return err
}

const markMailJobSent = `-- name: MarkMailJobSent :exec
UPDATE mail_jobs SET status = 'sent', sent_at = now() WHERE id = $1
`

func (q *Queries) MarkMailJobSent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markMailJobSent, id)
	return err
}
