// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetType string

const (
	AssetTypeHOST     AssetType = "HOST"
	AssetTypePORT     AssetType = "PORT"
	AssetTypeSERVICE  AssetType = "SERVICE"
	AssetTypeENDPOINT AssetType = "ENDPOINT"
)

func (e *AssetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetType(s)
	case string:
		*e = AssetType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetType: %T", src)
	}
	return nil
}

type NullAssetType struct {
	AssetType AssetType `json:"asset_type"`
	Valid     bool      `json:"valid"` // Valid is true if AssetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetType) Scan(value interface{}) error {
	if value == nil {
		ns.AssetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetType), nil
}

type CvssVersion string

const (
	CvssVersionV31 CvssVersion = "V31"
	CvssVersionV40 CvssVersion = "V40"
)

func (e *CvssVersion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CvssVersion(s)
	case string:
		*e = CvssVersion(s)
	default:
		return fmt.Errorf("unsupported scan type for CvssVersion: %T", src)
	}
	return nil
}

type NullCvssVersion struct {
	CvssVersion CvssVersion `json:"cvss_version"`
	Valid       bool        `json:"valid"` // Valid is true if CvssVersion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCvssVersion) Scan(value interface{}) error {
	if value == nil {
		ns.CvssVersion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CvssVersion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCvssVersion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CvssVersion), nil
}

type HostOsType string

const (
	HostOsTypeWINDOWS HostOsType = "WINDOWS"
	HostOsTypeLINUX   HostOsType = "LINUX"
	HostOsTypeMACOS   HostOsType = "MACOS"
	HostOsTypeFREEBSD HostOsType = "FREEBSD"
	HostOsTypeANDROID HostOsType = "ANDROID"
	HostOsTypeIOS     HostOsType = "IOS"
	HostOsTypeOTHER   HostOsType = "OTHER"
	HostOsTypeUNKNOWN HostOsType = "UNKNOWN"
)

func (e *HostOsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HostOsType(s)
	case string:
		*e = HostOsType(s)
	default:
		return fmt.Errorf("unsupported scan type for HostOsType: %T", src)
	}
	return nil
}

type NullHostOsType struct {
	HostOsType HostOsType `json:"host_os_type"`
	Valid      bool       `json:"valid"` // Valid is true if HostOsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHostOsType) Scan(value interface{}) error {
	if value == nil {
		ns.HostOsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HostOsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHostOsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HostOsType), nil
}

type HostStatus string

const (
	HostStatusUP      HostStatus = "UP"
	HostStatusDOWN    HostStatus = "DOWN"
	HostStatusUNKNOWN HostStatus = "UNKNOWN"
)

func (e *HostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HostStatus(s)
	case string:
		*e = HostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HostStatus: %T", src)
	}
	return nil
}

type NullHostStatus struct {
	HostStatus HostStatus `json:"host_status"`
	Valid      bool       `json:"valid"` // Valid is true if HostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HostStatus), nil
}

type HttpMethod string

const (
	HttpMethodGET     HttpMethod = "GET"
	HttpMethodPOST    HttpMethod = "POST"
	HttpMethodPUT     HttpMethod = "PUT"
	HttpMethodPATCH   HttpMethod = "PATCH"
	HttpMethodDELETE  HttpMethod = "DELETE"
	HttpMethodHEAD    HttpMethod = "HEAD"
	HttpMethodOPTIONS HttpMethod = "OPTIONS"
	HttpMethodQUERY   HttpMethod = "QUERY"
)

func (e *HttpMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HttpMethod(s)
	case string:
		*e = HttpMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for HttpMethod: %T", src)
	}
	return nil
}

type NullHttpMethod struct {
	HttpMethod HttpMethod `json:"http_method"`
	Valid      bool       `json:"valid"` // Valid is true if HttpMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHttpMethod) Scan(value interface{}) error {
	if value == nil {
		ns.HttpMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HttpMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHttpMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HttpMethod), nil
}

type NotificationType string

const (
	NotificationTypeMENTION              NotificationType = "MENTION"
	NotificationTypePROJECTMEMBERADDED   NotificationType = "PROJECT_MEMBER_ADDED"
	NotificationTypeVULNSTATUSCHANGED    NotificationType = "VULN_STATUS_CHANGED"
	NotificationTypePROJECTSTATUSCHANGED NotificationType = "PROJECT_STATUS_CHANGED"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type PortProtocol string

const (
	PortProtocolTCP PortProtocol = "TCP"
	PortProtocolUDP PortProtocol = "UDP"
)

func (e *PortProtocol) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PortProtocol(s)
	case string:
		*e = PortProtocol(s)
	default:
		return fmt.Errorf("unsupported scan type for PortProtocol: %T", src)
	}
	return nil
}

type NullPortProtocol struct {
	PortProtocol PortProtocol `json:"port_protocol"`
	Valid        bool         `json:"valid"` // Valid is true if PortProtocol is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPortProtocol) Scan(value interface{}) error {
	if value == nil {
		ns.PortProtocol, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PortProtocol.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPortProtocol) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PortProtocol), nil
}

type PortState string

const (
	PortStateOPEN     PortState = "OPEN"
	PortStateCLOSED   PortState = "CLOSED"
	PortStateFILTERED PortState = "FILTERED"
)

func (e *PortState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PortState(s)
	case string:
		*e = PortState(s)
	default:
		return fmt.Errorf("unsupported scan type for PortState: %T", src)
	}
	return nil
}

type NullPortState struct {
	PortState PortState `json:"port_state"`
	Valid     bool      `json:"valid"` // Valid is true if PortState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPortState) Scan(value interface{}) error {
	if value == nil {
		ns.PortState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PortState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPortState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PortState), nil
}

type ProjectRole string

const (
	ProjectRoleLEAD      ProjectRole = "LEAD"
	ProjectRolePENTESTER ProjectRole = "PENTESTER"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole `json:"project_role"`
	Valid       bool        `json:"valid"` // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type ProjectStatus string

const (
	ProjectStatusACTIVE                ProjectStatus = "ACTIVE"
	ProjectStatusFREEZE                ProjectStatus = "FREEZE"
	ProjectStatusHANDOVERTODEVELOPMENT ProjectStatus = "HANDOVER_TO_DEVELOPMENT"
	ProjectStatusVULNERABILITYRECHECK  ProjectStatus = "VULNERABILITY_RECHECK"
	ProjectStatusCOMPLETED             ProjectStatus = "COMPLETED"
	ProjectStatusARCHIVED              ProjectStatus = "ARCHIVED"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus `json:"project_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

type UserRole string

const (
	UserRoleADMIN     UserRole = "ADMIN"
	UserRolePENTESTER UserRole = "PENTESTER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VulnSeverity string

const (
	VulnSeverityCRITICAL VulnSeverity = "CRITICAL"
	VulnSeverityHIGH     VulnSeverity = "HIGH"
	VulnSeverityMEDIUM   VulnSeverity = "MEDIUM"
	VulnSeverityLOW      VulnSeverity = "LOW"
	VulnSeverityINFO     VulnSeverity = "INFO"
)

func (e *VulnSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VulnSeverity(s)
	case string:
		*e = VulnSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for VulnSeverity: %T", src)
	}
	return nil
}

type NullVulnSeverity struct {
	VulnSeverity VulnSeverity `json:"vuln_severity"`
	Valid        bool         `json:"valid"` // Valid is true if VulnSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVulnSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.VulnSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VulnSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVulnSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VulnSeverity), nil
}

type VulnStatus string

const (
	VulnStatusOPEN         VulnStatus = "OPEN"
	VulnStatusINPROGRESS   VulnStatus = "IN_PROGRESS"
	VulnStatusFIXED        VulnStatus = "FIXED"
	VulnStatusWONTFIX      VulnStatus = "WONT_FIX"
	VulnStatusACCEPTEDRISK VulnStatus = "ACCEPTED_RISK"
)

func (e *VulnStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VulnStatus(s)
	case string:
		*e = VulnStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VulnStatus: %T", src)
	}
	return nil
}

type NullVulnStatus struct {
	VulnStatus VulnStatus `json:"vuln_status"`
	Valid      bool       `json:"valid"` // Valid is true if VulnStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVulnStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VulnStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VulnStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVulnStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VulnStatus), nil
}

type AccountReactivationToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AgentApiToken struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []byte             `json:"scopes"`
	AllProjects bool               `json:"all_projects"`
	CreatedBy   int32              `json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AgentApiTokenProjectGrant struct {
	ID        int32              `json:"id"`
	TokenID   int32              `json:"token_id"`
	ProjectID int32              `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         int32              `json:"id"`
	UserID     pgtype.Int4        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.Int4        `json:"entity_id"`
	Details    []byte             `json:"details"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID              int32              `json:"id"`
	VulnerabilityID int32              `json:"vulnerability_id"`
	UserID          int32              `json:"user_id"`
	Content         string             `json:"content"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CommentMention struct {
	ID        int32 `json:"id"`
	CommentID int32 `json:"comment_id"`
	UserID    int32 `json:"user_id"`
}

type Endpoint struct {
	ID                 int32              `json:"id"`
	HostID             int32              `json:"host_id"`
	Path               string             `json:"path"`
	Method             NullHttpMethod     `json:"method"`
	Description        pgtype.Text        `json:"description"`
	QueryParams        []byte             `json:"query_params"`
	RequestBody        pgtype.Text        `json:"request_body"`
	RequestContentType pgtype.Text        `json:"request_content_type"`
	RequestHeaders     []byte             `json:"request_headers"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type File struct {
	ID              int32              `json:"id"`
	VulnerabilityID int32              `json:"vulnerability_id"`
	OriginalName    string             `json:"original_name"`
	ContentType     string             `json:"content_type"`
	SizeBytes       int64              `json:"size_bytes"`
	MinioBucket     string             `json:"minio_bucket"`
	MinioKey        string             `json:"minio_key"`
	UploadedBy      int32              `json:"uploaded_by"`
	UploadedAt      pgtype.Timestamptz `json:"uploaded_at"`
}

type Host struct {
	ID        int32              `json:"id"`
	ProjectID int32              `json:"project_id"`
	IpAddress pgtype.Text        `json:"ip_address"`
	Hostname  pgtype.Text        `json:"hostname"`
	Status    HostStatus         `json:"status"`
	OsType    HostOsType         `json:"os_type"`
	Notes     pgtype.Text        `json:"notes"`
	Origin    string             `json:"origin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HostFarmJob struct {
	ID              int32              `json:"id"`
	ProjectID       int32              `json:"project_id"`
	CreatedBy       int32              `json:"created_by"`
	Kind            string             `json:"kind"`
	Status          string             `json:"status"`
	TargetsTotal    pgtype.Int4        `json:"targets_total"`
	Result          []byte             `json:"result"`
	Error           pgtype.Text        `json:"error"`
	Raw             pgtype.Text        `json:"raw"`
	Attempts        int32              `json:"attempts"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	LastError       pgtype.Text        `json:"last_error"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	SkippedTargets  []byte             `json:"skipped_targets"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Progress        []byte             `json:"progress"`
	CancelRequested bool               `json:"cancel_requested"`
	CancelSteps     []byte             `json:"cancel_steps"`
}

type HostIpAddress struct {
	ID           int32              `json:"id"`
	HostID       int32              `json:"host_id"`
	IpAddress    string             `json:"ip_address"`
	Label        pgtype.Text        `json:"label"`
	IsPrimary    bool               `json:"is_primary"`
	Hostnames    []byte             `json:"hostnames"`
	IsCloudflare pgtype.Bool        `json:"is_cloudflare"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID             int32              `json:"id"`
	Email          string             `json:"email"`
	FullName       pgtype.Text        `json:"full_name"`
	Role           UserRole           `json:"role"`
	ProjectRole    ProjectRole        `json:"project_role"`
	TokenHash      string             `json:"token_hash"`
	Status         string             `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	InvitedBy      pgtype.Int4        `json:"invited_by"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	AcceptedUserID pgtype.Int4        `json:"accepted_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type JsFile struct {
	ID            int32              `json:"id"`
	ProjectID     int32              `json:"project_id"`
	HostID        int32              `json:"host_id"`
	Url           string             `json:"url"`
	Sha256        pgtype.Text        `json:"sha256"`
	SizeBytes     pgtype.Int4        `json:"size_bytes"`
	ContentType   pgtype.Text        `json:"content_type"`
	Status        string             `json:"status"`
	Error         pgtype.Text        `json:"error"`
	SecretCount   int32              `json:"secret_count"`
	EndpointCount int32              `json:"endpoint_count"`
	Endpoints     []byte             `json:"endpoints"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type JsSecret struct {
	ID           int32              `json:"id"`
	JsFileID     int32              `json:"js_file_id"`
	Kind         string             `json:"kind"`
	MatchPreview string             `json:"match_preview"`
	Snippet      pgtype.Text        `json:"snippet"`
	Severity     string             `json:"severity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MailJob struct {
	ID             int32              `json:"id"`
	UserID         pgtype.Int4        `json:"user_id"`
	CreatedBy      pgtype.Int4        `json:"created_by"`
	RecipientEmail string             `json:"recipient_email"`
	Subject        string             `json:"subject"`
	Template       string             `json:"template"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	LastError      pgtype.Text        `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	Type            NotificationType   `json:"type"`
	CommentID       pgtype.Int4        `json:"comment_id"`
	NoteCommentID   pgtype.Int4        `json:"note_comment_id"`
	ProjectID       pgtype.Int4        `json:"project_id"`
	VulnerabilityID pgtype.Int4        `json:"vulnerability_id"`
	ActorID         pgtype.Int4        `json:"actor_id"`
	Status          pgtype.Text        `json:"status"`
	IsRead          bool               `json:"is_read"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Port struct {
	ID          int32              `json:"id"`
	HostID      int32              `json:"host_id"`
	IpAddressID int32              `json:"ip_address_id"`
	PortNumber  int32              `json:"port_number"`
	Protocol    PortProtocol       `json:"protocol"`
	State       PortState          `json:"state"`
	HttpStatus  pgtype.Int4        `json:"http_status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Folder           string             `json:"folder"`
	Description      pgtype.Text        `json:"description"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	TimelineFrozenAt pgtype.Timestamptz `json:"timeline_frozen_at"`
	Status           ProjectStatus      `json:"status"`
	CreatedBy        int32              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProjectCredential struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	Username          pgtype.Text        `json:"username"`
	PasswordEncrypted string             `json:"password_encrypted"`
	Host              pgtype.Text        `json:"host"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProjectFolder struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Path      string             `json:"path"`
	ParentID  pgtype.Int4        `json:"parent_id"`
	CreatedBy int32              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectHiddenIp struct {
	ID        int32              `json:"id"`
	ProjectID int32              `json:"project_id"`
	IpAddress string             `json:"ip_address"`
	CreatedBy pgtype.Int4        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectMember struct {
	ID        int32              `json:"id"`
	ProjectID int32              `json:"project_id"`
	UserID    int32              `json:"user_id"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
}

type ProjectNote struct {
	ID        int32              `json:"id"`
	ProjectID int32              `json:"project_id"`
	ParentID  pgtype.Int4        `json:"parent_id"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	SortOrder int32              `json:"sort_order"`
	CreatedBy int32              `json:"created_by"`
	UpdatedBy pgtype.Int4        `json:"updated_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProjectNoteComment struct {
	ID        int32              `json:"id"`
	ProjectID int32              `json:"project_id"`
	NoteID    int32              `json:"note_id"`
	UserID    int32              `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ReconFarmConfig struct {
	ProjectID int32              `json:"project_id"`
	Config    []byte             `json:"config"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Service struct {
	ID        int32              `json:"id"`
	PortID    int32              `json:"port_id"`
	Name      string             `json:"name"`
	Version   pgtype.Text        `json:"version"`
	Banner    pgtype.Text        `json:"banner"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                int32              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	FullName          pgtype.Text        `json:"full_name"`
	AvatarMinioBucket pgtype.Text        `json:"avatar_minio_bucket"`
	AvatarMinioKey    pgtype.Text        `json:"avatar_minio_key"`
	AvatarContentType pgtype.Text        `json:"avatar_content_type"`
	AvatarUploadedAt  pgtype.Timestamptz `json:"avatar_uploaded_at"`
	PasswordHash      string             `json:"password_hash"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	TotpSecret        pgtype.Text        `json:"totp_secret"`
	TotpEnabled       bool               `json:"totp_enabled"`
	TotpConfirmedAt   pgtype.Timestamptz `json:"totp_confirmed_at"`
	Role              UserRole           `json:"role"`
	ProjectRole       ProjectRole        `json:"project_role"`
	IsActive          bool               `json:"is_active"`
	IsLocked          bool               `json:"is_locked"`
	Tags              []byte             `json:"tags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Vulnerability struct {
	ID               int32              `json:"id"`
	ProjectID        int32              `json:"project_id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Severity         VulnSeverity       `json:"severity"`
	CvssVersion      NullCvssVersion    `json:"cvss_version"`
	CvssScore        *float64           `json:"cvss_score"`
	CvssVector       pgtype.Text        `json:"cvss_vector"`
	CweID            pgtype.Text        `json:"cwe_id"`
	Status           VulnStatus         `json:"status"`
	WorkflowSteps    []byte             `json:"workflow_steps"`
	StepsToReproduce pgtype.Text        `json:"steps_to_reproduce"`
	Impact           pgtype.Text        `json:"impact"`
	Recommendations  pgtype.Text        `json:"recommendations"`
	CreatedBy        int32              `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type VulnerabilityAsset struct {
	ID              int32     `json:"id"`
	VulnerabilityID int32     `json:"vulnerability_id"`
	AssetType       AssetType `json:"asset_type"`
	AssetID         int32     `json:"asset_id"`
}
