// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT count(*) FROM notifications
WHERE user_id = $1
  AND ($2::bool IS NULL OR is_read = $2)
`

type CountNotificationsParams struct {
	UserID int32       `json:"user_id"`
	IsRead pgtype.Bool `json:"is_read"`
}

func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, arg.UserID, arg.IsRead)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCommentHostID = `-- name: GetCommentHostID :one
SELECT va.asset_id
FROM vulnerability_assets va
JOIN comments c ON c.vulnerability_id = va.vulnerability_id
WHERE va.asset_type = 'HOST' AND c.id = $1
LIMIT 1
`

func (q *Queries) GetCommentHostID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getCommentHostID, id)
	var asset_id int32
	err := row.Scan(&asset_id)
	return asset_id, err
}

const getCommentNotificationContext = `-- name: GetCommentNotificationContext :one

SELECT c.vulnerability_id AS vulnerability_id, v.title AS title, v.project_id AS project_id, u.username AS username
FROM comments c
JOIN vulnerabilities v ON v.id = c.vulnerability_id
JOIN users u ON u.id = c.user_id
WHERE c.id = $1
`

type GetCommentNotificationContextRow struct {
	VulnerabilityID int32  `json:"vulnerability_id"`
	Title           string `json:"title"`
	ProjectID       int32  `json:"project_id"`
	Username        string `json:"username"`
}

// ─────────── резолверы контекста ───────────
func (q *Queries) GetCommentNotificationContext(ctx context.Context, id int32) (GetCommentNotificationContextRow, error) {
	row := q.db.QueryRow(ctx, getCommentNotificationContext, id)
	var i GetCommentNotificationContextRow
	err := row.Scan(
		&i.VulnerabilityID,
		&i.Title,
		&i.ProjectID,
		&i.Username,
	)
	return i, err
}

const getNoteCommentNotificationContext = `-- name: GetNoteCommentNotificationContext :one
SELECT pnc.note_id, pnc.project_id, u.username, pn.title AS note_title
FROM project_note_comments pnc
JOIN project_notes pn ON pn.id = pnc.note_id
JOIN users u ON u.id = pnc.user_id
WHERE pnc.id = $1
`

type GetNoteCommentNotificationContextRow struct {
	NoteID    int32  `json:"note_id"`
	ProjectID int32  `json:"project_id"`
	Username  string `json:"username"`
	NoteTitle string `json:"note_title"`
}

func (q *Queries) GetNoteCommentNotificationContext(ctx context.Context, id int32) (GetNoteCommentNotificationContextRow, error) {
	row := q.db.QueryRow(ctx, getNoteCommentNotificationContext, id)
	var i GetNoteCommentNotificationContextRow
	err := row.Scan(
		&i.NoteID,
		&i.ProjectID,
		&i.Username,
		&i.NoteTitle,
	)
	return i, err
}

const getProjectName = `-- name: GetProjectName :one
SELECT name FROM projects WHERE id = $1
`

func (q *Queries) GetProjectName(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getProjectName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUsernameByID = `-- name: GetUsernameByID :one
SELECT username FROM users WHERE id = $1
`

func (q *Queries) GetUsernameByID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getUsernameByID, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const getVulnTitleAndProject = `-- name: GetVulnTitleAndProject :one
SELECT title, project_id FROM vulnerabilities WHERE id = $1
`

type GetVulnTitleAndProjectRow struct {
	Title     string `json:"title"`
	ProjectID int32  `json:"project_id"`
}

func (q *Queries) GetVulnTitleAndProject(ctx context.Context, id int32) (GetVulnTitleAndProjectRow, error) {
	row := q.db.QueryRow(ctx, getVulnTitleAndProject, id)
	var i GetVulnTitleAndProjectRow
	err := row.Scan(&i.Title, &i.ProjectID)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many

SELECT id, user_id, type, comment_id, note_comment_id, project_id, vulnerability_id, actor_id, status, is_read, created_at FROM notifications
WHERE user_id = $1
  AND ($2::bool IS NULL OR is_read = $2)
ORDER BY created_at DESC
OFFSET $3 LIMIT $4
`

type ListNotificationsParams struct {
	UserID int32       `json:"user_id"`
	IsRead pgtype.Bool `json:"is_read"`
	Offset int32       `json:"offset"`
	Lim    int32       `json:"lim"`
}

// Контекст notifications (читающая сторона; запись — в projects/vulns контекстах).
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.IsRead,
		arg.Offset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.CommentID,
			&i.NoteCommentID,
			&i.ProjectID,
			&i.VulnerabilityID,
			&i.ActorID,
			&i.Status,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = true WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET is_read = true WHERE id = $1 AND user_id = $2 RETURNING id, user_id, type, comment_id, note_comment_id, project_id, vulnerability_id, actor_id, status, is_read, created_at
`

type MarkNotificationReadParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.CommentID,
		&i.NoteCommentID,
		&i.ProjectID,
		&i.VulnerabilityID,
		&i.ActorID,
		&i.Status,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
