// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertHiddenIPs = `-- name: BulkInsertHiddenIPs :execrows
INSERT INTO project_hidden_ips (project_id, ip_address, created_by)
SELECT $1, unnest($2::text[]), $3
ON CONFLICT ON CONSTRAINT uq_project_hidden_ip DO NOTHING
`

type BulkInsertHiddenIPsParams struct {
	ProjectID int32       `json:"project_id"`
	Addrs     []string    `json:"addrs"`
	CreatedBy pgtype.Int4 `json:"created_by"`
}

// Пакетное скрытие адресов: апсерт по (project_id, ip_address) для списка адресов
// (ON CONFLICT DO NOTHING). Возвращает число реально добавленных (уже скрытые не
// считаются). Зеркало InsertHiddenIP для множества адресов.
func (q *Queries) BulkInsertHiddenIPs(ctx context.Context, arg BulkInsertHiddenIPsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkInsertHiddenIPs, arg.ProjectID, arg.Addrs, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countNoteComments = `-- name: CountNoteComments :one
SELECT count(*) FROM project_note_comments WHERE project_id = $1 AND note_id = $2
`

type CountNoteCommentsParams struct {
	ProjectID int32 `json:"project_id"`
	NoteID    int32 `json:"note_id"`
}

// ─────────── note comments ───────────
func (q *Queries) CountNoteComments(ctx context.Context, arg CountNoteCommentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNoteComments, arg.ProjectID, arg.NoteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsAdmin = `-- name: CountProjectsAdmin :one
SELECT count(*) FROM projects
WHERE ($1::project_status IS NULL OR status = $1)
`

func (q *Queries) CountProjectsAdmin(ctx context.Context, status NullProjectStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsAdmin, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsForMember = `-- name: CountProjectsForMember :one
SELECT count(*) FROM projects p JOIN project_members m ON m.project_id = p.id
WHERE m.user_id = $1
  AND ($2::project_status IS NULL OR p.status = $2)
`

type CountProjectsForMemberParams struct {
	UserID int32             `json:"user_id"`
	Status NullProjectStatus `json:"status"`
}

func (q *Queries) CountProjectsForMember(ctx context.Context, arg CountProjectsForMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsForMember, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM project_credentials WHERE id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCredential, id)
	return err
}

const deleteHiddenIP = `-- name: DeleteHiddenIP :exec
DELETE FROM project_hidden_ips WHERE project_id = $1 AND ip_address = $2
`

type DeleteHiddenIPParams struct {
	ProjectID int32  `json:"project_id"`
	IpAddress string `json:"ip_address"`
}

func (q *Queries) DeleteHiddenIP(ctx context.Context, arg DeleteHiddenIPParams) error {
	_, err := q.db.Exec(ctx, deleteHiddenIP, arg.ProjectID, arg.IpAddress)
	return err
}

const deleteHostByID = `-- name: DeleteHostByID :exec
DELETE FROM hosts WHERE id = $1
`

func (q *Queries) DeleteHostByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteHostByID, id)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	ProjectID int32 `json:"project_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.ProjectID, arg.UserID)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM project_notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const deleteNoteComment = `-- name: DeleteNoteComment :exec
DELETE FROM project_note_comments WHERE id = $1
`

func (q *Queries) DeleteNoteComment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNoteComment, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteSubtreeFolders = `-- name: DeleteSubtreeFolders :exec
DELETE FROM project_folders WHERE path = $1 OR path LIKE $1 || '/%'
`

func (q *Queries) DeleteSubtreeFolders(ctx context.Context, path string) error {
	_, err := q.db.Exec(ctx, deleteSubtreeFolders, path)
	return err
}

const deleteSubtreeProjects = `-- name: DeleteSubtreeProjects :exec
DELETE FROM projects WHERE folder = $1 OR folder LIKE $1 || '/%'
`

func (q *Queries) DeleteSubtreeProjects(ctx context.Context, folder string) error {
	_, err := q.db.Exec(ctx, deleteSubtreeProjects, folder)
	return err
}

const findSiblingFolderByName = `-- name: FindSiblingFolderByName :one
SELECT id, name, path, parent_id, created_by, created_at, updated_at FROM project_folders
WHERE parent_id IS NOT DISTINCT FROM $1 AND name = $2 AND id <> $3
LIMIT 1
`

type FindSiblingFolderByNameParams struct {
	ParentID  pgtype.Int4 `json:"parent_id"`
	Name      string      `json:"name"`
	ExcludeID int32       `json:"exclude_id"`
}

func (q *Queries) FindSiblingFolderByName(ctx context.Context, arg FindSiblingFolderByNameParams) (ProjectFolder, error) {
	row := q.db.QueryRow(ctx, findSiblingFolderByName, arg.ParentID, arg.Name, arg.ExcludeID)
	var i ProjectFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ParentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSiblingNoteTitle = `-- name: FindSiblingNoteTitle :one
SELECT id FROM project_notes
WHERE project_id = $1
  AND parent_id IS NOT DISTINCT FROM $2
  AND title = $3
  AND id <> $4
LIMIT 1
`

type FindSiblingNoteTitleParams struct {
	ProjectID int32       `json:"project_id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	Title     string      `json:"title"`
	ExcludeID int32       `json:"exclude_id"`
}

func (q *Queries) FindSiblingNoteTitle(ctx context.Context, arg FindSiblingNoteTitleParams) (int32, error) {
	row := q.db.QueryRow(ctx, findSiblingNoteTitle,
		arg.ProjectID,
		arg.ParentID,
		arg.Title,
		arg.ExcludeID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getCredential = `-- name: GetCredential :one
SELECT c.id, c.project_id, c.username, c.password_encrypted, c.host, c.created_by, c.created_at, c.updated_at, u.username AS created_by_username
FROM project_credentials c LEFT JOIN users u ON u.id = c.created_by
WHERE c.id = $1 AND c.project_id = $2
`

type GetCredentialParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

type GetCredentialRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	Username          pgtype.Text        `json:"username"`
	PasswordEncrypted string             `json:"password_encrypted"`
	Host              pgtype.Text        `json:"host"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (GetCredentialRow, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.ID, arg.ProjectID)
	var i GetCredentialRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Host,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUsername,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, name, path, parent_id, created_by, created_at, updated_at FROM project_folders WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id int32) (ProjectFolder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i ProjectFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ParentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByPath = `-- name: GetFolderByPath :one
SELECT id, name, path, parent_id, created_by, created_at, updated_at FROM project_folders WHERE path = $1
`

func (q *Queries) GetFolderByPath(ctx context.Context, path string) (ProjectFolder, error) {
	row := q.db.QueryRow(ctx, getFolderByPath, path)
	var i ProjectFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ParentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, project_id, user_id, added_at FROM project_members WHERE project_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	ProjectID int32 `json:"project_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.AddedAt,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT n.id, n.project_id, n.parent_id, n.title, n.content, n.sort_order, n.created_by, n.updated_by, n.created_at, n.updated_at, u.username AS created_by_username
FROM project_notes n LEFT JOIN users u ON u.id = n.created_by
WHERE n.id = $1 AND n.project_id = $2
`

type GetNoteParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

type GetNoteRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	ParentID          pgtype.Int4        `json:"parent_id"`
	Title             string             `json:"title"`
	Content           pgtype.Text        `json:"content"`
	SortOrder         int32              `json:"sort_order"`
	CreatedBy         int32              `json:"created_by"`
	UpdatedBy         pgtype.Int4        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (GetNoteRow, error) {
	row := q.db.QueryRow(ctx, getNote, arg.ID, arg.ProjectID)
	var i GetNoteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Title,
		&i.Content,
		&i.SortOrder,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUsername,
	)
	return i, err
}

const getNoteComment = `-- name: GetNoteComment :one
SELECT id, project_id, note_id, user_id, content, created_at, updated_at FROM project_note_comments WHERE id = $1 AND note_id = $2 AND project_id = $3
`

type GetNoteCommentParams struct {
	ID        int32 `json:"id"`
	NoteID    int32 `json:"note_id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) GetNoteComment(ctx context.Context, arg GetNoteCommentParams) (ProjectNoteComment, error) {
	row := q.db.QueryRow(ctx, getNoteComment, arg.ID, arg.NoteID, arg.ProjectID)
	var i ProjectNoteComment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NoteID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one

SELECT id, name, folder, description, start_date, end_date, timeline_frozen_at, status, created_by, created_at, updated_at FROM projects WHERE id = $1
`

// Запросы контекста projects: проекты, папки, участники, заметки(+комментарии),
// креды, hidden-ips, статистика, активность, уведомления, упоминания.
// ─────────── projects ───────────
func (q *Queries) GetProjectByID(ctx context.Context, id int32) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Folder,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.TimelineFrozenAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hiddenIPExists = `-- name: HiddenIPExists :one
SELECT EXISTS (SELECT 1 FROM project_hidden_ips WHERE project_id = $1 AND ip_address = $2)
`

type HiddenIPExistsParams struct {
	ProjectID int32  `json:"project_id"`
	IpAddress string `json:"ip_address"`
}

func (q *Queries) HiddenIPExists(ctx context.Context, arg HiddenIPExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hiddenIPExists, arg.ProjectID, arg.IpAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO project_credentials (project_id, username, password_encrypted, host, created_by)
VALUES ($1, $2, $3, $4, $5) RETURNING id, project_id, username, password_encrypted, host, created_by, created_at, updated_at
`

type InsertCredentialParams struct {
	ProjectID         int32       `json:"project_id"`
	Username          pgtype.Text `json:"username"`
	PasswordEncrypted string      `json:"password_encrypted"`
	Host              pgtype.Text `json:"host"`
	CreatedBy         int32       `json:"created_by"`
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (ProjectCredential, error) {
	row := q.db.QueryRow(ctx, insertCredential,
		arg.ProjectID,
		arg.Username,
		arg.PasswordEncrypted,
		arg.Host,
		arg.CreatedBy,
	)
	var i ProjectCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Host,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFolder = `-- name: InsertFolder :one
INSERT INTO project_folders (name, path, parent_id, created_by) VALUES ($1, $2, $3, $4) RETURNING id, name, path, parent_id, created_by, created_at, updated_at
`

type InsertFolderParams struct {
	Name      string      `json:"name"`
	Path      string      `json:"path"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	CreatedBy int32       `json:"created_by"`
}

func (q *Queries) InsertFolder(ctx context.Context, arg InsertFolderParams) (ProjectFolder, error) {
	row := q.db.QueryRow(ctx, insertFolder,
		arg.Name,
		arg.Path,
		arg.ParentID,
		arg.CreatedBy,
	)
	var i ProjectFolder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.ParentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHiddenIP = `-- name: InsertHiddenIP :exec
INSERT INTO project_hidden_ips (project_id, ip_address, created_by) VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT uq_project_hidden_ip DO NOTHING
`

type InsertHiddenIPParams struct {
	ProjectID int32       `json:"project_id"`
	IpAddress string      `json:"ip_address"`
	CreatedBy pgtype.Int4 `json:"created_by"`
}

func (q *Queries) InsertHiddenIP(ctx context.Context, arg InsertHiddenIPParams) error {
	_, err := q.db.Exec(ctx, insertHiddenIP, arg.ProjectID, arg.IpAddress, arg.CreatedBy)
	return err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO project_members (project_id, user_id) VALUES ($1, $2) RETURNING id, project_id, user_id, added_at
`

type InsertMemberParams struct {
	ProjectID int32 `json:"project_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, insertMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.AddedAt,
	)
	return i, err
}

const insertNote = `-- name: InsertNote :one
INSERT INTO project_notes (project_id, parent_id, title, content, sort_order, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $6) RETURNING id, project_id, parent_id, title, content, sort_order, created_by, updated_by, created_at, updated_at
`

type InsertNoteParams struct {
	ProjectID int32       `json:"project_id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	SortOrder int32       `json:"sort_order"`
	CreatedBy int32       `json:"created_by"`
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (ProjectNote, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.ProjectID,
		arg.ParentID,
		arg.Title,
		arg.Content,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i ProjectNote
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Title,
		&i.Content,
		&i.SortOrder,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNoteComment = `-- name: InsertNoteComment :one
INSERT INTO project_note_comments (project_id, note_id, user_id, content) VALUES ($1, $2, $3, $4) RETURNING id, project_id, note_id, user_id, content, created_at, updated_at
`

type InsertNoteCommentParams struct {
	ProjectID int32  `json:"project_id"`
	NoteID    int32  `json:"note_id"`
	UserID    int32  `json:"user_id"`
	Content   string `json:"content"`
}

func (q *Queries) InsertNoteComment(ctx context.Context, arg InsertNoteCommentParams) (ProjectNoteComment, error) {
	row := q.db.QueryRow(ctx, insertNoteComment,
		arg.ProjectID,
		arg.NoteID,
		arg.UserID,
		arg.Content,
	)
	var i ProjectNoteComment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NoteID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (user_id, type, comment_id, note_comment_id, project_id, vulnerability_id, actor_id, status, is_read)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, false)
`

type InsertNotificationParams struct {
	UserID          int32            `json:"user_id"`
	Type            NotificationType `json:"type"`
	CommentID       pgtype.Int4      `json:"comment_id"`
	NoteCommentID   pgtype.Int4      `json:"note_comment_id"`
	ProjectID       pgtype.Int4      `json:"project_id"`
	VulnerabilityID pgtype.Int4      `json:"vulnerability_id"`
	ActorID         pgtype.Int4      `json:"actor_id"`
	Status          pgtype.Text      `json:"status"`
}

// ─────────── notifications + mentions ───────────
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.CommentID,
		arg.NoteCommentID,
		arg.ProjectID,
		arg.VulnerabilityID,
		arg.ActorID,
		arg.Status,
	)
	return err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (name, folder, description, start_date, end_date, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, folder, description, start_date, end_date, timeline_frozen_at, status, created_by, created_at, updated_at
`

type InsertProjectParams struct {
	Name        string        `json:"name"`
	Folder      string        `json:"folder"`
	Description pgtype.Text   `json:"description"`
	StartDate   pgtype.Date   `json:"start_date"`
	EndDate     pgtype.Date   `json:"end_date"`
	Status      ProjectStatus `json:"status"`
	CreatedBy   int32         `json:"created_by"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.Name,
		arg.Folder,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Folder,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.TimelineFrozenAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS (SELECT 1 FROM project_members WHERE project_id = $1 AND user_id = $2)
`

type IsProjectMemberParams struct {
	ProjectID int32 `json:"project_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectMember, arg.ProjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAllProjectIDs = `-- name: ListAllProjectIDs :many
SELECT id FROM projects ORDER BY id
`

func (q *Queries) ListAllProjectIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, listAllProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT c.id, c.project_id, c.username, c.password_encrypted, c.host, c.created_by, c.created_at, c.updated_at, u.username AS created_by_username
FROM project_credentials c LEFT JOIN users u ON u.id = c.created_by
WHERE c.project_id = $1 ORDER BY c.created_at ASC, c.id ASC
`

type ListCredentialsRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	Username          pgtype.Text        `json:"username"`
	PasswordEncrypted string             `json:"password_encrypted"`
	Host              pgtype.Text        `json:"host"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

// ─────────── credentials ───────────
func (q *Queries) ListCredentials(ctx context.Context, projectID int32) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsRow{}
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Username,
			&i.PasswordEncrypted,
			&i.Host,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, name, path, parent_id, created_by, created_at, updated_at FROM project_folders ORDER BY path ASC
`

// ─────────── folders ───────────
func (q *Queries) ListFolders(ctx context.Context) ([]ProjectFolder, error) {
	rows, err := q.db.Query(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectFolder{}
	for rows.Next() {
		var i ProjectFolder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.ParentID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiddenIPs = `-- name: ListHiddenIPs :many
SELECT ip_address FROM project_hidden_ips WHERE project_id = $1 ORDER BY ip_address
`

// ─────────── hidden ips ───────────
func (q *Queries) ListHiddenIPs(ctx context.Context, projectID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listHiddenIPs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ip_address string
		if err := rows.Scan(&ip_address); err != nil {
			return nil, err
		}
		items = append(items, ip_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberUserIDs = `-- name: ListMemberUserIDs :many
SELECT user_id FROM project_members WHERE project_id = $1
`

func (q *Queries) ListMemberUserIDs(ctx context.Context, projectID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listMemberUserIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, u.username, u.email, u.role, u.project_role, m.added_at
FROM project_members m JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1 ORDER BY m.added_at DESC
`

type ListMembersRow struct {
	UserID      int32              `json:"user_id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Role        UserRole           `json:"role"`
	ProjectRole ProjectRole        `json:"project_role"`
	AddedAt     pgtype.Timestamptz `json:"added_at"`
}

// ─────────── members ───────────
func (q *Queries) ListMembers(ctx context.Context, projectID int32) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.ProjectRole,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteComments = `-- name: ListNoteComments :many
SELECT c.id, c.project_id, c.note_id, c.user_id, c.content, c.created_at, c.updated_at, u.username,
       u.avatar_minio_key, u.avatar_uploaded_at, u.id AS uid
FROM project_note_comments c JOIN users u ON u.id = c.user_id
WHERE c.project_id = $1 AND c.note_id = $2
ORDER BY c.created_at ASC OFFSET $3 LIMIT $4
`

type ListNoteCommentsParams struct {
	ProjectID int32 `json:"project_id"`
	NoteID    int32 `json:"note_id"`
	Offset    int32 `json:"offset"`
	Limit     int32 `json:"limit"`
}

type ListNoteCommentsRow struct {
	ID               int32              `json:"id"`
	ProjectID        int32              `json:"project_id"`
	NoteID           int32              `json:"note_id"`
	UserID           int32              `json:"user_id"`
	Content          string             `json:"content"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Username         string             `json:"username"`
	AvatarMinioKey   pgtype.Text        `json:"avatar_minio_key"`
	AvatarUploadedAt pgtype.Timestamptz `json:"avatar_uploaded_at"`
	Uid              int32              `json:"uid"`
}

func (q *Queries) ListNoteComments(ctx context.Context, arg ListNoteCommentsParams) ([]ListNoteCommentsRow, error) {
	rows, err := q.db.Query(ctx, listNoteComments,
		arg.ProjectID,
		arg.NoteID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNoteCommentsRow{}
	for rows.Next() {
		var i ListNoteCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NoteID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarMinioKey,
			&i.AvatarUploadedAt,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT n.id, n.project_id, n.parent_id, n.title, n.content, n.sort_order, n.created_by, n.updated_by, n.created_at, n.updated_at, u.username AS created_by_username
FROM project_notes n LEFT JOIN users u ON u.id = n.created_by
WHERE n.project_id = $1
ORDER BY n.parent_id ASC NULLS FIRST, n.sort_order ASC, n.title ASC
`

type ListNotesRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	ParentID          pgtype.Int4        `json:"parent_id"`
	Title             string             `json:"title"`
	Content           pgtype.Text        `json:"content"`
	SortOrder         int32              `json:"sort_order"`
	CreatedBy         int32              `json:"created_by"`
	UpdatedBy         pgtype.Int4        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

// ─────────── notes ───────────
func (q *Queries) ListNotes(ctx context.Context, projectID int32) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesRow{}
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.SortOrder,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesActivity = `-- name: ListNotesActivity :many
SELECT a.id, a.action, a.entity_id, a.user_id, u.username, a.details, a.created_at
FROM audit_logs a LEFT JOIN users u ON u.id = a.user_id
WHERE a.entity_type = 'project_note' AND a.action IN ('CREATE','UPDATE','DELETE')
  AND (a.details->>'project_id' = $1::text
       OR a.entity_id IN (SELECT id FROM project_notes WHERE project_id = $1))
ORDER BY a.created_at DESC LIMIT $2
`

type ListNotesActivityParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

type ListNotesActivityRow struct {
	ID        int32              `json:"id"`
	Action    string             `json:"action"`
	EntityID  pgtype.Int4        `json:"entity_id"`
	UserID    pgtype.Int4        `json:"user_id"`
	Username  pgtype.Text        `json:"username"`
	Details   []byte             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ─────────── activity ───────────
func (q *Queries) ListNotesActivity(ctx context.Context, arg ListNotesActivityParams) ([]ListNotesActivityRow, error) {
	rows, err := q.db.Query(ctx, listNotesActivity, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesActivityRow{}
	for rows.Next() {
		var i ListNotesActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityID,
			&i.UserID,
			&i.Username,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectActivity = `-- name: ListProjectActivity :many
SELECT a.id, a.action, a.entity_type, a.entity_id, a.user_id, u.username, a.details, a.created_at
FROM audit_logs a LEFT JOIN users u ON u.id = a.user_id
WHERE a.entity_type IS NOT NULL
  AND (
    (a.entity_type = 'project' AND a.entity_id = $1)
    OR (a.entity_type = 'vulnerability' AND a.entity_id IN (SELECT id FROM vulnerabilities WHERE project_id = $1))
    OR (a.entity_type = 'host' AND a.entity_id IN (SELECT id FROM hosts WHERE project_id = $1))
    OR (a.entity_type = 'port' AND a.entity_id IN (SELECT id FROM ports WHERE host_id IN (SELECT id FROM hosts WHERE project_id = $1)))
    OR (a.entity_type = 'service' AND a.entity_id IN (SELECT id FROM services WHERE port_id IN (SELECT id FROM ports WHERE host_id IN (SELECT id FROM hosts WHERE project_id = $1))))
    OR (a.entity_type = 'endpoint' AND a.entity_id IN (SELECT id FROM endpoints WHERE host_id IN (SELECT id FROM hosts WHERE project_id = $1)))
    OR (a.entity_type = 'project_note' AND a.entity_id IN (SELECT id FROM project_notes WHERE project_id = $1))
    OR (a.entity_type = 'project_member' AND a.entity_id IN (SELECT id FROM project_members WHERE project_id = $1))
    OR (a.details->>'project_id' = $1::text)
  )
ORDER BY a.created_at DESC LIMIT $2
`

type ListProjectActivityParams struct {
	ProjectID pgtype.Int4 `json:"project_id"`
	Lim       int32       `json:"lim"`
}

type ListProjectActivityRow struct {
	ID         int32              `json:"id"`
	Action     string             `json:"action"`
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.Int4        `json:"entity_id"`
	UserID     pgtype.Int4        `json:"user_id"`
	Username   pgtype.Text        `json:"username"`
	Details    []byte             `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListProjectActivity(ctx context.Context, arg ListProjectActivityParams) ([]ListProjectActivityRow, error) {
	rows, err := q.db.Query(ctx, listProjectActivity, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectActivityRow{}
	for rows.Next() {
		var i ListProjectActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.UserID,
			&i.Username,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsAdmin = `-- name: ListProjectsAdmin :many
SELECT id, name, folder, description, start_date, end_date, timeline_frozen_at, status, created_by, created_at, updated_at FROM projects
WHERE ($1::project_status IS NULL OR status = $1)
ORDER BY created_at DESC OFFSET $2 LIMIT $3
`

type ListProjectsAdminParams struct {
	Status NullProjectStatus `json:"status"`
	Offset int32             `json:"offset"`
	Lim    int32             `json:"lim"`
}

func (q *Queries) ListProjectsAdmin(ctx context.Context, arg ListProjectsAdminParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsAdmin, arg.Status, arg.Offset, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Folder,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.TimelineFrozenAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByIDs = `-- name: ListProjectsByIDs :many
SELECT id, name, folder, description, start_date, end_date, timeline_frozen_at, status, created_by, created_at, updated_at FROM projects WHERE id = ANY($1::int[]) ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByIDs(ctx context.Context, ids []int32) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Folder,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.TimelineFrozenAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForMember = `-- name: ListProjectsForMember :many
SELECT p.id, p.name, p.folder, p.description, p.start_date, p.end_date, p.timeline_frozen_at, p.status, p.created_by, p.created_at, p.updated_at FROM projects p JOIN project_members m ON m.project_id = p.id
WHERE m.user_id = $1
  AND ($2::project_status IS NULL OR p.status = $2)
ORDER BY p.created_at DESC OFFSET $3 LIMIT $4
`

type ListProjectsForMemberParams struct {
	UserID int32             `json:"user_id"`
	Status NullProjectStatus `json:"status"`
	Offset int32             `json:"offset"`
	Lim    int32             `json:"lim"`
}

func (q *Queries) ListProjectsForMember(ctx context.Context, arg ListProjectsForMemberParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForMember,
		arg.UserID,
		arg.Status,
		arg.Offset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Folder,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.TimelineFrozenAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingNotes = `-- name: ListSiblingNotes :many
SELECT n.id, n.project_id, n.parent_id, n.title, n.content, n.sort_order, n.created_by, n.updated_by, n.created_at, n.updated_at, u.username AS created_by_username
FROM project_notes n LEFT JOIN users u ON u.id = n.created_by
WHERE n.project_id = $1 AND n.parent_id IS NOT DISTINCT FROM $2
ORDER BY n.sort_order ASC, n.title ASC
`

type ListSiblingNotesParams struct {
	ProjectID int32       `json:"project_id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
}

type ListSiblingNotesRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	ParentID          pgtype.Int4        `json:"parent_id"`
	Title             string             `json:"title"`
	Content           pgtype.Text        `json:"content"`
	SortOrder         int32              `json:"sort_order"`
	CreatedBy         int32              `json:"created_by"`
	UpdatedBy         pgtype.Int4        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

func (q *Queries) ListSiblingNotes(ctx context.Context, arg ListSiblingNotesParams) ([]ListSiblingNotesRow, error) {
	rows, err := q.db.Query(ctx, listSiblingNotes, arg.ProjectID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiblingNotesRow{}
	for rows.Next() {
		var i ListSiblingNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.Title,
			&i.Content,
			&i.SortOrder,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandaloneIPHostIDs = `-- name: ListStandaloneIPHostIDs :many
SELECT DISTINCT h.id FROM hosts h JOIN host_ip_addresses hia ON hia.host_id = h.id
WHERE h.project_id = $1 AND h.origin = 'ip' AND hia.ip_address = $2
`

type ListStandaloneIPHostIDsParams struct {
	ProjectID int32  `json:"project_id"`
	IpAddress string `json:"ip_address"`
}

func (q *Queries) ListStandaloneIPHostIDs(ctx context.Context, arg ListStandaloneIPHostIDsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listStandaloneIPHostIDs, arg.ProjectID, arg.IpAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtreeFolders = `-- name: ListSubtreeFolders :many
SELECT id, name, path, parent_id, created_by, created_at, updated_at FROM project_folders WHERE path = $1 OR path LIKE $1 || '/%'
`

func (q *Queries) ListSubtreeFolders(ctx context.Context, path string) ([]ProjectFolder, error) {
	rows, err := q.db.Query(ctx, listSubtreeFolders, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectFolder{}
	for rows.Next() {
		var i ProjectFolder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.ParentID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtreeProjects = `-- name: ListSubtreeProjects :many
SELECT id, name, folder, description, start_date, end_date, timeline_frozen_at, status, created_by, created_at, updated_at FROM projects WHERE folder = $1 OR folder LIKE $1 || '/%'
`

func (q *Queries) ListSubtreeProjects(ctx context.Context, folder string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listSubtreeProjects, folder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Folder,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.TimelineFrozenAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulnsForActivity = `-- name: ListVulnsForActivity :many
SELECT id, title, severity FROM vulnerabilities WHERE id = ANY($1::int[])
`

type ListVulnsForActivityRow struct {
	ID       int32        `json:"id"`
	Title    string       `json:"title"`
	Severity VulnSeverity `json:"severity"`
}

func (q *Queries) ListVulnsForActivity(ctx context.Context, ids []int32) ([]ListVulnsForActivityRow, error) {
	rows, err := q.db.Query(ctx, listVulnsForActivity, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVulnsForActivityRow{}
	for rows.Next() {
		var i ListVulnsForActivityRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Severity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSiblingSortOrder = `-- name: MaxSiblingSortOrder :one
SELECT COALESCE(MAX(sort_order), -1)::int FROM project_notes
WHERE project_id = $1 AND parent_id IS NOT DISTINCT FROM $2
`

type MaxSiblingSortOrderParams struct {
	ProjectID int32       `json:"project_id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
}

func (q *Queries) MaxSiblingSortOrder(ctx context.Context, arg MaxSiblingSortOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxSiblingSortOrder, arg.ProjectID, arg.ParentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const moveNote = `-- name: MoveNote :exec
UPDATE project_notes SET parent_id = $2, sort_order = $3, updated_by = $4, updated_at = now() WHERE id = $1
`

type MoveNoteParams struct {
	ID        int32       `json:"id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	SortOrder int32       `json:"sort_order"`
	UpdatedBy pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) MoveNote(ctx context.Context, arg MoveNoteParams) error {
	_, err := q.db.Exec(ctx, moveNote,
		arg.ID,
		arg.ParentID,
		arg.SortOrder,
		arg.UpdatedBy,
	)
	return err
}

const projectStatsAdmin = `-- name: ProjectStatsAdmin :many
SELECT p.id AS project_id, p.status,
       COALESCE(h.cnt, 0)::bigint AS hosts_count,
       COALESCE(v.total, 0)::bigint AS total_findings,
       COALESCE(v.open, 0)::bigint AS open_findings
FROM projects p
LEFT JOIN (SELECT project_id, count(*) AS cnt FROM hosts GROUP BY project_id) h ON h.project_id = p.id
LEFT JOIN (SELECT project_id, count(*) AS total,
                  count(*) FILTER (WHERE status IN ('OPEN','IN_PROGRESS')) AS open
           FROM vulnerabilities GROUP BY project_id) v ON v.project_id = p.id
ORDER BY p.created_at DESC
`

type ProjectStatsAdminRow struct {
	ProjectID     int32         `json:"project_id"`
	Status        ProjectStatus `json:"status"`
	HostsCount    int64         `json:"hosts_count"`
	TotalFindings int64         `json:"total_findings"`
	OpenFindings  int64         `json:"open_findings"`
}

// ─────────── project stats ───────────
func (q *Queries) ProjectStatsAdmin(ctx context.Context) ([]ProjectStatsAdminRow, error) {
	rows, err := q.db.Query(ctx, projectStatsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectStatsAdminRow{}
	for rows.Next() {
		var i ProjectStatsAdminRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Status,
			&i.HostsCount,
			&i.TotalFindings,
			&i.OpenFindings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectStatsForMember = `-- name: ProjectStatsForMember :many
SELECT p.id AS project_id, p.status,
       COALESCE(h.cnt, 0)::bigint AS hosts_count,
       COALESCE(v.total, 0)::bigint AS total_findings,
       COALESCE(v.open, 0)::bigint AS open_findings
FROM projects p
JOIN project_members m ON m.project_id = p.id AND m.user_id = $1
LEFT JOIN (SELECT project_id, count(*) AS cnt FROM hosts GROUP BY project_id) h ON h.project_id = p.id
LEFT JOIN (SELECT project_id, count(*) AS total,
                  count(*) FILTER (WHERE status IN ('OPEN','IN_PROGRESS')) AS open
           FROM vulnerabilities GROUP BY project_id) v ON v.project_id = p.id
ORDER BY p.created_at DESC
`

type ProjectStatsForMemberRow struct {
	ProjectID     int32         `json:"project_id"`
	Status        ProjectStatus `json:"status"`
	HostsCount    int64         `json:"hosts_count"`
	TotalFindings int64         `json:"total_findings"`
	OpenFindings  int64         `json:"open_findings"`
}

func (q *Queries) ProjectStatsForMember(ctx context.Context, userID int32) ([]ProjectStatsForMemberRow, error) {
	rows, err := q.db.Query(ctx, projectStatsForMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectStatsForMemberRow{}
	for rows.Next() {
		var i ProjectStatsForMemberRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Status,
			&i.HostsCount,
			&i.TotalFindings,
			&i.OpenFindings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMentionUsers = `-- name: ResolveMentionUsers :many
SELECT u.id, u.username FROM users u
LEFT JOIN project_members pm ON pm.user_id = u.id AND pm.project_id = $1
WHERE u.username = ANY($2::text[]) AND (pm.user_id IS NOT NULL OR u.role = 'ADMIN')
`

type ResolveMentionUsersParams struct {
	ProjectID int32    `json:"project_id"`
	Usernames []string `json:"usernames"`
}

type ResolveMentionUsersRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) ResolveMentionUsers(ctx context.Context, arg ResolveMentionUsersParams) ([]ResolveMentionUsersRow, error) {
	rows, err := q.db.Query(ctx, resolveMentionUsers, arg.ProjectID, arg.Usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveMentionUsersRow{}
	for rows.Next() {
		var i ResolveMentionUsersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNoteSortOrder = `-- name: SetNoteSortOrder :exec
UPDATE project_notes SET sort_order = $2, updated_by = $3, updated_at = now() WHERE id = $1
`

type SetNoteSortOrderParams struct {
	ID        int32       `json:"id"`
	SortOrder int32       `json:"sort_order"`
	UpdatedBy pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) SetNoteSortOrder(ctx context.Context, arg SetNoteSortOrderParams) error {
	_, err := q.db.Exec(ctx, setNoteSortOrder, arg.ID, arg.SortOrder, arg.UpdatedBy)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE project_credentials SET username = $2, password_encrypted = $3, host = $4, updated_at = now() WHERE id = $1
`

type UpdateCredentialParams struct {
	ID                int32       `json:"id"`
	Username          pgtype.Text `json:"username"`
	PasswordEncrypted string      `json:"password_encrypted"`
	Host              pgtype.Text `json:"host"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential,
		arg.ID,
		arg.Username,
		arg.PasswordEncrypted,
		arg.Host,
	)
	return err
}

const updateFolderPath = `-- name: UpdateFolderPath :exec
UPDATE project_folders SET path = $2, updated_at = now() WHERE id = $1
`

type UpdateFolderPathParams struct {
	ID   int32  `json:"id"`
	Path string `json:"path"`
}

func (q *Queries) UpdateFolderPath(ctx context.Context, arg UpdateFolderPathParams) error {
	_, err := q.db.Exec(ctx, updateFolderPath, arg.ID, arg.Path)
	return err
}

const updateFolderPathParent = `-- name: UpdateFolderPathParent :exec
UPDATE project_folders SET path = $2, parent_id = $3, updated_at = now() WHERE id = $1
`

type UpdateFolderPathParentParams struct {
	ID       int32       `json:"id"`
	Path     string      `json:"path"`
	ParentID pgtype.Int4 `json:"parent_id"`
}

func (q *Queries) UpdateFolderPathParent(ctx context.Context, arg UpdateFolderPathParentParams) error {
	_, err := q.db.Exec(ctx, updateFolderPathParent, arg.ID, arg.Path, arg.ParentID)
	return err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE project_notes SET title = $2, content = $3, updated_by = $4, updated_at = now() WHERE id = $1
`

type UpdateNoteParams struct {
	ID        int32       `json:"id"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	UpdatedBy pgtype.Int4 `json:"updated_by"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.Exec(ctx, updateNote,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.UpdatedBy,
	)
	return err
}

const updateNoteComment = `-- name: UpdateNoteComment :exec
UPDATE project_note_comments SET content = $2, updated_at = now() WHERE id = $1
`

type UpdateNoteCommentParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateNoteComment(ctx context.Context, arg UpdateNoteCommentParams) error {
	_, err := q.db.Exec(ctx, updateNoteComment, arg.ID, arg.Content)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, folder = $3, description = $4, start_date = $5, end_date = $6,
    status = $7, timeline_frozen_at = $8, updated_at = now()
WHERE id = $1 RETURNING id, name, folder, description, start_date, end_date, timeline_frozen_at, status, created_by, created_at, updated_at
`

type UpdateProjectParams struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Folder           string             `json:"folder"`
	Description      pgtype.Text        `json:"description"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	Status           ProjectStatus      `json:"status"`
	TimelineFrozenAt pgtype.Timestamptz `json:"timeline_frozen_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Folder,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.TimelineFrozenAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Folder,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.TimelineFrozenAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectFolderPath = `-- name: UpdateProjectFolderPath :exec
UPDATE projects SET folder = $2, updated_at = now() WHERE id = $1
`

type UpdateProjectFolderPathParams struct {
	ID     int32  `json:"id"`
	Folder string `json:"folder"`
}

func (q *Queries) UpdateProjectFolderPath(ctx context.Context, arg UpdateProjectFolderPathParams) error {
	_, err := q.db.Exec(ctx, updateProjectFolderPath, arg.ID, arg.Folder)
	return err
}
