// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// ─────────────────────────── invitations ───────────────────────────
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	// ─────────────────────────── password_reset_tokens ───────────────────────────
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	// ─────────────────────────── account_reactivation_tokens ───────────────────────────
	CreateReactivationToken(ctx context.Context, arg CreateReactivationTokenParams) (AccountReactivationToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DisableUserTotp(ctx context.Context, id int32) error
	EmailExists(ctx context.Context, email string) (bool, error)
	EnableUserTotp(ctx context.Context, id int32) error
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	GetPasswordResetByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPendingInvitationByEmail(ctx context.Context, email string) (Invitation, error)
	GetReactivationByHash(ctx context.Context, tokenHash string) (AccountReactivationToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Запросы контекста auth. Растут по мере порта роутеров auth/users.
	// Колонки — из baseline (00001_baseline.sql). sqlc-синтаксис имён: `-- name: X :kind`.
	// ─────────────────────────── users ───────────────────────────
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// ─────────────────────────── refresh_tokens ───────────────────────────
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error
	MarkPasswordResetUsed(ctx context.Context, id int32) error
	MarkReactivationUsed(ctx context.Context, id int32) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID int32) error
	RevokeInvitation(ctx context.Context, id int32) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SetUserLocked(ctx context.Context, arg SetUserLockedParams) error
	// ─────────────────────────── 2FA (TOTP) ───────────────────────────
	SetUserTotpSecret(ctx context.Context, arg SetUserTotpSecretParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
