// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimPendingMailJobs(ctx context.Context, arg ClaimPendingMailJobsParams) ([]MailJob, error)
	// Атомарно берёт задачу в работу (status='running', attempts++) при статусе, не
	// равном running/done (порт guard run_recon_job: повторную доставку не пробиваем).
	ClaimReconJobRunning(ctx context.Context, id int32) (HostFarmJob, error)
	ClearCommentMentions(ctx context.Context, commentID int32) error
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountFileImagesForVuln(ctx context.Context, arg CountFileImagesForVulnParams) (int64, error)
	CountHostAssetLinks(ctx context.Context, vulnerabilityID int32) (int64, error)
	CountHosts(ctx context.Context, arg CountHostsParams) (int64, error)
	// ─────────── note comments ───────────
	CountNoteComments(ctx context.Context, arg CountNoteCommentsParams) (int64, error)
	CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error)
	CountProjectsAdmin(ctx context.Context, status NullProjectStatus) (int64, error)
	CountProjectsForMember(ctx context.Context, arg CountProjectsForMemberParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID int32) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// ─────────── comments ───────────
	CountVulnComments(ctx context.Context, vulnerabilityID int32) (int64, error)
	CountVulns(ctx context.Context, arg CountVulnsParams) (int64, error)
	CountVulnsForHost(ctx context.Context, arg CountVulnsForHostParams) (int64, error)
	// Запросы контекста agenttokens (v1 CRUD + v2 bearer-auth).
	CreateAgentToken(ctx context.Context, arg CreateAgentTokenParams) (AgentApiToken, error)
	// ─────────────────────────── invitations ───────────────────────────
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	// ─────────────────────────── password_reset_tokens ───────────────────────────
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	// ─────────────────────────── account_reactivation_tokens ───────────────────────────
	CreateReactivationToken(ctx context.Context, arg CreateReactivationTokenParams) (AccountReactivationToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAgentToken(ctx context.Context, id int32) error
	DeleteCredential(ctx context.Context, id int32) error
	DeleteEndpoint(ctx context.Context, id int32) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteFile(ctx context.Context, id int32) error
	DeleteHiddenIP(ctx context.Context, arg DeleteHiddenIPParams) error
	DeleteHiddenIPs(ctx context.Context, arg DeleteHiddenIPsParams) error
	DeleteHost(ctx context.Context, arg DeleteHostParams) error
	DeleteHostByID(ctx context.Context, id int32) error
	DeleteHostIP(ctx context.Context, id int32) error
	DeleteJsFilesForHost(ctx context.Context, arg DeleteJsFilesForHostParams) error
	DeleteJsSecretsForFile(ctx context.Context, jsFileID int32) error
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeleteNote(ctx context.Context, id int32) error
	DeleteNoteComment(ctx context.Context, id int32) error
	DeletePort(ctx context.Context, id int32) error
	DeleteProject(ctx context.Context, id int32) error
	DeleteService(ctx context.Context, id int32) error
	DeleteServicesForPort(ctx context.Context, portID int32) error
	DeleteSubtreeFolders(ctx context.Context, path string) error
	DeleteSubtreeProjects(ctx context.Context, folder string) error
	DeleteVuln(ctx context.Context, id int32) error
	DeleteVulnAsset(ctx context.Context, id int32) error
	DeleteVulnComment(ctx context.Context, id int32) error
	DisableUserTotp(ctx context.Context, id int32) error
	EmailExists(ctx context.Context, email string) (bool, error)
	EnableUserTotp(ctx context.Context, id int32) error
	EndpointAssetInProject(ctx context.Context, arg EndpointAssetInProjectParams) (bool, error)
	ExpireUserUnusedPasswordResetTokens(ctx context.Context, userID int32) error
	ExpireUserUnusedReactivationTokens(ctx context.Context, userID int32) error
	FindEndpointByPathMethod(ctx context.Context, arg FindEndpointByPathMethodParams) (Endpoint, error)
	FindPortDup(ctx context.Context, arg FindPortDupParams) (Port, error)
	FindServiceByName(ctx context.Context, arg FindServiceByNameParams) (Service, error)
	FindSiblingFolderByName(ctx context.Context, arg FindSiblingFolderByNameParams) (ProjectFolder, error)
	FindSiblingNoteTitle(ctx context.Context, arg FindSiblingNoteTitleParams) (int32, error)
	FindVulnAsset(ctx context.Context, arg FindVulnAssetParams) (VulnerabilityAsset, error)
	GetActivePendingInvitationByEmail(ctx context.Context, email string) (Invitation, error)
	GetAgentTokenByHash(ctx context.Context, tokenHash string) (AgentApiToken, error)
	GetAgentTokenByID(ctx context.Context, id int32) (AgentApiToken, error)
	GetCommentHostID(ctx context.Context, id int32) (int32, error)
	// ─────────── резолверы контекста ───────────
	GetCommentNotificationContext(ctx context.Context, id int32) (GetCommentNotificationContextRow, error)
	GetCredential(ctx context.Context, arg GetCredentialParams) (GetCredentialRow, error)
	GetEndpointForHost(ctx context.Context, arg GetEndpointForHostParams) (Endpoint, error)
	// Снимок управляющих колонок отмены для поллера воркера.
	GetFarmCancelState(ctx context.Context, id int32) (GetFarmCancelStateRow, error)
	// Читает текущий cancel_steps под блокировкой строки (read-modify-write отмены
	// одного шага). Фильтр по проекту и kind — чужую задачу не трогаем.
	GetFarmCancelStepsForUpdate(ctx context.Context, arg GetFarmCancelStepsForUpdateParams) ([]byte, error)
	GetFileByID(ctx context.Context, id int32) (File, error)
	GetFileForVuln(ctx context.Context, arg GetFileForVulnParams) (File, error)
	GetFolderByID(ctx context.Context, id int32) (ProjectFolder, error)
	GetFolderByPath(ctx context.Context, path string) (ProjectFolder, error)
	GetHost(ctx context.Context, arg GetHostParams) (Host, error)
	// ─────────── find-or-create / attach хостов (persist) ───────────
	GetHostByHostname(ctx context.Context, arg GetHostByHostnameParams) (Host, error)
	GetHostByIPLiteral(ctx context.Context, arg GetHostByIPLiteralParams) (Host, error)
	GetHostFarmJob(ctx context.Context, id int32) (HostFarmJob, error)
	GetHostFarmJobForProject(ctx context.Context, arg GetHostFarmJobForProjectParams) (HostFarmJob, error)
	GetHostIPForHost(ctx context.Context, arg GetHostIPForHostParams) (HostIpAddress, error)
	GetInvitationByID(ctx context.Context, id int32) (Invitation, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	// Контекст recon, ферма JS: js_files/js_secrets. Скан «в памяти» (файлы в БД не
	// хранятся) — тут только находки, метаданные и апсерт по (project_id, url).
	GetJsFileByProjectURL(ctx context.Context, arg GetJsFileByProjectURLParams) (JsFile, error)
	GetMailJob(ctx context.Context, id int32) (MailJob, error)
	GetMember(ctx context.Context, arg GetMemberParams) (ProjectMember, error)
	GetNote(ctx context.Context, arg GetNoteParams) (GetNoteRow, error)
	GetNoteComment(ctx context.Context, arg GetNoteCommentParams) (ProjectNoteComment, error)
	GetNoteCommentNotificationContext(ctx context.Context, id int32) (GetNoteCommentNotificationContextRow, error)
	GetOriginIPHostByAddress(ctx context.Context, arg GetOriginIPHostByAddressParams) (Host, error)
	GetPasswordResetByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetPendingInvitationByEmail(ctx context.Context, email string) (Invitation, error)
	GetPort(ctx context.Context, arg GetPortParams) (Port, error)
	// ─────────── ports (upsert) ───────────
	GetPortByIPNumberProto(ctx context.Context, arg GetPortByIPNumberProtoParams) (Port, error)
	// Запросы контекста projects: проекты, папки, участники, заметки(+комментарии),
	// креды, hidden-ips, статистика, активность, уведомления, упоминания.
	// ─────────── projects ───────────
	GetProjectByID(ctx context.Context, id int32) (Project, error)
	GetProjectName(ctx context.Context, id int32) (string, error)
	GetReactivationByHash(ctx context.Context, tokenHash string) (AccountReactivationToken, error)
	// Контекст recon: пер-проектная конфигурация фермы. GetReconFarmConfig отдаёт
	// сырой JSONB-блоб (Go доклеивает дефолты), Upsert — идемпотентная запись.
	GetReconFarmConfig(ctx context.Context, projectID int32) ([]byte, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenForUser(ctx context.Context, arg GetRefreshTokenForUserParams) (RefreshToken, error)
	GetServiceForPort(ctx context.Context, arg GetServiceForPortParams) (Service, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Запросы контекста auth. Растут по мере порта роутеров auth/users.
	// Колонки — из baseline (00001_baseline.sql). sqlc-синтаксис имён: `-- name: X :kind`.
	// ─────────────────────────── users ───────────────────────────
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRoleByID(ctx context.Context, id int32) (GetUserRoleByIDRow, error)
	GetUsernameByID(ctx context.Context, id int32) (string, error)
	// Контекст vulns: vulnerabilities (+CVSS 4.0), assets, comments/mentions, files.
	// ─────────── vulnerabilities ───────────
	GetVuln(ctx context.Context, arg GetVulnParams) (GetVulnRow, error)
	GetVulnAssetLink(ctx context.Context, arg GetVulnAssetLinkParams) (VulnerabilityAsset, error)
	GetVulnComment(ctx context.Context, arg GetVulnCommentParams) (Comment, error)
	GetVulnTitleAndProject(ctx context.Context, id int32) (GetVulnTitleAndProjectRow, error)
	HiddenIPExists(ctx context.Context, arg HiddenIPExistsParams) (bool, error)
	// asset-in-project existence checks (polymorphic)
	HostAssetInProject(ctx context.Context, arg HostAssetInProjectParams) (bool, error)
	HostExistsInProject(ctx context.Context, arg HostExistsInProjectParams) (bool, error)
	InsertAgentTokenGrant(ctx context.Context, arg InsertAgentTokenGrantParams) error
	// Запросы контекста audit. Пишем журнал действий; чтение — в контексте audit позже.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCommentMention(ctx context.Context, arg InsertCommentMentionParams) error
	InsertCredential(ctx context.Context, arg InsertCredentialParams) (ProjectCredential, error)
	InsertEndpoint(ctx context.Context, arg InsertEndpointParams) (Endpoint, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	InsertFolder(ctx context.Context, arg InsertFolderParams) (ProjectFolder, error)
	InsertHiddenIP(ctx context.Context, arg InsertHiddenIPParams) error
	// Контекст inventory: hosts/ip-addresses/ports/services/endpoints (+ OpenAPI import/export).
	// hidden-ips живут в контексте projects (те же роуты) — здесь их нет.
	// ─────────── hosts ───────────
	InsertHost(ctx context.Context, arg InsertHostParams) (Host, error)
	// Контекст recon (ферма + scanner): задачи host_farm_jobs как durable-очередь и
	// запросы персиста хостов/адресов/портов сверх inventory.sql. Модель статусов
	// (порт farm/jobs.py + worker/recon_worker.py): pending→queued→running→done|failed.
	// attempts инкрементится при ВЗЯТИИ в работу (ClaimReconJobRunning), не при провале.
	// Каждый Update*Job СБРАСЫВАЕТ updated_at=now() — reclaim застрявших зависит от него.
	// ─────────── host_farm_jobs (очередь) ───────────
	InsertHostFarmJob(ctx context.Context, arg InsertHostFarmJobParams) (HostFarmJob, error)
	InsertHostIP(ctx context.Context, arg InsertHostIPParams) (HostIpAddress, error)
	InsertJsSecret(ctx context.Context, arg InsertJsSecretParams) error
	// Запросы контекста mail (outbox). Отправка — cmd/mail-worker.
	// Модель статусов (порт mail_worker.py): pending→queued→processing→sent|failed.
	// attempts инкрементится при ВЗЯТИИ в работу (MarkMailJobProcessing), не при провале.
	InsertMailJob(ctx context.Context, arg InsertMailJobParams) (MailJob, error)
	InsertMember(ctx context.Context, arg InsertMemberParams) (ProjectMember, error)
	// ─────────── notifications ───────────
	InsertMentionNotification(ctx context.Context, arg InsertMentionNotificationParams) error
	InsertNote(ctx context.Context, arg InsertNoteParams) (ProjectNote, error)
	InsertNoteComment(ctx context.Context, arg InsertNoteCommentParams) (ProjectNoteComment, error)
	// ─────────── notifications + mentions ───────────
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	InsertPort(ctx context.Context, arg InsertPortParams) (Port, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error)
	// ─────────────────────────── refresh_tokens ───────────────────────────
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	InsertService(ctx context.Context, arg InsertServiceParams) (Service, error)
	InsertVuln(ctx context.Context, arg InsertVulnParams) (Vulnerability, error)
	InsertVulnAsset(ctx context.Context, arg InsertVulnAssetParams) (VulnerabilityAsset, error)
	InsertVulnComment(ctx context.Context, arg InsertVulnCommentParams) (Comment, error)
	InsertVulnStatusNotification(ctx context.Context, arg InsertVulnStatusNotificationParams) error
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	ListAgentTokenGrants(ctx context.Context, tokenID int32) ([]int32, error)
	ListAgentTokensByCreator(ctx context.Context, createdBy int32) ([]AgentApiToken, error)
	ListAllProjectIDs(ctx context.Context) ([]int32, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListCommentMentions(ctx context.Context, commentID int32) ([]ListCommentMentionsRow, error)
	// ─────────── credentials ───────────
	ListCredentials(ctx context.Context, projectID int32) ([]ListCredentialsRow, error)
	// ─────────── endpoints ───────────
	ListEndpointsForHost(ctx context.Context, hostID int32) ([]Endpoint, error)
	ListEndpointsForHostOrdered(ctx context.Context, hostID int32) ([]Endpoint, error)
	ListEndpointsForHosts(ctx context.Context, hostIds []int32) ([]Endpoint, error)
	// ─────────── folders ───────────
	ListFolders(ctx context.Context) ([]ProjectFolder, error)
	// ─────────── hidden ips ───────────
	ListHiddenIPs(ctx context.Context, projectID int32) ([]string, error)
	// ─────────── host_ip_addresses ───────────
	ListHostIPs(ctx context.Context, hostID int32) ([]HostIpAddress, error)
	ListHostIPsForHosts(ctx context.Context, hostIds []int32) ([]HostIpAddress, error)
	ListHosts(ctx context.Context, arg ListHostsParams) ([]Host, error)
	ListJsFileURLsForHost(ctx context.Context, arg ListJsFileURLsForHostParams) ([]string, error)
	ListJsFileURLsForProject(ctx context.Context, projectID int32) ([]string, error)
	ListJsFilesForProject(ctx context.Context, projectID int32) ([]JsFile, error)
	ListJsSecretsForFile(ctx context.Context, jsFileID int32) ([]JsSecret, error)
	ListMemberProjectIDs(ctx context.Context, userID int32) ([]int32, error)
	ListMemberUserIDs(ctx context.Context, projectID int32) ([]int32, error)
	// ─────────── members ───────────
	ListMembers(ctx context.Context, projectID int32) ([]ListMembersRow, error)
	ListNoteComments(ctx context.Context, arg ListNoteCommentsParams) ([]ListNoteCommentsRow, error)
	// ─────────── notes ───────────
	ListNotes(ctx context.Context, projectID int32) ([]ListNotesRow, error)
	// ─────────── activity ───────────
	ListNotesActivity(ctx context.Context, arg ListNotesActivityParams) ([]ListNotesActivityRow, error)
	// Контекст notifications (читающая сторона; запись — в projects/vulns контекстах).
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPendingInvitations(ctx context.Context) ([]Invitation, error)
	// ─────────── ports ───────────
	ListPortsForHost(ctx context.Context, hostID int32) ([]Port, error)
	ListPortsForIPs(ctx context.Context, ipIds []int32) ([]Port, error)
	ListProjectActivity(ctx context.Context, arg ListProjectActivityParams) ([]ListProjectActivityRow, error)
	ListProjectAllHostnames(ctx context.Context, projectID int32) ([]pgtype.Text, error)
	// ─────────── выбор целей по проекту ───────────
	ListProjectDomainHostnames(ctx context.Context, projectID int32) ([]pgtype.Text, error)
	ListProjectHostIDNames(ctx context.Context, projectID int32) ([]ListProjectHostIDNamesRow, error)
	ListProjectOriginHostRows(ctx context.Context, projectID int32) ([]ListProjectOriginHostRowsRow, error)
	ListProjectOriginIPs(ctx context.Context, projectID int32) ([]string, error)
	ListProjectScanTargets(ctx context.Context, projectID int32) ([]ListProjectScanTargetsRow, error)
	ListProjectsAdmin(ctx context.Context, arg ListProjectsAdminParams) ([]Project, error)
	ListProjectsByIDs(ctx context.Context, ids []int32) ([]Project, error)
	ListProjectsForMember(ctx context.Context, arg ListProjectsForMemberParams) ([]Project, error)
	// ─────────── services ───────────
	ListServicesForPort(ctx context.Context, portID int32) ([]Service, error)
	ListServicesForPorts(ctx context.Context, portIds []int32) ([]Service, error)
	ListSiblingNotes(ctx context.Context, arg ListSiblingNotesParams) ([]ListSiblingNotesRow, error)
	ListStandaloneIPHostIDs(ctx context.Context, arg ListStandaloneIPHostIDsParams) ([]int32, error)
	ListSubtreeFolders(ctx context.Context, path string) ([]ProjectFolder, error)
	ListSubtreeProjects(ctx context.Context, folder string) ([]Project, error)
	// Запросы контекста users (роутер users.py). Часть операций переиспользует
	// запросы из auth.sql (GetUserByID/ByUsername/ByEmail, Username/EmailExists,
	// UpdateUserPassword, SetUserLocked/Active, EnableUserTotp/DisableUserTotp,
	// RevokeAllUserRefreshTokens, CreateInvitation, CreateReactivationToken,
	// ExpireUserUnusedReactivationTokens, InsertMailJob, InsertAuditLog).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// ─────────── vulnerability_assets ───────────
	ListVulnAssets(ctx context.Context, vulnerabilityID int32) ([]VulnerabilityAsset, error)
	ListVulnComments(ctx context.Context, arg ListVulnCommentsParams) ([]ListVulnCommentsRow, error)
	// ─────────── files ───────────
	ListVulnFiles(ctx context.Context, vulnerabilityID int32) ([]File, error)
	ListVulns(ctx context.Context, arg ListVulnsParams) ([]ListVulnsRow, error)
	ListVulnsForActivity(ctx context.Context, ids []int32) ([]ListVulnsForActivityRow, error)
	ListVulnsForHost(ctx context.Context, arg ListVulnsForHostParams) ([]ListVulnsForHostRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID int32) error
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error
	MarkMailJobFailed(ctx context.Context, arg MarkMailJobFailedParams) error
	MarkMailJobPending(ctx context.Context, arg MarkMailJobPendingParams) error
	MarkMailJobProcessing(ctx context.Context, id int32) (MailJob, error)
	MarkMailJobQueued(ctx context.Context, id int32) error
	MarkMailJobSent(ctx context.Context, id int32) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	MarkPasswordResetUsed(ctx context.Context, id int32) error
	MarkReactivationUsed(ctx context.Context, id int32) error
	MaxSiblingSortOrder(ctx context.Context, arg MaxSiblingSortOrderParams) (int32, error)
	MoveNote(ctx context.Context, arg MoveNoteParams) error
	PatchVulnStatus(ctx context.Context, arg PatchVulnStatusParams) (Vulnerability, error)
	PortAssetInProject(ctx context.Context, arg PortAssetInProjectParams) (bool, error)
	PrimaryHostID(ctx context.Context, vulnerabilityID int32) (int32, error)
	// ─────────── project stats ───────────
	ProjectStatsAdmin(ctx context.Context) ([]ProjectStatsAdminRow, error)
	ProjectStatsForMember(ctx context.Context, userID int32) ([]ProjectStatsForMemberRow, error)
	// Реклейм обычной дорожки: НЕ трогает farm_run (его прогон легитимно длинный,
	// иначе его переигрывали бы как «застрявший» → двойной прогон).
	ReclaimStaleReconJobsExcludingKind(ctx context.Context, arg ReclaimStaleReconJobsExcludingKindParams) (int64, error)
	// Реклейм фермовой дорожки: только farm_run и с БОЛЬШИМ окном stale_seconds
	// (прогон идёт минутами), чтобы живой прогон не считался застрявшим.
	ReclaimStaleReconJobsForKind(ctx context.Context, arg ReclaimStaleReconJobsForKindParams) (int64, error)
	// Сигнал отмены ВСЕГО прогона: cancel_requested=true. Только для farm_run задачи
	// этого проекта (иначе строка не совпадёт и апдейт — no-op).
	RequestFarmCancel(ctx context.Context, arg RequestFarmCancelParams) error
	// Сигнал отмены ВСЕХ активных (pending|running) farm_run задач проекта. Возвращает
	// число затронутых строк.
	RequestFarmCancelAllActive(ctx context.Context, projectID int32) (int64, error)
	ResetUserPasswordTemp(ctx context.Context, arg ResetUserPasswordTempParams) error
	// ─────────── comment mentions ───────────
	ResolveCommentMentionUsers(ctx context.Context, arg ResolveCommentMentionUsersParams) ([]ResolveCommentMentionUsersRow, error)
	ResolveMentionUsers(ctx context.Context, arg ResolveMentionUsersParams) ([]ResolveMentionUsersRow, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID int32) error
	RevokeInvitation(ctx context.Context, id int32) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SelectExistingHostIPLiterals(ctx context.Context, arg SelectExistingHostIPLiteralsParams) ([]pgtype.Text, error)
	// ─────────── existing-target keys (create_job) ───────────
	SelectExistingHostnames(ctx context.Context, arg SelectExistingHostnamesParams) ([]pgtype.Text, error)
	SelectExistingOriginIPAddresses(ctx context.Context, arg SelectExistingOriginIPAddressesParams) ([]string, error)
	// Воркер гоняет ДВЕ независимые дорожки: «обычная» (все kind, кроме farm_run —
	// держит add-hosts/add-ips/port-scan отзывчивыми) и «фермовая» (только farm_run,
	// долгие прогоны). Отсюда — выборка/реклейм с фильтром по kind, чтобы дорожки не
	// мешали друг другу: длинный farm_run не блокирует обычные задачи, а реклейм
	// обычной дорожки НИКОГДА не трогает бегущий farm_run (и наоборот).
	// Pending обычной дорожки: всё, КРОМЕ переданного kind (= 'farm_run').
	SelectPendingReconJobsExcludingKind(ctx context.Context, arg SelectPendingReconJobsExcludingKindParams) ([]int32, error)
	// Pending фермовой дорожки: только переданный kind (= 'farm_run').
	SelectPendingReconJobsForKind(ctx context.Context, arg SelectPendingReconJobsForKindParams) ([]int32, error)
	ServiceAssetInProject(ctx context.Context, arg ServiceAssetInProjectParams) (bool, error)
	// Записывает новый массив id шагов к отмене (маршалится в Go после дедупа).
	SetFarmCancelSteps(ctx context.Context, arg SetFarmCancelStepsParams) error
	// ─────────── host_ip_addresses (ensure_ips) ───────────
	SetHostIPCloudflare(ctx context.Context, arg SetHostIPCloudflareParams) error
	SetHostIPHostnames(ctx context.Context, arg SetHostIPHostnamesParams) error
	SetHostPrimaryIP(ctx context.Context, arg SetHostPrimaryIPParams) error
	SetHostStatus(ctx context.Context, arg SetHostStatusParams) error
	// Помечает прогон отменённым (НЕ провал): status='cancelled', частичный result,
	// finished_at=now(). Ошибочные поля чистятся — отмена не является ошибкой.
	SetJobCancelled(ctx context.Context, arg SetJobCancelledParams) error
	SetJobDone(ctx context.Context, arg SetJobDoneParams) error
	SetJobFailed(ctx context.Context, arg SetJobFailedParams) error
	// Обновляет JSON-снимок прогресса полного прогона фермы (kind='farm_run') по мере
	// продвижения стадий. Тоже сбрасывает updated_at, чтобы reclaim не забрал живую задачу.
	SetJobProgress(ctx context.Context, arg SetJobProgressParams) error
	SetJobQueued(ctx context.Context, id int32) error
	SetNoteSortOrder(ctx context.Context, arg SetNoteSortOrderParams) error
	SetPortStateHTTP(ctx context.Context, arg SetPortStateHTTPParams) error
	SetPortStateOpen(ctx context.Context, id int32) error
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) error
	SetUserLocked(ctx context.Context, arg SetUserLockedParams) error
	// ─────────────────────────── 2FA (TOTP) ───────────────────────────
	SetUserTotpSecret(ctx context.Context, arg SetUserTotpSecretParams) error
	SetUserTotpSecretForSetup(ctx context.Context, arg SetUserTotpSecretForSetupParams) error
	TouchAgentTokenLastUsed(ctx context.Context, arg TouchAgentTokenLastUsedParams) error
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error)
	UpdateFolderPath(ctx context.Context, arg UpdateFolderPathParams) error
	UpdateFolderPathParent(ctx context.Context, arg UpdateFolderPathParentParams) error
	UpdateHost(ctx context.Context, arg UpdateHostParams) (Host, error)
	UpdateHostIP(ctx context.Context, arg UpdateHostIPParams) error
	UpdateInvitationForResend(ctx context.Context, arg UpdateInvitationForResendParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdateNoteComment(ctx context.Context, arg UpdateNoteCommentParams) error
	UpdatePort(ctx context.Context, arg UpdatePortParams) (Port, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectFolderPath(ctx context.Context, arg UpdateProjectFolderPathParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateVuln(ctx context.Context, arg UpdateVulnParams) (Vulnerability, error)
	UpdateVulnComment(ctx context.Context, arg UpdateVulnCommentParams) error
	UpsertJsFile(ctx context.Context, arg UpsertJsFileParams) (int32, error)
	UpsertReconFarmConfig(ctx context.Context, arg UpsertReconFarmConfigParams) error
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
