// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recon.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimReconJobRunning = `-- name: ClaimReconJobRunning :one
UPDATE host_farm_jobs
SET status = 'running', attempts = attempts + 1, updated_at = now()
WHERE id = $1 AND status NOT IN ('running', 'done')
RETURNING id, project_id, created_by, kind, status, targets_total, result, error, raw, attempts, published_at, last_error, finished_at, skipped_targets, created_at, updated_at, progress, cancel_requested, cancel_steps
`

// Атомарно берёт задачу в работу (status='running', attempts++) при статусе, не
// равном running/done (порт guard run_recon_job: повторную доставку не пробиваем).
func (q *Queries) ClaimReconJobRunning(ctx context.Context, id int32) (HostFarmJob, error) {
	row := q.db.QueryRow(ctx, claimReconJobRunning, id)
	var i HostFarmJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Kind,
		&i.Status,
		&i.TargetsTotal,
		&i.Result,
		&i.Error,
		&i.Raw,
		&i.Attempts,
		&i.PublishedAt,
		&i.LastError,
		&i.FinishedAt,
		&i.SkippedTargets,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
		&i.CancelRequested,
		&i.CancelSteps,
	)
	return i, err
}

const clearStagedEndpoints = `-- name: ClearStagedEndpoints :execrows
DELETE FROM recon_farm_staged_endpoints
WHERE project_id = $1 AND job_id = $2
`

type ClearStagedEndpointsParams struct {
	ProjectID int32 `json:"project_id"`
	JobID     int32 `json:"job_id"`
}

// Удаляет staged-эндпоинты одного прогона; возвращает число удалённых.
func (q *Queries) ClearStagedEndpoints(ctx context.Context, arg ClearStagedEndpointsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearStagedEndpoints, arg.ProjectID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearStagedHosts = `-- name: ClearStagedHosts :execrows
DELETE FROM recon_farm_staged_hosts
WHERE project_id = $1 AND job_id = $2
`

type ClearStagedHostsParams struct {
	ProjectID int32 `json:"project_id"`
	JobID     int32 `json:"job_id"`
}

// Удаляет staged-строки одного прогона; возвращает число удалённых.
func (q *Queries) ClearStagedHosts(ctx context.Context, arg ClearStagedHostsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearStagedHosts, arg.ProjectID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearStagedJs = `-- name: ClearStagedJs :execrows
DELETE FROM recon_farm_staged_js
WHERE project_id = $1 AND job_id = $2
`

type ClearStagedJsParams struct {
	ProjectID int32 `json:"project_id"`
	JobID     int32 `json:"job_id"`
}

// Удаляет staged-находки JS одного прогона; возвращает число удалённых.
func (q *Queries) ClearStagedJs(ctx context.Context, arg ClearStagedJsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearStagedJs, arg.ProjectID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHiddenIPs = `-- name: DeleteHiddenIPs :exec
DELETE FROM project_hidden_ips
WHERE project_id = $1 AND ip_address = ANY($2::text[])
`

type DeleteHiddenIPsParams struct {
	ProjectID int32    `json:"project_id"`
	Addrs     []string `json:"addrs"`
}

func (q *Queries) DeleteHiddenIPs(ctx context.Context, arg DeleteHiddenIPsParams) error {
	_, err := q.db.Exec(ctx, deleteHiddenIPs, arg.ProjectID, arg.Addrs)
	return err
}

const deleteServicesForPort = `-- name: DeleteServicesForPort :exec
DELETE FROM services WHERE port_id = $1
`

func (q *Queries) DeleteServicesForPort(ctx context.Context, portID int32) error {
	_, err := q.db.Exec(ctx, deleteServicesForPort, portID)
	return err
}

const getFarmCancelState = `-- name: GetFarmCancelState :one
SELECT cancel_requested, cancel_steps FROM host_farm_jobs WHERE id = $1
`

type GetFarmCancelStateRow struct {
	CancelRequested bool   `json:"cancel_requested"`
	CancelSteps     []byte `json:"cancel_steps"`
}

// Снимок управляющих колонок отмены для поллера воркера.
func (q *Queries) GetFarmCancelState(ctx context.Context, id int32) (GetFarmCancelStateRow, error) {
	row := q.db.QueryRow(ctx, getFarmCancelState, id)
	var i GetFarmCancelStateRow
	err := row.Scan(&i.CancelRequested, &i.CancelSteps)
	return i, err
}

const getFarmCancelStepsForUpdate = `-- name: GetFarmCancelStepsForUpdate :one
SELECT cancel_steps FROM host_farm_jobs
WHERE id = $1 AND project_id = $2 AND kind = 'farm_run'
FOR UPDATE
`

type GetFarmCancelStepsForUpdateParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

// Читает текущий cancel_steps под блокировкой строки (read-modify-write отмены
// одного шага). Фильтр по проекту и kind — чужую задачу не трогаем.
func (q *Queries) GetFarmCancelStepsForUpdate(ctx context.Context, arg GetFarmCancelStepsForUpdateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFarmCancelStepsForUpdate, arg.ID, arg.ProjectID)
	var cancel_steps []byte
	err := row.Scan(&cancel_steps)
	return cancel_steps, err
}

const getHostByHostname = `-- name: GetHostByHostname :one

SELECT id, project_id, ip_address, hostname, status, os_type, notes, origin, created_at, updated_at FROM hosts WHERE project_id = $1 AND hostname = $2 ORDER BY id LIMIT 1
`

type GetHostByHostnameParams struct {
	ProjectID int32       `json:"project_id"`
	Hostname  pgtype.Text `json:"hostname"`
}

// ─────────── find-or-create / attach хостов (persist) ───────────
func (q *Queries) GetHostByHostname(ctx context.Context, arg GetHostByHostnameParams) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByHostname, arg.ProjectID, arg.Hostname)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IpAddress,
		&i.Hostname,
		&i.Status,
		&i.OsType,
		&i.Notes,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostByIPLiteral = `-- name: GetHostByIPLiteral :one
SELECT id, project_id, ip_address, hostname, status, os_type, notes, origin, created_at, updated_at FROM hosts WHERE project_id = $1 AND ip_address = $2 ORDER BY id LIMIT 1
`

type GetHostByIPLiteralParams struct {
	ProjectID int32       `json:"project_id"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) GetHostByIPLiteral(ctx context.Context, arg GetHostByIPLiteralParams) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByIPLiteral, arg.ProjectID, arg.IpAddress)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IpAddress,
		&i.Hostname,
		&i.Status,
		&i.OsType,
		&i.Notes,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostFarmJob = `-- name: GetHostFarmJob :one
SELECT id, project_id, created_by, kind, status, targets_total, result, error, raw, attempts, published_at, last_error, finished_at, skipped_targets, created_at, updated_at, progress, cancel_requested, cancel_steps FROM host_farm_jobs WHERE id = $1
`

func (q *Queries) GetHostFarmJob(ctx context.Context, id int32) (HostFarmJob, error) {
	row := q.db.QueryRow(ctx, getHostFarmJob, id)
	var i HostFarmJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Kind,
		&i.Status,
		&i.TargetsTotal,
		&i.Result,
		&i.Error,
		&i.Raw,
		&i.Attempts,
		&i.PublishedAt,
		&i.LastError,
		&i.FinishedAt,
		&i.SkippedTargets,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
		&i.CancelRequested,
		&i.CancelSteps,
	)
	return i, err
}

const getHostFarmJobForProject = `-- name: GetHostFarmJobForProject :one
SELECT id, project_id, created_by, kind, status, targets_total, result, error, raw, attempts, published_at, last_error, finished_at, skipped_targets, created_at, updated_at, progress, cancel_requested, cancel_steps FROM host_farm_jobs
WHERE id = $1 AND project_id = $2 AND kind = $3
`

type GetHostFarmJobForProjectParams struct {
	ID        int32  `json:"id"`
	ProjectID int32  `json:"project_id"`
	Kind      string `json:"kind"`
}

func (q *Queries) GetHostFarmJobForProject(ctx context.Context, arg GetHostFarmJobForProjectParams) (HostFarmJob, error) {
	row := q.db.QueryRow(ctx, getHostFarmJobForProject, arg.ID, arg.ProjectID, arg.Kind)
	var i HostFarmJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Kind,
		&i.Status,
		&i.TargetsTotal,
		&i.Result,
		&i.Error,
		&i.Raw,
		&i.Attempts,
		&i.PublishedAt,
		&i.LastError,
		&i.FinishedAt,
		&i.SkippedTargets,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
		&i.CancelRequested,
		&i.CancelSteps,
	)
	return i, err
}

const getOriginIPHostByAddress = `-- name: GetOriginIPHostByAddress :one
SELECT h.id, h.project_id, h.ip_address, h.hostname, h.status, h.os_type, h.notes, h.origin, h.created_at, h.updated_at FROM hosts h
JOIN host_ip_addresses hia ON hia.host_id = h.id
WHERE h.project_id = $1 AND h.origin = 'ip' AND hia.ip_address = $2
ORDER BY h.created_at
LIMIT 1
`

type GetOriginIPHostByAddressParams struct {
	ProjectID int32  `json:"project_id"`
	IpAddress string `json:"ip_address"`
}

func (q *Queries) GetOriginIPHostByAddress(ctx context.Context, arg GetOriginIPHostByAddressParams) (Host, error) {
	row := q.db.QueryRow(ctx, getOriginIPHostByAddress, arg.ProjectID, arg.IpAddress)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IpAddress,
		&i.Hostname,
		&i.Status,
		&i.OsType,
		&i.Notes,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortByIPNumberProto = `-- name: GetPortByIPNumberProto :one

SELECT id, host_id, ip_address_id, port_number, protocol, state, http_status, created_at, updated_at FROM ports WHERE ip_address_id = $1 AND port_number = $2 AND protocol = $3 LIMIT 1
`

type GetPortByIPNumberProtoParams struct {
	IpAddressID int32        `json:"ip_address_id"`
	PortNumber  int32        `json:"port_number"`
	Protocol    PortProtocol `json:"protocol"`
}

// ─────────── ports (upsert) ───────────
func (q *Queries) GetPortByIPNumberProto(ctx context.Context, arg GetPortByIPNumberProtoParams) (Port, error) {
	row := q.db.QueryRow(ctx, getPortByIPNumberProto, arg.IpAddressID, arg.PortNumber, arg.Protocol)
	var i Port
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.IpAddressID,
		&i.PortNumber,
		&i.Protocol,
		&i.State,
		&i.HttpStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHostFarmJob = `-- name: InsertHostFarmJob :one


INSERT INTO host_farm_jobs (project_id, created_by, kind, status, targets_total, raw, skipped_targets, result, progress, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, created_by, kind, status, targets_total, result, error, raw, attempts, published_at, last_error, finished_at, skipped_targets, created_at, updated_at, progress, cancel_requested, cancel_steps
`

type InsertHostFarmJobParams struct {
	ProjectID      int32              `json:"project_id"`
	CreatedBy      int32              `json:"created_by"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	TargetsTotal   pgtype.Int4        `json:"targets_total"`
	Raw            pgtype.Text        `json:"raw"`
	SkippedTargets []byte             `json:"skipped_targets"`
	Result         []byte             `json:"result"`
	Progress       []byte             `json:"progress"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

// Контекст recon (ферма + scanner): задачи host_farm_jobs как durable-очередь и
// запросы персиста хостов/адресов/портов сверх inventory.sql. Модель статусов
// (порт farm/jobs.py + worker/recon_worker.py): pending→queued→running→done|failed.
// attempts инкрементится при ВЗЯТИИ в работу (ClaimReconJobRunning), не при провале.
// Каждый Update*Job СБРАСЫВАЕТ updated_at=now() — reclaim застрявших зависит от него.
// ─────────── host_farm_jobs (очередь) ───────────
func (q *Queries) InsertHostFarmJob(ctx context.Context, arg InsertHostFarmJobParams) (HostFarmJob, error) {
	row := q.db.QueryRow(ctx, insertHostFarmJob,
		arg.ProjectID,
		arg.CreatedBy,
		arg.Kind,
		arg.Status,
		arg.TargetsTotal,
		arg.Raw,
		arg.SkippedTargets,
		arg.Result,
		arg.Progress,
		arg.FinishedAt,
	)
	var i HostFarmJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Kind,
		&i.Status,
		&i.TargetsTotal,
		&i.Result,
		&i.Error,
		&i.Raw,
		&i.Attempts,
		&i.PublishedAt,
		&i.LastError,
		&i.FinishedAt,
		&i.SkippedTargets,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
		&i.CancelRequested,
		&i.CancelSteps,
	)
	return i, err
}

const insertStagedEndpoint = `-- name: InsertStagedEndpoint :exec

INSERT INTO recon_farm_staged_endpoints (project_id, job_id, host, url, method, source)
VALUES ($1, $2, $3, $4,
        $5, $6)
`

type InsertStagedEndpointParams struct {
	ProjectID int32       `json:"project_id"`
	JobID     int32       `json:"job_id"`
	Host      string      `json:"host"`
	Url       string      `json:"url"`
	Method    pgtype.Text `json:"method"`
	Source    pgtype.Text `json:"source"`
}

// ─────────── стейджинг эндпоинтов прогона (recon_farm_staged_endpoints) ───────────
// Стадия эндпоинтов (katana/gau/waybackurls) складывает найденные URL сюда; импорт
// создаёт реальные endpoints проекта (по имени хоста). ports/hosts не трогаются.
func (q *Queries) InsertStagedEndpoint(ctx context.Context, arg InsertStagedEndpointParams) error {
	_, err := q.db.Exec(ctx, insertStagedEndpoint,
		arg.ProjectID,
		arg.JobID,
		arg.Host,
		arg.Url,
		arg.Method,
		arg.Source,
	)
	return err
}

const insertStagedHost = `-- name: InsertStagedHost :exec

INSERT INTO recon_farm_staged_hosts (project_id, job_id, hostname, ip, alive, source, ports)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type InsertStagedHostParams struct {
	ProjectID int32       `json:"project_id"`
	JobID     int32       `json:"job_id"`
	Hostname  string      `json:"hostname"`
	Ip        pgtype.Text `json:"ip"`
	Alive     bool        `json:"alive"`
	Source    pgtype.Text `json:"source"`
	Ports     []byte      `json:"ports"`
}

// ─────────── стейджинг полного прогона фермы (recon_farm_staged_hosts) ───────────
// Полный прогон (kind='farm_run') НЕ пишет в проект: находки складываются сюда, а
// пользователь импортирует выбранное вручную. ports — JSONB-массив портов.
func (q *Queries) InsertStagedHost(ctx context.Context, arg InsertStagedHostParams) error {
	_, err := q.db.Exec(ctx, insertStagedHost,
		arg.ProjectID,
		arg.JobID,
		arg.Hostname,
		arg.Ip,
		arg.Alive,
		arg.Source,
		arg.Ports,
	)
	return err
}

const insertStagedJs = `-- name: InsertStagedJs :exec

INSERT INTO recon_farm_staged_js (project_id, job_id, host, url, kind, value, severity)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type InsertStagedJsParams struct {
	ProjectID int32       `json:"project_id"`
	JobID     int32       `json:"job_id"`
	Host      string      `json:"host"`
	Url       string      `json:"url"`
	Kind      string      `json:"kind"`
	Value     string      `json:"value"`
	Severity  pgtype.Text `json:"severity"`
}

// ─────────── стейджинг JS-майнинга прогона (recon_farm_staged_js) ───────────
// Стадия JS (trufflehog + regex) складывает находки сюда: по строке на секрет
// (kind='secret', value=preview, severity) или эндпоинт (kind='endpoint', value=path).
// Импорт создаёт js_files/secrets проекта обычным persist-путём.
func (q *Queries) InsertStagedJs(ctx context.Context, arg InsertStagedJsParams) error {
	_, err := q.db.Exec(ctx, insertStagedJs,
		arg.ProjectID,
		arg.JobID,
		arg.Host,
		arg.Url,
		arg.Kind,
		arg.Value,
		arg.Severity,
	)
	return err
}

const latestFarmRunJobID = `-- name: LatestFarmRunJobID :one
SELECT id FROM host_farm_jobs
WHERE project_id = $1 AND kind = 'farm_run'
ORDER BY id DESC
LIMIT 1
`

// id последнего прогона фермы проекта (для отчёта без явного job_id).
func (q *Queries) LatestFarmRunJobID(ctx context.Context, projectID int32) (int32, error) {
	row := q.db.QueryRow(ctx, latestFarmRunJobID, projectID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listFarmRunJobs = `-- name: ListFarmRunJobs :many
SELECT id, status, raw, result, finished_at, created_at
FROM host_farm_jobs
WHERE project_id = $1 AND kind = 'farm_run'
ORDER BY id DESC
LIMIT $2
`

type ListFarmRunJobsParams struct {
	ProjectID int32 `json:"project_id"`
	Lim       int32 `json:"lim"`
}

type ListFarmRunJobsRow struct {
	ID         int32              `json:"id"`
	Status     string             `json:"status"`
	Raw        pgtype.Text        `json:"raw"`
	Result     []byte             `json:"result"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// История прогонов фермы проекта (новые сверху): статус, конфиг (raw) и итог
// (result) для показа в логах и перехода к отчёту/настройкам конкретного скана.
func (q *Queries) ListFarmRunJobs(ctx context.Context, arg ListFarmRunJobsParams) ([]ListFarmRunJobsRow, error) {
	rows, err := q.db.Query(ctx, listFarmRunJobs, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFarmRunJobsRow{}
	for rows.Next() {
		var i ListFarmRunJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Raw,
			&i.Result,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectAllHostnames = `-- name: ListProjectAllHostnames :many
SELECT hostname FROM hosts WHERE project_id = $1 AND hostname IS NOT NULL
`

func (q *Queries) ListProjectAllHostnames(ctx context.Context, projectID int32) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listProjectAllHostnames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var hostname pgtype.Text
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDomainHostnames = `-- name: ListProjectDomainHostnames :many

SELECT hostname FROM hosts
WHERE project_id = $1 AND origin = 'host' AND hostname IS NOT NULL
`

// ─────────── выбор целей по проекту ───────────
func (q *Queries) ListProjectDomainHostnames(ctx context.Context, projectID int32) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listProjectDomainHostnames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var hostname pgtype.Text
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectHostIDNames = `-- name: ListProjectHostIDNames :many
SELECT id, hostname FROM hosts WHERE project_id = $1
`

type ListProjectHostIDNamesRow struct {
	ID       int32       `json:"id"`
	Hostname pgtype.Text `json:"hostname"`
}

func (q *Queries) ListProjectHostIDNames(ctx context.Context, projectID int32) ([]ListProjectHostIDNamesRow, error) {
	rows, err := q.db.Query(ctx, listProjectHostIDNames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectHostIDNamesRow{}
	for rows.Next() {
		var i ListProjectHostIDNamesRow
		if err := rows.Scan(&i.ID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectOriginHostRows = `-- name: ListProjectOriginHostRows :many
SELECT id, hostname FROM hosts
WHERE project_id = $1 AND origin = 'host' AND hostname IS NOT NULL
`

type ListProjectOriginHostRowsRow struct {
	ID       int32       `json:"id"`
	Hostname pgtype.Text `json:"hostname"`
}

func (q *Queries) ListProjectOriginHostRows(ctx context.Context, projectID int32) ([]ListProjectOriginHostRowsRow, error) {
	rows, err := q.db.Query(ctx, listProjectOriginHostRows, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectOriginHostRowsRow{}
	for rows.Next() {
		var i ListProjectOriginHostRowsRow
		if err := rows.Scan(&i.ID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectOriginIPs = `-- name: ListProjectOriginIPs :many
SELECT hia.ip_address FROM host_ip_addresses hia
JOIN hosts h ON h.id = hia.host_id
WHERE h.project_id = $1 AND h.origin = 'ip'
`

func (q *Queries) ListProjectOriginIPs(ctx context.Context, projectID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listProjectOriginIPs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ip_address string
		if err := rows.Scan(&ip_address); err != nil {
			return nil, err
		}
		items = append(items, ip_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectScanTargets = `-- name: ListProjectScanTargets :many
SELECT hostname, ip_address FROM hosts WHERE project_id = $1
`

type ListProjectScanTargetsRow struct {
	Hostname  pgtype.Text `json:"hostname"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) ListProjectScanTargets(ctx context.Context, projectID int32) ([]ListProjectScanTargetsRow, error) {
	rows, err := q.db.Query(ctx, listProjectScanTargets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectScanTargetsRow{}
	for rows.Next() {
		var i ListProjectScanTargetsRow
		if err := rows.Scan(&i.Hostname, &i.IpAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedEndpoints = `-- name: ListStagedEndpoints :many
SELECT id, project_id, job_id, host, url, method, source, imported, created_at
FROM recon_farm_staged_endpoints
WHERE project_id = $1 AND job_id = $2
ORDER BY id
`

type ListStagedEndpointsParams struct {
	ProjectID int32 `json:"project_id"`
	JobID     int32 `json:"job_id"`
}

// Все staged-эндпоинты одного прогона (для отчёта), по возрастанию id.
func (q *Queries) ListStagedEndpoints(ctx context.Context, arg ListStagedEndpointsParams) ([]ReconFarmStagedEndpoint, error) {
	rows, err := q.db.Query(ctx, listStagedEndpoints, arg.ProjectID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconFarmStagedEndpoint{}
	for rows.Next() {
		var i ReconFarmStagedEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Host,
			&i.Url,
			&i.Method,
			&i.Source,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedEndpointsByIDs = `-- name: ListStagedEndpointsByIDs :many
SELECT id, project_id, job_id, host, url, method, source, imported, created_at
FROM recon_farm_staged_endpoints
WHERE project_id = $1 AND id = ANY($2::int[])
ORDER BY id
`

type ListStagedEndpointsByIDsParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Выбранные staged-эндпоинты проекта по id (для импорта). Скоуп проекта обязателен.
func (q *Queries) ListStagedEndpointsByIDs(ctx context.Context, arg ListStagedEndpointsByIDsParams) ([]ReconFarmStagedEndpoint, error) {
	rows, err := q.db.Query(ctx, listStagedEndpointsByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconFarmStagedEndpoint{}
	for rows.Next() {
		var i ReconFarmStagedEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Host,
			&i.Url,
			&i.Method,
			&i.Source,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedHosts = `-- name: ListStagedHosts :many
SELECT id, project_id, job_id, hostname, ip, alive, source, ports, imported, created_at
FROM recon_farm_staged_hosts
WHERE project_id = $1 AND job_id = $2
ORDER BY id
`

type ListStagedHostsParams struct {
	ProjectID int32 `json:"project_id"`
	JobID     int32 `json:"job_id"`
}

// Все staged-строки одного прогона (для отчёта), по возрастанию id.
func (q *Queries) ListStagedHosts(ctx context.Context, arg ListStagedHostsParams) ([]ReconFarmStagedHost, error) {
	rows, err := q.db.Query(ctx, listStagedHosts, arg.ProjectID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconFarmStagedHost{}
	for rows.Next() {
		var i ReconFarmStagedHost
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Hostname,
			&i.Ip,
			&i.Alive,
			&i.Source,
			&i.Ports,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedHostsByIDs = `-- name: ListStagedHostsByIDs :many
SELECT id, project_id, job_id, hostname, ip, alive, source, ports, imported, created_at
FROM recon_farm_staged_hosts
WHERE project_id = $1 AND id = ANY($2::int[])
ORDER BY id
`

type ListStagedHostsByIDsParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Выбранные staged-строки проекта по id (для импорта). Скоуп проекта обязателен —
// чужие строки не импортируем.
func (q *Queries) ListStagedHostsByIDs(ctx context.Context, arg ListStagedHostsByIDsParams) ([]ReconFarmStagedHost, error) {
	rows, err := q.db.Query(ctx, listStagedHostsByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconFarmStagedHost{}
	for rows.Next() {
		var i ReconFarmStagedHost
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Hostname,
			&i.Ip,
			&i.Alive,
			&i.Source,
			&i.Ports,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedJs = `-- name: ListStagedJs :many
SELECT id, project_id, job_id, host, url, kind, value, severity, imported, created_at
FROM recon_farm_staged_js
WHERE project_id = $1 AND job_id = $2
ORDER BY id
`

type ListStagedJsParams struct {
	ProjectID int32 `json:"project_id"`
	JobID     int32 `json:"job_id"`
}

// Все staged-находки JS одного прогона (для отчёта), по возрастанию id.
func (q *Queries) ListStagedJs(ctx context.Context, arg ListStagedJsParams) ([]ReconFarmStagedJ, error) {
	rows, err := q.db.Query(ctx, listStagedJs, arg.ProjectID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconFarmStagedJ{}
	for rows.Next() {
		var i ReconFarmStagedJ
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Host,
			&i.Url,
			&i.Kind,
			&i.Value,
			&i.Severity,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedJsByIDs = `-- name: ListStagedJsByIDs :many
SELECT id, project_id, job_id, host, url, kind, value, severity, imported, created_at
FROM recon_farm_staged_js
WHERE project_id = $1 AND id = ANY($2::int[])
ORDER BY id
`

type ListStagedJsByIDsParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Выбранные staged-находки JS проекта по id (для импорта). Скоуп проекта обязателен.
func (q *Queries) ListStagedJsByIDs(ctx context.Context, arg ListStagedJsByIDsParams) ([]ReconFarmStagedJ, error) {
	rows, err := q.db.Query(ctx, listStagedJsByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconFarmStagedJ{}
	for rows.Next() {
		var i ReconFarmStagedJ
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobID,
			&i.Host,
			&i.Url,
			&i.Kind,
			&i.Value,
			&i.Severity,
			&i.Imported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStagedEndpointsImported = `-- name: MarkStagedEndpointsImported :exec
UPDATE recon_farm_staged_endpoints SET imported = true
WHERE project_id = $1 AND id = ANY($2::int[])
`

type MarkStagedEndpointsImportedParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Помечает выбранные staged-эндпоинты импортированными (идемпотентно).
func (q *Queries) MarkStagedEndpointsImported(ctx context.Context, arg MarkStagedEndpointsImportedParams) error {
	_, err := q.db.Exec(ctx, markStagedEndpointsImported, arg.ProjectID, arg.Ids)
	return err
}

const markStagedImported = `-- name: MarkStagedImported :exec
UPDATE recon_farm_staged_hosts SET imported = true
WHERE project_id = $1 AND id = ANY($2::int[])
`

type MarkStagedImportedParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Помечает выбранные staged-строки импортированными (идемпотентно).
func (q *Queries) MarkStagedImported(ctx context.Context, arg MarkStagedImportedParams) error {
	_, err := q.db.Exec(ctx, markStagedImported, arg.ProjectID, arg.Ids)
	return err
}

const markStagedJsImported = `-- name: MarkStagedJsImported :exec
UPDATE recon_farm_staged_js SET imported = true
WHERE project_id = $1 AND id = ANY($2::int[])
`

type MarkStagedJsImportedParams struct {
	ProjectID int32   `json:"project_id"`
	Ids       []int32 `json:"ids"`
}

// Помечает выбранные staged-находки JS импортированными (идемпотентно).
func (q *Queries) MarkStagedJsImported(ctx context.Context, arg MarkStagedJsImportedParams) error {
	_, err := q.db.Exec(ctx, markStagedJsImported, arg.ProjectID, arg.Ids)
	return err
}

const reclaimStaleReconJobsExcludingKind = `-- name: ReclaimStaleReconJobsExcludingKind :execrows
UPDATE host_farm_jobs SET status = 'pending', updated_at = now()
WHERE status IN ('queued', 'running')
  AND kind <> $1
  AND updated_at < now() - ($2::int * interval '1 second')
  AND attempts < $3
`

type ReclaimStaleReconJobsExcludingKindParams struct {
	Kind         string `json:"kind"`
	StaleSeconds int32  `json:"stale_seconds"`
	MaxAttempts  int32  `json:"max_attempts"`
}

// Реклейм обычной дорожки: НЕ трогает farm_run (его прогон легитимно длинный,
// иначе его переигрывали бы как «застрявший» → двойной прогон).
func (q *Queries) ReclaimStaleReconJobsExcludingKind(ctx context.Context, arg ReclaimStaleReconJobsExcludingKindParams) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleReconJobsExcludingKind, arg.Kind, arg.StaleSeconds, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reclaimStaleReconJobsForKind = `-- name: ReclaimStaleReconJobsForKind :execrows
UPDATE host_farm_jobs SET status = 'pending', updated_at = now()
WHERE status IN ('queued', 'running')
  AND kind = $1
  AND updated_at < now() - ($2::int * interval '1 second')
  AND attempts < $3
`

type ReclaimStaleReconJobsForKindParams struct {
	Kind         string `json:"kind"`
	StaleSeconds int32  `json:"stale_seconds"`
	MaxAttempts  int32  `json:"max_attempts"`
}

// Реклейм фермовой дорожки: только farm_run и с БОЛЬШИМ окном stale_seconds
// (прогон идёт минутами), чтобы живой прогон не считался застрявшим.
func (q *Queries) ReclaimStaleReconJobsForKind(ctx context.Context, arg ReclaimStaleReconJobsForKindParams) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleReconJobsForKind, arg.Kind, arg.StaleSeconds, arg.MaxAttempts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestFarmCancel = `-- name: RequestFarmCancel :exec
UPDATE host_farm_jobs
SET cancel_requested = true, updated_at = now()
WHERE id = $1 AND project_id = $2 AND kind = 'farm_run'
`

type RequestFarmCancelParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

// Сигнал отмены ВСЕГО прогона: cancel_requested=true. Только для farm_run задачи
// этого проекта (иначе строка не совпадёт и апдейт — no-op).
func (q *Queries) RequestFarmCancel(ctx context.Context, arg RequestFarmCancelParams) error {
	_, err := q.db.Exec(ctx, requestFarmCancel, arg.ID, arg.ProjectID)
	return err
}

const requestFarmCancelAllActive = `-- name: RequestFarmCancelAllActive :execrows
UPDATE host_farm_jobs
SET cancel_requested = true, updated_at = now()
WHERE project_id = $1 AND kind = 'farm_run' AND status IN ('pending', 'running')
`

// Сигнал отмены ВСЕХ активных (pending|running) farm_run задач проекта. Возвращает
// число затронутых строк.
func (q *Queries) RequestFarmCancelAllActive(ctx context.Context, projectID int32) (int64, error) {
	result, err := q.db.Exec(ctx, requestFarmCancelAllActive, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectExistingHostIPLiterals = `-- name: SelectExistingHostIPLiterals :many
SELECT ip_address FROM hosts
WHERE project_id = $1 AND ip_address = ANY($2::text[])
`

type SelectExistingHostIPLiteralsParams struct {
	ProjectID int32    `json:"project_id"`
	Addrs     []string `json:"addrs"`
}

func (q *Queries) SelectExistingHostIPLiterals(ctx context.Context, arg SelectExistingHostIPLiteralsParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, selectExistingHostIPLiterals, arg.ProjectID, arg.Addrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var ip_address pgtype.Text
		if err := rows.Scan(&ip_address); err != nil {
			return nil, err
		}
		items = append(items, ip_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectExistingHostnames = `-- name: SelectExistingHostnames :many

SELECT hostname FROM hosts
WHERE project_id = $1 AND hostname = ANY($2::text[])
`

type SelectExistingHostnamesParams struct {
	ProjectID int32    `json:"project_id"`
	Names     []string `json:"names"`
}

// ─────────── existing-target keys (create_job) ───────────
func (q *Queries) SelectExistingHostnames(ctx context.Context, arg SelectExistingHostnamesParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, selectExistingHostnames, arg.ProjectID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var hostname pgtype.Text
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectExistingOriginIPAddresses = `-- name: SelectExistingOriginIPAddresses :many
SELECT hia.ip_address FROM host_ip_addresses hia
JOIN hosts h ON h.id = hia.host_id
WHERE h.project_id = $1 AND h.origin = 'ip'
  AND hia.ip_address = ANY($2::text[])
`

type SelectExistingOriginIPAddressesParams struct {
	ProjectID int32    `json:"project_id"`
	Addrs     []string `json:"addrs"`
}

func (q *Queries) SelectExistingOriginIPAddresses(ctx context.Context, arg SelectExistingOriginIPAddressesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, selectExistingOriginIPAddresses, arg.ProjectID, arg.Addrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ip_address string
		if err := rows.Scan(&ip_address); err != nil {
			return nil, err
		}
		items = append(items, ip_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPendingReconJobsExcludingKind = `-- name: SelectPendingReconJobsExcludingKind :many

SELECT id FROM host_farm_jobs
WHERE (status = 'pending' OR (status = 'failed' AND attempts < $1))
  AND kind <> $2
ORDER BY created_at ASC
LIMIT $3
`

type SelectPendingReconJobsExcludingKindParams struct {
	MaxAttempts int32  `json:"max_attempts"`
	Kind        string `json:"kind"`
	Lim         int32  `json:"lim"`
}

// Воркер гоняет ДВЕ независимые дорожки: «обычная» (все kind, кроме farm_run —
// держит add-hosts/add-ips/port-scan отзывчивыми) и «фермовая» (только farm_run,
// долгие прогоны). Отсюда — выборка/реклейм с фильтром по kind, чтобы дорожки не
// мешали друг другу: длинный farm_run не блокирует обычные задачи, а реклейм
// обычной дорожки НИКОГДА не трогает бегущий farm_run (и наоборот).
// Pending обычной дорожки: всё, КРОМЕ переданного kind (= 'farm_run').
func (q *Queries) SelectPendingReconJobsExcludingKind(ctx context.Context, arg SelectPendingReconJobsExcludingKindParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, selectPendingReconJobsExcludingKind, arg.MaxAttempts, arg.Kind, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPendingReconJobsForKind = `-- name: SelectPendingReconJobsForKind :many
SELECT id FROM host_farm_jobs
WHERE (status = 'pending' OR (status = 'failed' AND attempts < $1))
  AND kind = $2
ORDER BY created_at ASC
LIMIT $3
`

type SelectPendingReconJobsForKindParams struct {
	MaxAttempts int32  `json:"max_attempts"`
	Kind        string `json:"kind"`
	Lim         int32  `json:"lim"`
}

// Pending фермовой дорожки: только переданный kind (= 'farm_run').
func (q *Queries) SelectPendingReconJobsForKind(ctx context.Context, arg SelectPendingReconJobsForKindParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, selectPendingReconJobsForKind, arg.MaxAttempts, arg.Kind, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFarmCancelSteps = `-- name: SetFarmCancelSteps :exec
UPDATE host_farm_jobs SET cancel_steps = $2, updated_at = now() WHERE id = $1
`

type SetFarmCancelStepsParams struct {
	ID          int32  `json:"id"`
	CancelSteps []byte `json:"cancel_steps"`
}

// Записывает новый массив id шагов к отмене (маршалится в Go после дедупа).
func (q *Queries) SetFarmCancelSteps(ctx context.Context, arg SetFarmCancelStepsParams) error {
	_, err := q.db.Exec(ctx, setFarmCancelSteps, arg.ID, arg.CancelSteps)
	return err
}

const setHostIPCloudflare = `-- name: SetHostIPCloudflare :exec

UPDATE host_ip_addresses SET is_cloudflare = $2, updated_at = now() WHERE id = $1
`

type SetHostIPCloudflareParams struct {
	ID           int32       `json:"id"`
	IsCloudflare pgtype.Bool `json:"is_cloudflare"`
}

// ─────────── host_ip_addresses (ensure_ips) ───────────
func (q *Queries) SetHostIPCloudflare(ctx context.Context, arg SetHostIPCloudflareParams) error {
	_, err := q.db.Exec(ctx, setHostIPCloudflare, arg.ID, arg.IsCloudflare)
	return err
}

const setHostIPHostnames = `-- name: SetHostIPHostnames :exec
UPDATE host_ip_addresses SET hostnames = $2, updated_at = now() WHERE id = $1
`

type SetHostIPHostnamesParams struct {
	ID        int32  `json:"id"`
	Hostnames []byte `json:"hostnames"`
}

func (q *Queries) SetHostIPHostnames(ctx context.Context, arg SetHostIPHostnamesParams) error {
	_, err := q.db.Exec(ctx, setHostIPHostnames, arg.ID, arg.Hostnames)
	return err
}

const setHostStatus = `-- name: SetHostStatus :exec
UPDATE hosts SET status = $2, updated_at = now() WHERE id = $1
`

type SetHostStatusParams struct {
	ID     int32      `json:"id"`
	Status HostStatus `json:"status"`
}

func (q *Queries) SetHostStatus(ctx context.Context, arg SetHostStatusParams) error {
	_, err := q.db.Exec(ctx, setHostStatus, arg.ID, arg.Status)
	return err
}

const setJobCancelled = `-- name: SetJobCancelled :exec
UPDATE host_farm_jobs
SET status = 'cancelled', result = $2, error = NULL, last_error = NULL, finished_at = now(), updated_at = now()
WHERE id = $1
`

type SetJobCancelledParams struct {
	ID     int32  `json:"id"`
	Result []byte `json:"result"`
}

// Помечает прогон отменённым (НЕ провал): status='cancelled', частичный result,
// finished_at=now(). Ошибочные поля чистятся — отмена не является ошибкой.
func (q *Queries) SetJobCancelled(ctx context.Context, arg SetJobCancelledParams) error {
	_, err := q.db.Exec(ctx, setJobCancelled, arg.ID, arg.Result)
	return err
}

const setJobDone = `-- name: SetJobDone :exec
UPDATE host_farm_jobs
SET status = 'done', result = $2, error = NULL, last_error = NULL, finished_at = now(), updated_at = now()
WHERE id = $1
`

type SetJobDoneParams struct {
	ID     int32  `json:"id"`
	Result []byte `json:"result"`
}

func (q *Queries) SetJobDone(ctx context.Context, arg SetJobDoneParams) error {
	_, err := q.db.Exec(ctx, setJobDone, arg.ID, arg.Result)
	return err
}

const setJobFailed = `-- name: SetJobFailed :exec
UPDATE host_farm_jobs
SET status = 'failed', last_error = $1, error = $2,
    finished_at = now(), updated_at = now()
WHERE id = $3
`

type SetJobFailedParams struct {
	LastError pgtype.Text `json:"last_error"`
	Error     pgtype.Text `json:"error"`
	ID        int32       `json:"id"`
}

func (q *Queries) SetJobFailed(ctx context.Context, arg SetJobFailedParams) error {
	_, err := q.db.Exec(ctx, setJobFailed, arg.LastError, arg.Error, arg.ID)
	return err
}

const setJobProgress = `-- name: SetJobProgress :exec
UPDATE host_farm_jobs SET progress = $2, updated_at = now() WHERE id = $1
`

type SetJobProgressParams struct {
	ID       int32  `json:"id"`
	Progress []byte `json:"progress"`
}

// Обновляет JSON-снимок прогресса полного прогона фермы (kind='farm_run') по мере
// продвижения стадий. Тоже сбрасывает updated_at, чтобы reclaim не забрал живую задачу.
func (q *Queries) SetJobProgress(ctx context.Context, arg SetJobProgressParams) error {
	_, err := q.db.Exec(ctx, setJobProgress, arg.ID, arg.Progress)
	return err
}

const setJobQueued = `-- name: SetJobQueued :exec
UPDATE host_farm_jobs SET status = 'queued', published_at = now(), last_error = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) SetJobQueued(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setJobQueued, id)
	return err
}

const setPortStateHTTP = `-- name: SetPortStateHTTP :exec
UPDATE ports SET state = $2, http_status = $3, updated_at = now() WHERE id = $1
`

type SetPortStateHTTPParams struct {
	ID         int32       `json:"id"`
	State      PortState   `json:"state"`
	HttpStatus pgtype.Int4 `json:"http_status"`
}

func (q *Queries) SetPortStateHTTP(ctx context.Context, arg SetPortStateHTTPParams) error {
	_, err := q.db.Exec(ctx, setPortStateHTTP, arg.ID, arg.State, arg.HttpStatus)
	return err
}

const setPortStateOpen = `-- name: SetPortStateOpen :exec
UPDATE ports SET state = 'OPEN', updated_at = now() WHERE id = $1
`

func (q *Queries) SetPortStateOpen(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setPortStateOpen, id)
	return err
}
