// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recon_farm_config.sql

package sqlc

import (
	"context"
)

const getReconFarmConfig = `-- name: GetReconFarmConfig :one

SELECT config FROM recon_farm_config WHERE project_id = $1
`

// Контекст recon: пер-проектная конфигурация фермы. GetReconFarmConfig отдаёт
// сырой JSONB-блоб (Go доклеивает дефолты), Upsert — идемпотентная запись.
func (q *Queries) GetReconFarmConfig(ctx context.Context, projectID int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getReconFarmConfig, projectID)
	var config []byte
	err := row.Scan(&config)
	return config, err
}

const upsertReconFarmConfig = `-- name: UpsertReconFarmConfig :exec
INSERT INTO recon_farm_config (project_id, config, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (project_id) DO UPDATE SET config = EXCLUDED.config, updated_at = now()
`

type UpsertReconFarmConfigParams struct {
	ProjectID int32  `json:"project_id"`
	Config    []byte `json:"config"`
}

func (q *Queries) UpsertReconFarmConfig(ctx context.Context, arg UpsertReconFarmConfigParams) error {
	_, err := q.db.Exec(ctx, upsertReconFarmConfig, arg.ProjectID, arg.Config)
	return err
}
