// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActivePendingInvitationByEmail = `-- name: GetActivePendingInvitationByEmail :one
SELECT id, email, full_name, role, project_role, token_hash, status, expires_at, invited_by, accepted_at, accepted_user_id, created_at, updated_at FROM invitations WHERE email = $1 AND status = 'pending' AND expires_at > now() ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActivePendingInvitationByEmail(ctx context.Context, email string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getActivePendingInvitationByEmail, email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.ProjectRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, email, full_name, role, project_role, token_hash, status, expires_at, invited_by, accepted_at, accepted_user_id, created_at, updated_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id int32) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.ProjectRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, email, full_name, role, project_role, token_hash, status, expires_at, invited_by, accepted_at, accepted_user_id, created_at, updated_at FROM invitations WHERE status = 'pending' ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitations(ctx context.Context) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.ProjectRole,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.InvitedBy,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many

SELECT id, username, email, full_name, avatar_minio_bucket, avatar_minio_key, avatar_content_type, avatar_uploaded_at, password_hash, password_changed_at, totp_secret, totp_enabled, totp_confirmed_at, role, project_role, is_active, is_locked, tags, created_at, updated_at FROM users ORDER BY created_at DESC OFFSET $1 LIMIT $2
`

type ListUsersParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

// Запросы контекста users (роутер users.py). Часть операций переиспользует
// запросы из auth.sql (GetUserByID/ByUsername/ByEmail, Username/EmailExists,
// UpdateUserPassword, SetUserLocked/Active, EnableUserTotp/DisableUserTotp,
// RevokeAllUserRefreshTokens, CreateInvitation, CreateReactivationToken,
// ExpireUserUnusedReactivationTokens, InsertMailJob, InsertAuditLog).
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.AvatarMinioBucket,
			&i.AvatarMinioKey,
			&i.AvatarContentType,
			&i.AvatarUploadedAt,
			&i.PasswordHash,
			&i.PasswordChangedAt,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.TotpConfirmedAt,
			&i.Role,
			&i.ProjectRole,
			&i.IsActive,
			&i.IsLocked,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserPasswordTemp = `-- name: ResetUserPasswordTemp :exec
UPDATE users SET password_hash = $2, password_changed_at = NULL WHERE id = $1
`

type ResetUserPasswordTempParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) ResetUserPasswordTemp(ctx context.Context, arg ResetUserPasswordTempParams) error {
	_, err := q.db.Exec(ctx, resetUserPasswordTemp, arg.ID, arg.PasswordHash)
	return err
}

const setUserAvatar = `-- name: SetUserAvatar :exec
UPDATE users
SET avatar_minio_bucket = $2, avatar_minio_key = $3, avatar_content_type = $4, avatar_uploaded_at = now()
WHERE id = $1
`

type SetUserAvatarParams struct {
	ID                int32       `json:"id"`
	AvatarMinioBucket pgtype.Text `json:"avatar_minio_bucket"`
	AvatarMinioKey    pgtype.Text `json:"avatar_minio_key"`
	AvatarContentType pgtype.Text `json:"avatar_content_type"`
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) error {
	_, err := q.db.Exec(ctx, setUserAvatar,
		arg.ID,
		arg.AvatarMinioBucket,
		arg.AvatarMinioKey,
		arg.AvatarContentType,
	)
	return err
}

const setUserTotpSecretForSetup = `-- name: SetUserTotpSecretForSetup :exec
UPDATE users SET totp_secret = $2, totp_confirmed_at = NULL WHERE id = $1
`

type SetUserTotpSecretForSetupParams struct {
	ID         int32       `json:"id"`
	TotpSecret pgtype.Text `json:"totp_secret"`
}

func (q *Queries) SetUserTotpSecretForSetup(ctx context.Context, arg SetUserTotpSecretForSetupParams) error {
	_, err := q.db.Exec(ctx, setUserTotpSecretForSetup, arg.ID, arg.TotpSecret)
	return err
}

const updateInvitationForResend = `-- name: UpdateInvitationForResend :exec
UPDATE invitations SET token_hash = $2, status = 'pending', expires_at = $3 WHERE id = $1
`

type UpdateInvitationForResendParams struct {
	ID        int32              `json:"id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateInvitationForResend(ctx context.Context, arg UpdateInvitationForResendParams) error {
	_, err := q.db.Exec(ctx, updateInvitationForResend, arg.ID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :exec
UPDATE users SET full_name = $2, role = $3, project_role = $4, is_active = $5 WHERE id = $1
`

type UpdateUserAdminParams struct {
	ID          int32       `json:"id"`
	FullName    pgtype.Text `json:"full_name"`
	Role        UserRole    `json:"role"`
	ProjectRole ProjectRole `json:"project_role"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) error {
	_, err := q.db.Exec(ctx, updateUserAdmin,
		arg.ID,
		arg.FullName,
		arg.Role,
		arg.ProjectRole,
		arg.IsActive,
	)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET username = $2, email = $3, full_name = $4 WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID       int32       `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	FullName pgtype.Text `json:"full_name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FullName,
	)
	return err
}
