// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vulns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearCommentMentions = `-- name: ClearCommentMentions :exec
DELETE FROM comment_mentions WHERE comment_id = $1
`

func (q *Queries) ClearCommentMentions(ctx context.Context, commentID int32) error {
	_, err := q.db.Exec(ctx, clearCommentMentions, commentID)
	return err
}

const countFileImagesForVuln = `-- name: CountFileImagesForVuln :one
SELECT count(*) FROM files WHERE vulnerability_id = $1 AND id = ANY($2::int[])
`

type CountFileImagesForVulnParams struct {
	VulnerabilityID int32   `json:"vulnerability_id"`
	Ids             []int32 `json:"ids"`
}

func (q *Queries) CountFileImagesForVuln(ctx context.Context, arg CountFileImagesForVulnParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFileImagesForVuln, arg.VulnerabilityID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHostAssetLinks = `-- name: CountHostAssetLinks :one
SELECT count(*) FROM vulnerability_assets WHERE vulnerability_id = $1 AND asset_type = 'HOST'
`

func (q *Queries) CountHostAssetLinks(ctx context.Context, vulnerabilityID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countHostAssetLinks, vulnerabilityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVulnComments = `-- name: CountVulnComments :one
SELECT count(*) FROM comments WHERE vulnerability_id = $1
`

// ─────────── comments ───────────
func (q *Queries) CountVulnComments(ctx context.Context, vulnerabilityID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countVulnComments, vulnerabilityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVulns = `-- name: CountVulns :one
SELECT count(*) FROM vulnerabilities v
WHERE v.project_id = $1
  AND ($2::vuln_severity IS NULL OR v.severity = $2)
  AND ($3::vuln_status IS NULL OR v.status = $3)
`

type CountVulnsParams struct {
	ProjectID int32            `json:"project_id"`
	Severity  NullVulnSeverity `json:"severity"`
	Status    NullVulnStatus   `json:"status"`
}

func (q *Queries) CountVulns(ctx context.Context, arg CountVulnsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVulns, arg.ProjectID, arg.Severity, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVulnsForHost = `-- name: CountVulnsForHost :one
SELECT count(*) FROM vulnerabilities v
JOIN vulnerability_assets va ON va.vulnerability_id = v.id AND va.asset_type = 'HOST' AND va.asset_id = $1
WHERE v.project_id = $2
  AND ($3::vuln_severity IS NULL OR v.severity = $3)
  AND ($4::vuln_status IS NULL OR v.status = $4)
`

type CountVulnsForHostParams struct {
	HostID    int32            `json:"host_id"`
	ProjectID int32            `json:"project_id"`
	Severity  NullVulnSeverity `json:"severity"`
	Status    NullVulnStatus   `json:"status"`
}

func (q *Queries) CountVulnsForHost(ctx context.Context, arg CountVulnsForHostParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVulnsForHost,
		arg.HostID,
		arg.ProjectID,
		arg.Severity,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteVuln = `-- name: DeleteVuln :exec
DELETE FROM vulnerabilities WHERE id = $1
`

func (q *Queries) DeleteVuln(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVuln, id)
	return err
}

const deleteVulnAsset = `-- name: DeleteVulnAsset :exec
DELETE FROM vulnerability_assets WHERE id = $1
`

func (q *Queries) DeleteVulnAsset(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVulnAsset, id)
	return err
}

const deleteVulnComment = `-- name: DeleteVulnComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteVulnComment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVulnComment, id)
	return err
}

const endpointAssetInProject = `-- name: EndpointAssetInProject :one
SELECT EXISTS (SELECT 1 FROM endpoints e JOIN hosts h ON h.id = e.host_id WHERE e.id = $1 AND h.project_id = $2)
`

type EndpointAssetInProjectParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) EndpointAssetInProject(ctx context.Context, arg EndpointAssetInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, endpointAssetInProject, arg.ID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findVulnAsset = `-- name: FindVulnAsset :one
SELECT id, vulnerability_id, asset_type, asset_id FROM vulnerability_assets WHERE vulnerability_id = $1 AND asset_type = $2 AND asset_id = $3
`

type FindVulnAssetParams struct {
	VulnerabilityID int32     `json:"vulnerability_id"`
	AssetType       AssetType `json:"asset_type"`
	AssetID         int32     `json:"asset_id"`
}

func (q *Queries) FindVulnAsset(ctx context.Context, arg FindVulnAssetParams) (VulnerabilityAsset, error) {
	row := q.db.QueryRow(ctx, findVulnAsset, arg.VulnerabilityID, arg.AssetType, arg.AssetID)
	var i VulnerabilityAsset
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.AssetType,
		&i.AssetID,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, vulnerability_id, original_name, content_type, size_bytes, minio_bucket, minio_key, uploaded_by, uploaded_at FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.MinioBucket,
		&i.MinioKey,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getFileForVuln = `-- name: GetFileForVuln :one
SELECT id, vulnerability_id, original_name, content_type, size_bytes, minio_bucket, minio_key, uploaded_by, uploaded_at FROM files WHERE id = $1 AND vulnerability_id = $2
`

type GetFileForVulnParams struct {
	ID              int32 `json:"id"`
	VulnerabilityID int32 `json:"vulnerability_id"`
}

func (q *Queries) GetFileForVuln(ctx context.Context, arg GetFileForVulnParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileForVuln, arg.ID, arg.VulnerabilityID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.MinioBucket,
		&i.MinioKey,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getVuln = `-- name: GetVuln :one

SELECT v.id, v.project_id, v.title, v.description, v.severity, v.cvss_version, v.cvss_score, v.cvss_vector, v.cwe_id, v.status, v.workflow_steps, v.steps_to_reproduce, v.impact, v.recommendations, v.created_by, v.created_at, v.updated_at, u.username AS created_by_username
FROM vulnerabilities v LEFT JOIN users u ON u.id = v.created_by
WHERE v.id = $1 AND v.project_id = $2
`

type GetVulnParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

type GetVulnRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Severity          VulnSeverity       `json:"severity"`
	CvssVersion       NullCvssVersion    `json:"cvss_version"`
	CvssScore         *float64           `json:"cvss_score"`
	CvssVector        pgtype.Text        `json:"cvss_vector"`
	CweID             pgtype.Text        `json:"cwe_id"`
	Status            VulnStatus         `json:"status"`
	WorkflowSteps     []byte             `json:"workflow_steps"`
	StepsToReproduce  pgtype.Text        `json:"steps_to_reproduce"`
	Impact            pgtype.Text        `json:"impact"`
	Recommendations   pgtype.Text        `json:"recommendations"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

// Контекст vulns: vulnerabilities (+CVSS 4.0), assets, comments/mentions, files.
// ─────────── vulnerabilities ───────────
func (q *Queries) GetVuln(ctx context.Context, arg GetVulnParams) (GetVulnRow, error) {
	row := q.db.QueryRow(ctx, getVuln, arg.ID, arg.ProjectID)
	var i GetVulnRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssVersion,
		&i.CvssScore,
		&i.CvssVector,
		&i.CweID,
		&i.Status,
		&i.WorkflowSteps,
		&i.StepsToReproduce,
		&i.Impact,
		&i.Recommendations,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUsername,
	)
	return i, err
}

const getVulnAssetLink = `-- name: GetVulnAssetLink :one
SELECT id, vulnerability_id, asset_type, asset_id FROM vulnerability_assets WHERE id = $1 AND vulnerability_id = $2
`

type GetVulnAssetLinkParams struct {
	ID              int32 `json:"id"`
	VulnerabilityID int32 `json:"vulnerability_id"`
}

func (q *Queries) GetVulnAssetLink(ctx context.Context, arg GetVulnAssetLinkParams) (VulnerabilityAsset, error) {
	row := q.db.QueryRow(ctx, getVulnAssetLink, arg.ID, arg.VulnerabilityID)
	var i VulnerabilityAsset
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.AssetType,
		&i.AssetID,
	)
	return i, err
}

const getVulnComment = `-- name: GetVulnComment :one
SELECT id, vulnerability_id, user_id, content, created_at, updated_at FROM comments WHERE id = $1 AND vulnerability_id = $2
`

type GetVulnCommentParams struct {
	ID              int32 `json:"id"`
	VulnerabilityID int32 `json:"vulnerability_id"`
}

func (q *Queries) GetVulnComment(ctx context.Context, arg GetVulnCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getVulnComment, arg.ID, arg.VulnerabilityID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hostAssetInProject = `-- name: HostAssetInProject :one
SELECT EXISTS (SELECT 1 FROM hosts WHERE id = $1 AND project_id = $2)
`

type HostAssetInProjectParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

// asset-in-project existence checks (polymorphic)
func (q *Queries) HostAssetInProject(ctx context.Context, arg HostAssetInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostAssetInProject, arg.ID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hostExistsInProject = `-- name: HostExistsInProject :one
SELECT EXISTS (SELECT 1 FROM hosts WHERE id = $1 AND project_id = $2)
`

type HostExistsInProjectParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) HostExistsInProject(ctx context.Context, arg HostExistsInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, hostExistsInProject, arg.ID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCommentMention = `-- name: InsertCommentMention :exec
INSERT INTO comment_mentions (comment_id, user_id) VALUES ($1, $2)
ON CONFLICT ON CONSTRAINT uq_comment_mention DO NOTHING
`

type InsertCommentMentionParams struct {
	CommentID int32 `json:"comment_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) InsertCommentMention(ctx context.Context, arg InsertCommentMentionParams) error {
	_, err := q.db.Exec(ctx, insertCommentMention, arg.CommentID, arg.UserID)
	return err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (vulnerability_id, original_name, content_type, size_bytes, minio_bucket, minio_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, vulnerability_id, original_name, content_type, size_bytes, minio_bucket, minio_key, uploaded_by, uploaded_at
`

type InsertFileParams struct {
	VulnerabilityID int32  `json:"vulnerability_id"`
	OriginalName    string `json:"original_name"`
	ContentType     string `json:"content_type"`
	SizeBytes       int64  `json:"size_bytes"`
	MinioBucket     string `json:"minio_bucket"`
	MinioKey        string `json:"minio_key"`
	UploadedBy      int32  `json:"uploaded_by"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.VulnerabilityID,
		arg.OriginalName,
		arg.ContentType,
		arg.SizeBytes,
		arg.MinioBucket,
		arg.MinioKey,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.MinioBucket,
		&i.MinioKey,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const insertMentionNotification = `-- name: InsertMentionNotification :exec
INSERT INTO notifications (user_id, type, comment_id, actor_id, is_read)
VALUES ($1, 'MENTION', $2, $3, false)
`

type InsertMentionNotificationParams struct {
	UserID    int32       `json:"user_id"`
	CommentID pgtype.Int4 `json:"comment_id"`
	ActorID   pgtype.Int4 `json:"actor_id"`
}

// ─────────── notifications ───────────
func (q *Queries) InsertMentionNotification(ctx context.Context, arg InsertMentionNotificationParams) error {
	_, err := q.db.Exec(ctx, insertMentionNotification, arg.UserID, arg.CommentID, arg.ActorID)
	return err
}

const insertVuln = `-- name: InsertVuln :one
INSERT INTO vulnerabilities (project_id, title, description, severity, cvss_version, cvss_score,
    cvss_vector, cwe_id, status, workflow_steps, steps_to_reproduce, impact, recommendations, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING id, project_id, title, description, severity, cvss_version, cvss_score, cvss_vector, cwe_id, status, workflow_steps, steps_to_reproduce, impact, recommendations, created_by, created_at, updated_at
`

type InsertVulnParams struct {
	ProjectID        int32           `json:"project_id"`
	Title            string          `json:"title"`
	Description      pgtype.Text     `json:"description"`
	Severity         VulnSeverity    `json:"severity"`
	CvssVersion      NullCvssVersion `json:"cvss_version"`
	CvssScore        *float64        `json:"cvss_score"`
	CvssVector       pgtype.Text     `json:"cvss_vector"`
	CweID            pgtype.Text     `json:"cwe_id"`
	Status           VulnStatus      `json:"status"`
	WorkflowSteps    []byte          `json:"workflow_steps"`
	StepsToReproduce pgtype.Text     `json:"steps_to_reproduce"`
	Impact           pgtype.Text     `json:"impact"`
	Recommendations  pgtype.Text     `json:"recommendations"`
	CreatedBy        int32           `json:"created_by"`
}

func (q *Queries) InsertVuln(ctx context.Context, arg InsertVulnParams) (Vulnerability, error) {
	row := q.db.QueryRow(ctx, insertVuln,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.CvssVersion,
		arg.CvssScore,
		arg.CvssVector,
		arg.CweID,
		arg.Status,
		arg.WorkflowSteps,
		arg.StepsToReproduce,
		arg.Impact,
		arg.Recommendations,
		arg.CreatedBy,
	)
	var i Vulnerability
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssVersion,
		&i.CvssScore,
		&i.CvssVector,
		&i.CweID,
		&i.Status,
		&i.WorkflowSteps,
		&i.StepsToReproduce,
		&i.Impact,
		&i.Recommendations,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVulnAsset = `-- name: InsertVulnAsset :one
INSERT INTO vulnerability_assets (vulnerability_id, asset_type, asset_id) VALUES ($1, $2, $3) RETURNING id, vulnerability_id, asset_type, asset_id
`

type InsertVulnAssetParams struct {
	VulnerabilityID int32     `json:"vulnerability_id"`
	AssetType       AssetType `json:"asset_type"`
	AssetID         int32     `json:"asset_id"`
}

func (q *Queries) InsertVulnAsset(ctx context.Context, arg InsertVulnAssetParams) (VulnerabilityAsset, error) {
	row := q.db.QueryRow(ctx, insertVulnAsset, arg.VulnerabilityID, arg.AssetType, arg.AssetID)
	var i VulnerabilityAsset
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.AssetType,
		&i.AssetID,
	)
	return i, err
}

const insertVulnComment = `-- name: InsertVulnComment :one
INSERT INTO comments (vulnerability_id, user_id, content) VALUES ($1, $2, $3) RETURNING id, vulnerability_id, user_id, content, created_at, updated_at
`

type InsertVulnCommentParams struct {
	VulnerabilityID int32  `json:"vulnerability_id"`
	UserID          int32  `json:"user_id"`
	Content         string `json:"content"`
}

func (q *Queries) InsertVulnComment(ctx context.Context, arg InsertVulnCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, insertVulnComment, arg.VulnerabilityID, arg.UserID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VulnerabilityID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVulnStatusNotification = `-- name: InsertVulnStatusNotification :exec
INSERT INTO notifications (user_id, type, vulnerability_id, project_id, actor_id, status, is_read)
VALUES ($1, 'VULN_STATUS_CHANGED', $2, $3, $4, $5, false)
`

type InsertVulnStatusNotificationParams struct {
	UserID          int32       `json:"user_id"`
	VulnerabilityID pgtype.Int4 `json:"vulnerability_id"`
	ProjectID       pgtype.Int4 `json:"project_id"`
	ActorID         pgtype.Int4 `json:"actor_id"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) InsertVulnStatusNotification(ctx context.Context, arg InsertVulnStatusNotificationParams) error {
	_, err := q.db.Exec(ctx, insertVulnStatusNotification,
		arg.UserID,
		arg.VulnerabilityID,
		arg.ProjectID,
		arg.ActorID,
		arg.Status,
	)
	return err
}

const listCommentMentions = `-- name: ListCommentMentions :many
SELECT cm.user_id, u.username FROM comment_mentions cm JOIN users u ON u.id = cm.user_id
WHERE cm.comment_id = $1 ORDER BY cm.id
`

type ListCommentMentionsRow struct {
	UserID   int32  `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) ListCommentMentions(ctx context.Context, commentID int32) ([]ListCommentMentionsRow, error) {
	rows, err := q.db.Query(ctx, listCommentMentions, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentMentionsRow{}
	for rows.Next() {
		var i ListCommentMentionsRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulnAssets = `-- name: ListVulnAssets :many
SELECT id, vulnerability_id, asset_type, asset_id FROM vulnerability_assets WHERE vulnerability_id = $1 ORDER BY id
`

// ─────────── vulnerability_assets ───────────
func (q *Queries) ListVulnAssets(ctx context.Context, vulnerabilityID int32) ([]VulnerabilityAsset, error) {
	rows, err := q.db.Query(ctx, listVulnAssets, vulnerabilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VulnerabilityAsset{}
	for rows.Next() {
		var i VulnerabilityAsset
		if err := rows.Scan(
			&i.ID,
			&i.VulnerabilityID,
			&i.AssetType,
			&i.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulnComments = `-- name: ListVulnComments :many
SELECT c.id, c.vulnerability_id, c.user_id, c.content, c.created_at, c.updated_at, u.username, u.avatar_minio_key, u.avatar_uploaded_at
FROM comments c JOIN users u ON u.id = c.user_id
WHERE c.vulnerability_id = $1 ORDER BY c.created_at ASC OFFSET $2 LIMIT $3
`

type ListVulnCommentsParams struct {
	VulnerabilityID int32 `json:"vulnerability_id"`
	Offset          int32 `json:"offset"`
	Limit           int32 `json:"limit"`
}

type ListVulnCommentsRow struct {
	ID               int32              `json:"id"`
	VulnerabilityID  int32              `json:"vulnerability_id"`
	UserID           int32              `json:"user_id"`
	Content          string             `json:"content"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Username         string             `json:"username"`
	AvatarMinioKey   pgtype.Text        `json:"avatar_minio_key"`
	AvatarUploadedAt pgtype.Timestamptz `json:"avatar_uploaded_at"`
}

func (q *Queries) ListVulnComments(ctx context.Context, arg ListVulnCommentsParams) ([]ListVulnCommentsRow, error) {
	rows, err := q.db.Query(ctx, listVulnComments, arg.VulnerabilityID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVulnCommentsRow{}
	for rows.Next() {
		var i ListVulnCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.VulnerabilityID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarMinioKey,
			&i.AvatarUploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulnFiles = `-- name: ListVulnFiles :many
SELECT id, vulnerability_id, original_name, content_type, size_bytes, minio_bucket, minio_key, uploaded_by, uploaded_at FROM files WHERE vulnerability_id = $1 ORDER BY uploaded_at DESC
`

// ─────────── files ───────────
func (q *Queries) ListVulnFiles(ctx context.Context, vulnerabilityID int32) ([]File, error) {
	rows, err := q.db.Query(ctx, listVulnFiles, vulnerabilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.VulnerabilityID,
			&i.OriginalName,
			&i.ContentType,
			&i.SizeBytes,
			&i.MinioBucket,
			&i.MinioKey,
			&i.UploadedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulns = `-- name: ListVulns :many
SELECT v.id, v.project_id, v.title, v.description, v.severity, v.cvss_version, v.cvss_score, v.cvss_vector, v.cwe_id, v.status, v.workflow_steps, v.steps_to_reproduce, v.impact, v.recommendations, v.created_by, v.created_at, v.updated_at, u.username AS created_by_username
FROM vulnerabilities v LEFT JOIN users u ON u.id = v.created_by
WHERE v.project_id = $1
  AND ($2::vuln_severity IS NULL OR v.severity = $2)
  AND ($3::vuln_status IS NULL OR v.status = $3)
ORDER BY v.created_at DESC OFFSET $4 LIMIT $5
`

type ListVulnsParams struct {
	ProjectID int32            `json:"project_id"`
	Severity  NullVulnSeverity `json:"severity"`
	Status    NullVulnStatus   `json:"status"`
	Offset    int32            `json:"offset"`
	Lim       int32            `json:"lim"`
}

type ListVulnsRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Severity          VulnSeverity       `json:"severity"`
	CvssVersion       NullCvssVersion    `json:"cvss_version"`
	CvssScore         *float64           `json:"cvss_score"`
	CvssVector        pgtype.Text        `json:"cvss_vector"`
	CweID             pgtype.Text        `json:"cwe_id"`
	Status            VulnStatus         `json:"status"`
	WorkflowSteps     []byte             `json:"workflow_steps"`
	StepsToReproduce  pgtype.Text        `json:"steps_to_reproduce"`
	Impact            pgtype.Text        `json:"impact"`
	Recommendations   pgtype.Text        `json:"recommendations"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

func (q *Queries) ListVulns(ctx context.Context, arg ListVulnsParams) ([]ListVulnsRow, error) {
	rows, err := q.db.Query(ctx, listVulns,
		arg.ProjectID,
		arg.Severity,
		arg.Status,
		arg.Offset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVulnsRow{}
	for rows.Next() {
		var i ListVulnsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssVersion,
			&i.CvssScore,
			&i.CvssVector,
			&i.CweID,
			&i.Status,
			&i.WorkflowSteps,
			&i.StepsToReproduce,
			&i.Impact,
			&i.Recommendations,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVulnsForHost = `-- name: ListVulnsForHost :many
SELECT v.id, v.project_id, v.title, v.description, v.severity, v.cvss_version, v.cvss_score, v.cvss_vector, v.cwe_id, v.status, v.workflow_steps, v.steps_to_reproduce, v.impact, v.recommendations, v.created_by, v.created_at, v.updated_at, u.username AS created_by_username
FROM vulnerabilities v
JOIN vulnerability_assets va ON va.vulnerability_id = v.id AND va.asset_type = 'HOST' AND va.asset_id = $1
LEFT JOIN users u ON u.id = v.created_by
WHERE v.project_id = $2
  AND ($3::vuln_severity IS NULL OR v.severity = $3)
  AND ($4::vuln_status IS NULL OR v.status = $4)
ORDER BY v.created_at DESC OFFSET $5 LIMIT $6
`

type ListVulnsForHostParams struct {
	HostID    int32            `json:"host_id"`
	ProjectID int32            `json:"project_id"`
	Severity  NullVulnSeverity `json:"severity"`
	Status    NullVulnStatus   `json:"status"`
	Offset    int32            `json:"offset"`
	Lim       int32            `json:"lim"`
}

type ListVulnsForHostRow struct {
	ID                int32              `json:"id"`
	ProjectID         int32              `json:"project_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Severity          VulnSeverity       `json:"severity"`
	CvssVersion       NullCvssVersion    `json:"cvss_version"`
	CvssScore         *float64           `json:"cvss_score"`
	CvssVector        pgtype.Text        `json:"cvss_vector"`
	CweID             pgtype.Text        `json:"cwe_id"`
	Status            VulnStatus         `json:"status"`
	WorkflowSteps     []byte             `json:"workflow_steps"`
	StepsToReproduce  pgtype.Text        `json:"steps_to_reproduce"`
	Impact            pgtype.Text        `json:"impact"`
	Recommendations   pgtype.Text        `json:"recommendations"`
	CreatedBy         int32              `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername pgtype.Text        `json:"created_by_username"`
}

func (q *Queries) ListVulnsForHost(ctx context.Context, arg ListVulnsForHostParams) ([]ListVulnsForHostRow, error) {
	rows, err := q.db.Query(ctx, listVulnsForHost,
		arg.HostID,
		arg.ProjectID,
		arg.Severity,
		arg.Status,
		arg.Offset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVulnsForHostRow{}
	for rows.Next() {
		var i ListVulnsForHostRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssVersion,
			&i.CvssScore,
			&i.CvssVector,
			&i.CweID,
			&i.Status,
			&i.WorkflowSteps,
			&i.StepsToReproduce,
			&i.Impact,
			&i.Recommendations,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchVulnStatus = `-- name: PatchVulnStatus :one
UPDATE vulnerabilities SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, project_id, title, description, severity, cvss_version, cvss_score, cvss_vector, cwe_id, status, workflow_steps, steps_to_reproduce, impact, recommendations, created_by, created_at, updated_at
`

type PatchVulnStatusParams struct {
	ID     int32      `json:"id"`
	Status VulnStatus `json:"status"`
}

func (q *Queries) PatchVulnStatus(ctx context.Context, arg PatchVulnStatusParams) (Vulnerability, error) {
	row := q.db.QueryRow(ctx, patchVulnStatus, arg.ID, arg.Status)
	var i Vulnerability
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssVersion,
		&i.CvssScore,
		&i.CvssVector,
		&i.CweID,
		&i.Status,
		&i.WorkflowSteps,
		&i.StepsToReproduce,
		&i.Impact,
		&i.Recommendations,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const portAssetInProject = `-- name: PortAssetInProject :one
SELECT EXISTS (SELECT 1 FROM ports p JOIN hosts h ON h.id = p.host_id WHERE p.id = $1 AND h.project_id = $2)
`

type PortAssetInProjectParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) PortAssetInProject(ctx context.Context, arg PortAssetInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, portAssetInProject, arg.ID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const primaryHostID = `-- name: PrimaryHostID :one
SELECT asset_id FROM vulnerability_assets WHERE vulnerability_id = $1 AND asset_type = 'HOST' ORDER BY id LIMIT 1
`

func (q *Queries) PrimaryHostID(ctx context.Context, vulnerabilityID int32) (int32, error) {
	row := q.db.QueryRow(ctx, primaryHostID, vulnerabilityID)
	var asset_id int32
	err := row.Scan(&asset_id)
	return asset_id, err
}

const resolveCommentMentionUsers = `-- name: ResolveCommentMentionUsers :many
SELECT u.id, u.username FROM users u
LEFT JOIN project_members pm ON pm.user_id = u.id AND pm.project_id = $1
WHERE u.username = ANY($2::text[]) AND (pm.user_id IS NOT NULL OR u.role = 'ADMIN')
`

type ResolveCommentMentionUsersParams struct {
	ProjectID int32    `json:"project_id"`
	Usernames []string `json:"usernames"`
}

type ResolveCommentMentionUsersRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

// ─────────── comment mentions ───────────
func (q *Queries) ResolveCommentMentionUsers(ctx context.Context, arg ResolveCommentMentionUsersParams) ([]ResolveCommentMentionUsersRow, error) {
	rows, err := q.db.Query(ctx, resolveCommentMentionUsers, arg.ProjectID, arg.Usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveCommentMentionUsersRow{}
	for rows.Next() {
		var i ResolveCommentMentionUsersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceAssetInProject = `-- name: ServiceAssetInProject :one
SELECT EXISTS (SELECT 1 FROM services s JOIN ports p ON p.id = s.port_id JOIN hosts h ON h.id = p.host_id WHERE s.id = $1 AND h.project_id = $2)
`

type ServiceAssetInProjectParams struct {
	ID        int32 `json:"id"`
	ProjectID int32 `json:"project_id"`
}

func (q *Queries) ServiceAssetInProject(ctx context.Context, arg ServiceAssetInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceAssetInProject, arg.ID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateVuln = `-- name: UpdateVuln :one
UPDATE vulnerabilities SET title = $2, description = $3, severity = $4, cvss_version = $5,
    cvss_score = $6, cvss_vector = $7, cwe_id = $8, status = $9, workflow_steps = $10,
    steps_to_reproduce = $11, impact = $12, recommendations = $13, updated_at = now()
WHERE id = $1 RETURNING id, project_id, title, description, severity, cvss_version, cvss_score, cvss_vector, cwe_id, status, workflow_steps, steps_to_reproduce, impact, recommendations, created_by, created_at, updated_at
`

type UpdateVulnParams struct {
	ID               int32           `json:"id"`
	Title            string          `json:"title"`
	Description      pgtype.Text     `json:"description"`
	Severity         VulnSeverity    `json:"severity"`
	CvssVersion      NullCvssVersion `json:"cvss_version"`
	CvssScore        *float64        `json:"cvss_score"`
	CvssVector       pgtype.Text     `json:"cvss_vector"`
	CweID            pgtype.Text     `json:"cwe_id"`
	Status           VulnStatus      `json:"status"`
	WorkflowSteps    []byte          `json:"workflow_steps"`
	StepsToReproduce pgtype.Text     `json:"steps_to_reproduce"`
	Impact           pgtype.Text     `json:"impact"`
	Recommendations  pgtype.Text     `json:"recommendations"`
}

func (q *Queries) UpdateVuln(ctx context.Context, arg UpdateVulnParams) (Vulnerability, error) {
	row := q.db.QueryRow(ctx, updateVuln,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.CvssVersion,
		arg.CvssScore,
		arg.CvssVector,
		arg.CweID,
		arg.Status,
		arg.WorkflowSteps,
		arg.StepsToReproduce,
		arg.Impact,
		arg.Recommendations,
	)
	var i Vulnerability
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssVersion,
		&i.CvssScore,
		&i.CvssVector,
		&i.CweID,
		&i.Status,
		&i.WorkflowSteps,
		&i.StepsToReproduce,
		&i.Impact,
		&i.Recommendations,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVulnComment = `-- name: UpdateVulnComment :exec
UPDATE comments SET content = $2, updated_at = now() WHERE id = $1
`

type UpdateVulnCommentParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateVulnComment(ctx context.Context, arg UpdateVulnCommentParams) error {
	_, err := q.db.Exec(ctx, updateVulnComment, arg.ID, arg.Content)
	return err
}
