// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wordlists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWordlist = `-- name: DeleteWordlist :execrows
DELETE FROM recon_wordlists WHERE id = $1
`

// Удаляет строку словаря по id; число удалённых (0 = не было).
func (q *Queries) DeleteWordlist(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWordlist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWordlist = `-- name: GetWordlist :one
SELECT id, name, object_key, size_bytes, lines, uploaded_by, created_at
FROM recon_wordlists
WHERE id = $1
`

// Один словарь по id (для материализации / удаления).
func (q *Queries) GetWordlist(ctx context.Context, id int32) (ReconWordlist, error) {
	row := q.db.QueryRow(ctx, getWordlist, id)
	var i ReconWordlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Lines,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertWordlist = `-- name: InsertWordlist :one

INSERT INTO recon_wordlists (name, object_key, size_bytes, lines, uploaded_by)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, name, object_key, size_bytes, lines, uploaded_by, created_at
`

type InsertWordlistParams struct {
	Name       string      `json:"name"`
	ObjectKey  string      `json:"object_key"`
	SizeBytes  pgtype.Int8 `json:"size_bytes"`
	Lines      pgtype.Int4 `json:"lines"`
	UploadedBy pgtype.Int4 `json:"uploaded_by"`
}

// Контекст recon: пользовательские словари (recon_wordlists), workspace-level.
// object_key — серверный ключ MinIO ('wordlists/{uuid}'); name — ярлык (имя файла
// пользователя), в путь НЕ идёт. Читаются списком (GET), точечно по id (материализация
// / удаление), пишутся при загрузке, удаляются вместе с объектом MinIO.
func (q *Queries) InsertWordlist(ctx context.Context, arg InsertWordlistParams) (ReconWordlist, error) {
	row := q.db.QueryRow(ctx, insertWordlist,
		arg.Name,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.Lines,
		arg.UploadedBy,
	)
	var i ReconWordlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Lines,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listWordlists = `-- name: ListWordlists :many
SELECT id, name, object_key, size_bytes, lines, uploaded_by, created_at
FROM recon_wordlists
ORDER BY created_at DESC, id DESC
`

// Все кастомные словари workspace (новые сверху).
func (q *Queries) ListWordlists(ctx context.Context) ([]ReconWordlist, error) {
	rows, err := q.db.Query(ctx, listWordlists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconWordlist{}
	for rows.Next() {
		var i ReconWordlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.Lines,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
